// ════════════════════════════════════════════════════
// AMSCOPE
// ════════════════════════════════════════════════════
DB.companies.push({id:"amscope",name:"AmScope",shortName:"AmScope",flag:"🇺🇸",country:"USA",
 founded:2006,status:"active",featured:false,hq:"Irvine, California, USA",
 categories:["compound","stereo"],
 overview:"AmScope (United Scope LLC) is the dominant value microscope brand in the USA, Canada, and UK. Founded around 2006, they have become the top-selling microscope brand on Amazon. Their product range is far broader than most buyers realize — spanning basic beginner scopes to darkfield, polarizing, fluorescence, metallurgical, and inverted systems. Products are organized in clear tier families: M150 (beginner), B/T-series (student/professional), 490-series (veterinary/clinical), and SE/ZM/SM-series (stereo). AmScope also operates a comprehensive accessories division making them a practical one-stop source for hobbyists and budget labs.",
 oem:{acquiredBy:null,acquired:[],makesFor:[],madeBy:["United Scope LLC — Chinese OEM manufacturing network"],notes:"AmScope sources all instruments from Chinese OEM manufacturers. Models are frequently the same platform also sold by OMAX, Amado, Richter Optica, and other online brands at similar price points."},
 models:[
  {id:"amscope-m150",name:"M150 Series",series:"M",type:"compound",subtype:"student / beginner monocular / binocular",
   introduced:2008,discontinued:false,price_tier:"budget",price_new:"$50–$130",price_used:"$20–$60",
   illumination:["LED sub-stage","Fixed intensity"],
   magnification:"40x–2000x (monocular) or 40x–2500x (binocular) with 10x + 25x eyepieces",
   objectives:"DIN Achromat 4x/10x/40x/100x; 160mm finite, RMS thread",
   eyepieces:"WF 10x and WF 25x; monocular or binocular head",
   stage:"Single-layer fixed stage (monocular) or simple mechanical stage (binocular)",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["K–12 education","First microscope","Home hobbyist","Science fair"],
   noteworthy:"AmScope’s entry-level line and the first microscope for many hobbyists. Note: the ‘2000x’ marketing claim exceeds useful optical resolution (~1000x for standard achromats). The M150C and M150CB add a built-in camera. A reasonable starter scope; upgrade to the B120 when a mechanical stage becomes a priority.",
   oem_source:null},

  {id:"amscope-b120",name:"B120 / T120 Series",series:"B",type:"compound",subtype:"student / professional binocular compound",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$120–$300",price_used:"$50–$150",
   illumination:["LED (fly-eye lens for uniform illumination)","Daylight-balanced"],
   magnification:"40x–1000x or 40x–2500x depending on eyepiece set",
   objectives:"DIN Achromat 4x/10x/40x/100x; 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; Siedentopf 30° binocular; 360° rotating. T120 = trinocular with camera port.",
   stage:"3D two-layer mechanical stage with low-position controls; centerable Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"AmScope software (with camera)",
   applications:["K–12 education","Introductory college","Clinical basics","Home hobbyist"],
   noteworthy:"AmScope’s best-selling compound microscope and one of the most reviewed on Amazon. Meaningful step up from the M150: proper Siedentopf head, centerable Abbe condenser (essential for Köhler illumination), and full mechanical stage. Uses 160mm finite RMS optics. Darkfield and phase contrast kits available as add-ons.",
   oem_source:null},

  {id:"amscope-b490",name:"B490 / T490 Series",series:"B490",type:"compound",subtype:"professional veterinary / clinical compound",
   introduced:2008,discontinued:false,price_tier:"budget",price_new:"$300–$600",price_used:"$100–$350",
   illumination:["Halogen 6V/20W (original) or LED (current)","Variable intensity; filter holder"],
   magnification:"40x–2000x (4x–100x objectives, 10x eyepieces)",
   objectives:"DIN Achromat 4x/10x/40x/100x oil; 160mm finite, RMS thread.",
   eyepieces:"WF 10x/18mm; Siedentopf 30° binocular (B490) or simul-focal trinocular (T490)",
   stage:"Two-layer mechanical stage; coaxial coarse + fine focus with tension control; achromatic Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Veterinary","Clinical lab","Hematology","Semen analysis","Water testing"],
   noteworthy:"AmScope’s professional workhorse and most popular choice for veterinary practices and small clinical labs. The T490 adds a simul-focal trinocular port (camera and eyepieces active simultaneously). Compensation-free Siedentopf head, vertical stage lock, darkfield and phase contrast condenser accessories available.",
   oem_source:"motic"},

  {id:"amscope-polarizing",name:"P-Series Polarizing",series:"P",type:"compound",subtype:"polarizing compound (budget)",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$200–$500",price_used:"$100–$250",
   illumination:["LED with polarizer below stage","Analyzer above objectives; 360° rotating stage standard"],
   magnification:"40x–1600x (4x–100x objectives, 10x eyepieces)",
   objectives:"Strain-free DIN Achromat 4x/10x/20x/40x; 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; binocular Siedentopf",
   stage:"360° graduated rotating stage; Bertrand lens for conoscopic observation included",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Mineralogy","Petrology","Geology","Materials science","Textile fiber identification"],
   noteworthy:"One of the most affordable entry points into polarized light microscopy. Includes rotating graduated stage, polarizer + analyzer, strain-free objectives, and Bertrand lens for conoscopic work. Adequate for amateur mineralogy, thin section petrology, and basic materials analysis.",
   oem_source:null},

  {id:"amscope-darkfield",name:"Darkfield / DF-Fluorescence Combo",series:"DF",type:"compound",subtype:"darkfield compound (budget)",
   introduced:2012,discontinued:false,price_tier:"budget",price_new:"$300–$800",price_used:"$150–$400",
   illumination:["LED with darkfield dry condenser (standard)","Oil-immersion darkfield condenser (high-NA option)","Some models: darkfield + fluorescence combo"],
   magnification:"40x–1000x for darkfield (100x oil not compatible with darkfield condenser)",
   objectives:"DIN Achromat 4x–40x; 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; binocular or trinocular",
   stage:"Two-layer mechanical stage",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Live microorganisms","Blood analysis","Colloidal particles","Spirochetes","Water life"],
   noteworthy:"One of the few affordable dedicated darkfield microscope options. Dry condenser (central stop) limits NA to ~0.9. Oil-immersion darkfield condensers achieve NA >1.0 for finer structures. Combo DF/fluorescence units add epi-fluorescence for dual-mode use.",
   oem_source:null},

  {id:"amscope-metallurgical",name:"ME / MU Metallurgical Series",series:"ME/MU",type:"compound",subtype:"reflected light / metallurgical compound (budget)",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$300–$700",price_used:"$100–$350",
   illumination:["Reflected (incident) LED from above","Optional transmitted LED"],
   magnification:"50x–1500x (5x–100x objectives, 10x eyepieces)",
   objectives:"Metallurgical DIN Achromat objectives (coverslip-free, marked ‘/0’); 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; binocular or trinocular Siedentopf",
   stage:"Mechanical stage; incident illumination arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Metallurgy","PCB inspection","Mineralogy","Gemology","Surface quality control"],
   noteworthy:"Uses coverslip-free objectives (marked ‘/0’) — NOT compatible with standard biological objectives. Popular with hobbyist metallurgists and electronics repair. Among the most affordable metallurgical microscopes available.",
   oem_source:null},

  {id:"amscope-inverted",name:"Inverted Culture Microscope",series:"IN",type:"compound",subtype:"inverted routine / tissue culture (budget)",
   introduced:2012,discontinued:false,price_tier:"budget",price_new:"$300–$700",price_used:"$100–$350",
   illumination:["LED transmitted (sub-stage)","Variable intensity"],
   magnification:"40x–400x (4x–40x LWD objectives, 10x eyepieces)",
   objectives:"Long working distance (LWD) achromat 4x/10x/20x/40x; 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; binocular or trinocular 30°",
   stage:"Fixed stage; large opening for culture flasks; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"AmScope software",
   applications:["Tissue culture monitoring","Cell biology student","IVF basics","Microbiology education"],
   noteworthy:"Budget inverted for routine tissue culture observation. LWD objectives allow viewing through standard T-flask and petri dish bases. A practical budget alternative to the Zeiss Axiovert 25 or Olympus CKX22. Trinocular version available.",
   oem_source:null},

  {id:"amscope-se-series",name:"SE Series Stereo",series:"SE",type:"stereo",subtype:"zoom stereo (Greenough, entry)",
   introduced:2008,discontinued:false,price_tier:"budget",price_new:"$80–$250",price_used:"$30–$120",
   illumination:["LED incident (top)","LED transmitted (base)","Simultaneous or independent"],
   magnification:"10x–40x or 20x–200x with accessories",
   objectives:"Fixed Greenough zoom body",
   eyepieces:"WF 10x; binocular 45°",
   stage:"Integrated flat base with black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Basic dissection","Stamps and coins","Natural history","Elementary school"],
   noteworthy:"AmScope’s entry stereo family and one of the lowest-cost functional stereo microscopes available. Dual LED illumination (incident + transmitted) is a genuine convenience at this price. Popular with homeschool families and hobbyists. Limited zoom range and non-removable eyepieces on budget models restrict upgrade paths.",
   oem_source:null},

  {id:"amscope-zm-series",name:"ZM / SM Stereo Zoom Series",series:"ZM/SM",type:"stereo",subtype:"zoom stereo (Greenough, prosumer)",
   introduced:2008,discontinued:false,price_tier:"budget",price_new:"$200–$700",price_used:"$80–$350",
   illumination:["Dual LED gooseneck illuminators (standard)","Optional ring light","Optional transmitted base"],
   magnification:"7x–45x or 3.5x–180x depending on configuration; 3.5:1 to 7:1 zoom bodies available",
   objectives:"Fixed Greenough zoom body; 0.5x/0.7x/1.5x/2x auxiliary objectives available",
   eyepieces:"WF 10x/20mm standard; binocular or trinocular; interchangeable",
   stage:"Boom stand, column stand, or flat base options; 76mm neck diameter",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software (with camera)",
   applications:["Dissection","QC inspection","Electronics repair","Entomology","Gemology","Coins","PCB rework"],
   noteworthy:"AmScope’s most popular stereo family. Multiple body variants (ZM3.5, ZM4.5, ZM7, ZM7T). Standard gooseneck illuminators provide directional lighting. 76mm neck diameter compatible with aftermarket stands and ring lights. One of the most recommended stereo setups under $400.",
   oem_source:null},

  {id:"amscope-trinocular-stereo",name:"Trinocular Documentation Stereo",series:"ZM-T/SM-T",type:"stereo",subtype:"zoom stereo (Greenough, trinocular)",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$300–$800",price_used:"$120–$450",
   illumination:["Dual LED gooseneck or ring light","Optional transmitted base"],
   magnification:"3.5x–180x depending on body and auxiliaries",
   objectives:"Fixed Greenough zoom body; auxiliary objectives compatible",
   eyepieces:"WF 10x/20mm; Siedentopf trinocular head; simultaneous eyepiece + camera",
   stage:"Boom stand or column stand; 76mm neck diameter",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Documentation","Teaching","Electronics assembly","QC with video output","Soldering guidance"],
   noteworthy:"Trinocular versions of the ZM/SM zoom stereo family add a vertical camera port. Simul-focal design allows simultaneous eyepiece viewing and camera capture. Popular in electronics workshops for soldering guidance displays and in teaching labs for live video projection.",
   oem_source:null},

  {id:"amscope-boom-stereo",name:"Boom Stand Stereo System",series:"ZM/SM Boom",type:"stereo",subtype:"zoom stereo with boom arm stand",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$250–$700",price_used:"$100–$400",
   illumination:["Dual LED gooseneck","Optional ring light"],
   magnification:"3.5x–180x depending on body",
   objectives:"Fixed Greenough zoom body; auxiliary objectives compatible",
   eyepieces:"WF 10x/20mm; binocular or trinocular",
   stage:"Boom arm stand (no base table obstruction); flexible arm reach",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Large specimen work","Electronics and PCB inspection","Taxidermy","In-situ inspection"],
   noteworthy:"Boom arm configuration moves the microscope off the table base entirely, giving unobstructed access to large or irregularly-shaped specimens. Essential for PCB rework on installed boards and large insect mounting. The 76mm neck diameter means the same ZM/SM zoom heads mount directly onto boom arm stands — users can swap between flat base and boom arm with the same optical head.",
   oem_source:null},

  {id:"amscope-fluorescence-stereo",name:"Fluorescence Stereo Microscope",series:"ZM-FL",type:"stereo",subtype:"zoom stereo with fluorescence (budget)",
   introduced:2015,discontinued:false,price_tier:"mid",price_new:"$800–$2,500",price_used:"$300–$900",
   illumination:["LED incident + transmitted","EPI fluorescence attachment (UV/blue/green excitation options)","Mercury or LED fluorescence light source"],
   magnification:"3.5x–180x (same ZM/SM zoom bodies with fluorescence head)",
   objectives:"Fixed Greenough zoom body",
   eyepieces:"WF 10x/20mm; Siedentopf binocular or trinocular",
   stage:"Fluorescence base with filter cubes",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["GFP screening","Fluorescent mineral observation","Budget developmental biology","Fluorescent dye work"],
   noteworthy:"Budget fluorescence stereo configurations that are rare at this price point. Adequate for GFP-expressing organisms, fluorescent mineral observation, and introductory fluorescence work. Not a substitute for a Leica M205 FA or Zeiss SteREO Discovery, but delivers functional fluorescence stereo capability at a fraction of the cost.",
   oem_source:null},

  {id:"amscope-sm-series",name:"SM Greenough Stereo Series (SM-1B through SM-8B/T)",series:"SM",type:"stereo",subtype:"zoom stereo (Greenough, prosumer)",
   introduced:2008,discontinued:false,price_tier:"budget",
   price_new:"$150–$600",price_used:"$60–$300",
   illumination:["Dual LED gooseneck standard","Optional ring light","Optional transmitted LED base"],
   magnification:"7x–45x or 3.5x–90x depending on configuration; 3.5:1 to 7:1 zoom ratios",
   objectives:"Greenough zoom body; 0.5x/0.7x/1.5x/2x auxiliary objectives available; 76mm neck",
   eyepieces:"WF 10x/20mm standard; binocular or trinocular (T suffix); Siedentopf; 55–75mm IPD",
   stage:"Boom stand, column stand, or flat base; 76mm neck; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Dissection","Electronics","PCB rework","QC inspection","Entomology","Gemology"],
   noteworthy:"AmScope core Greenough stereo family. Numbering convention: B = binocular, T = trinocular; the number suffix indicates configuration package (stand type, illumination, accessories included). Key variants: SM-1B/SM-1T (basic binocular/trinocular on single-arm boom with gooseneck), SM-2T (trinocular with transmitted base), SM-3B/SM-3T (upgraded optics), SM-4B/SM-4T (professional configuration with better stand), SM-6T (trinocular with ring light), SM-7B (heavy-duty boom), SM-8B (premium professional). The optical body is identical across the SM line; differences are primarily stand type, head configuration, and illumination package. 76mm neck compatible with all AmScope stereo stands and ring lights.",
   oem_source:null},

  {id:"amscope-sw-series",name:"SW Stereo Series (SW-2B/T, SW-3B/T)",series:"SW",type:"stereo",subtype:"zoom stereo (Greenough, consumer-prosumer)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$100–$350",price_used:"$40–$180",
   illumination:["LED incident + transmitted (simultaneous or independent)","Variable intensity"],
   magnification:"10x–40x or 7.5x–45x depending on body; 4:1 zoom standard",
   objectives:"Fixed Greenough zoom body; basic auxiliary objectives compatible",
   eyepieces:"WF 10x/20mm; binocular (B) or trinocular (T); 45° incline",
   stage:"Flat base with black/white reversible plate; basic stand",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Education","Basic dissection","Home hobbyist","Electronics student","Stamps and coins"],
   noteworthy:"AmScope entry-to-prosumer Greenough stereo family sold primarily via Amazon. SW-2B (binocular), SW-2T (trinocular): basic flat-base configuration with dual LED illumination. SW-3B (binocular with transmitted), SW-3T (trinocular with transmitted): adds below-stage transmitted illumination for transparent specimens. Simpler mechanics than the SM-series but adequate for education and hobbyist use. Non-Siedentopf head on budget versions. The trinocular (T) versions add a camera port for documentation.",
   oem_source:null},

  {id:"amscope-sz9t",name:"SZ-9T High-Ratio Zoom Stereo",series:"SZ",type:"stereo",subtype:"zoom stereo (Greenough, high zoom ratio)",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$350–$700",price_used:"$120–$400",
   illumination:["Dual LED gooseneck","Optional ring light","Optional transmitted base"],
   magnification:"3.5x–90x (25:1 zoom ratio with 10x eyepieces); up to 270x with 20x eyepieces",
   objectives:"Greenough zoom body 0.35x–9.0x; 76mm neck",
   eyepieces:"WF 10x/20mm; Siedentopf trinocular; 45° incline; 55–75mm IPD",
   stage:"Boom stand standard; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Electronics inspection","PCB assembly","Gemology","Entomology","Detailed dissection"],
   noteworthy:"AmScope high-end Greenough stereo with an unusually wide 25:1 zoom ratio, providing the widest single-body zoom range in their stereo lineup. The 3.5x–90x range allows working from broad specimen overview to fine detail without changing objectives. Competes in functionality with the Nikon SMZ1270 range concept but at a fraction of the cost. Trinocular head standard on SZ-9T. Popular for electronics work where switching from board overview to component detail without refocusing is important.",
   oem_source:null},

  {id:"amscope-gm400",name:"GM400 Gemological Stereo",series:"GM",type:"stereo",subtype:"zoom stereo (Greenough, gemological)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$400–$900",price_used:"$120–$400",
   illumination:["LED incident oblique (top)","Transmitted brightfield and darkfield LED","Iris diaphragm","Variable intensity controls"],
   magnification:"7.5x–45x (6:1 zoom; 10x eyepieces); up to 90x with 20x eyepieces",
   objectives:"Greenough zoom body; gemological articulating stand; gem clamp",
   eyepieces:"WF 10x/20mm; binocular or trinocular; 45° incline",
   stage:"Gemological swivel articulating stand; transmitted brightfield/darkfield illumination; iris diaphragm for darkfield control; gem clamp included",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software",
   applications:["Gemology","Diamond grading","Jewelry appraisal","Watch repair","Stone inclusions"],
   noteworthy:"AmScope entry-level dedicated gemological stereo. The distinguishing feature is the brightfield/darkfield transmitted illumination stand with iris diaphragm, essential for viewing gem inclusions against a dark background. The articulating stand allows gem positioning for optimal illumination angles. Darkfield illumination reveals internal inclusions in diamonds and colored stones that brightfield cannot show. Trinocular version for camera documentation of gem characteristics. Most affordable dedicated gem stereo available; competes with Meiji GEM series at significantly lower price.",
   oem_source:null},

  {id:"amscope-h800",name:"H800 Digital Inspection System",series:"H800",type:"stereo",subtype:"digital inspection stereo (HDMI/USB output)",
   introduced:2015,discontinued:false,price_tier:"budget",
   price_new:"$300–$700",price_used:"$100–$300",
   illumination:["High-intensity LED ring (incident)","Variable intensity"],
   magnification:"3.5x–90x (zoom via camera software); 1080p HDMI and USB output",
   objectives:"Zoom lens integrated with digital sensor; no traditional eyepieces",
   eyepieces:"Digital display only (HDMI monitor output); no binocular eyetubes",
   stage:"Boom stand or post stand; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"AmScope software / HDMI direct to monitor",
   applications:["Electronics assembly","QC inspection","PCB rework","Production line inspection","Teaching display"],
   noteworthy:"The H800 is AmScope eyepiece-free digital inspection system — designed for production and QC environments where a monitor display is preferable to traditional eyepieces (no eye fatigue for operators doing 8-hour shifts, multiple people can view the same image simultaneously). HDMI output connects directly to any monitor. USB output for computer documentation. Not suitable for traditional microscopy where depth perception and direct optical viewing are required, but excellent for repetitive inspection tasks and group instruction.",
   oem_source:null}]
});
