// ════════════════════════════════════════════════════
// EUROMEX
// ════════════════════════════════════════════════════
DB.companies.push({id:"euromex",name:"Euromex Microscopen",shortName:"Euromex",flag:"🇳🇱",country:"Netherlands",
 founded:1966,status:"active",featured:false,hq:"Arnhem, Netherlands",
 categories:["compound","stereo"],
 overview:"Euromex Microscopen BV was founded in 1966 in Arnhem, Netherlands, and is one of Western Europe’s longest-established independent microscope companies. Unlike Asian OEM brands, Euromex occupies a genuine European mid-market position: they design and engineer their own optical systems (the EIS — Extended Infinity System — is proprietary), source components from qualified Asian manufacturers, and perform final assembly and quality control in the Netherlands. Their proximity to European customers provides service and warranty support that Asian-manufactured imports struggle to match. Euromex is particularly strong in continental European educational and clinical purchasing channels: the Netherlands, Belgium, Germany, France, and Scandinavia. Their bScope compound series (clinical/education), iScope (student), NexiusZoom Evo stereo, and PB polarizing series address the full scope of routine microscopy needs. Euromex also distributes the Oxion Inverso for tissue culture applications. The company remains privately owned and independent — not part of any major corporate group — which makes them one of the few genuinely independent European microscope manufacturers still operating.",
 oem:{acquiredBy:null,acquired:[],makesFor:[],madeBy:["Chinese and Taiwanese OEM manufacturers (assembled in Netherlands)"],notes:"Euromex assembles and quality-checks Asian OEM sources in the Netherlands before sale."},
 models:[
  {id:"euromex-iscope",name:"iScope",series:"iScope",type:"compound",subtype:"clinical / education",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$500–$950",price_used:"$100–$320",
   illumination:["LED"],magnification:"40x–1000x",objectives:"Achromat 4x/10x/40x/100x",
   eyepieces:"10x/18mm",stage:"Mechanical",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","Clinical routine","General biology"],
   noteworthy:"Popular in Dutch and Scandinavian schools. Good build quality for a budget scope with full LED illumination. Euromex provides strong European service and extended warranty support.",
   oem_source:null},
  {id:"euromex-nexius",name:"NexiusZoom Evo",series:"NexiusZoom",type:"stereo",subtype:"zoom stereo",
   introduced:2015,discontinued:false,price_tier:"mid",
   price_new:"$650–$1,300",price_used:"$150–$500",
   illumination:["LED ring + LED transmitted"],magnification:"6.7x–45x (10x eyepieces)",
   objectives:"Fixed",eyepieces:"10x/21mm",stage:"Large flat base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","QC inspection","Dissection","Natural history"],
   noteworthy:"Value stereo with good build quality. Popular in European university biology departments. Trinocular version supports documentation camera attachment.",
   oem_source:null}
,

  {id:"euromex-bscope",name:"bScope",series:"bScope",type:"compound",subtype:"routine / clinical upright (education / lab)",
   introduced:2014,discontinued:false,price_tier:"budget",
   price_new:"300-800 EUR",price_used:"100-400 EUR",
   illumination:["LED (standard)","Variable intensity; field iris (higher configs)"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Plan Achromat 4x/10x/40x/100x; DIN infinity-corrected; RMS thread.",
   eyepieces:"WF 10x/20mm or 10x/22mm; Siedentopf 30° binocular or trinocular; 48–75mm IPD",
   stage:"Rackless mechanical stage; Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"ScopeImage",
   applications:["Education","Clinical routine","Hematology","Veterinary","University teaching"],
   noteworthy:"Euromex’s most widely distributed routine compound microscope. Popular across European educational and clinical markets. Available in monocular, binocular, and trinocular configurations with achromat or plan achromat objectives. A solid mid-market European alternative to Motic BA310. Strong in European university and hospital purchasing programs.",
   oem_source:null},

  {id:"euromex-pb",name:"PB Polarizing Series",series:"PB",type:"compound",subtype:"polarizing compound (routine / petrographic)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"600-1500 EUR",price_used:"200-600 EUR",
   illumination:["LED transmitted","Polarizer below stage; analyzer above nosepiece"],
   magnification:"40x–1600x (4x–100x strain-free objectives, 10x eyepieces)",
   objectives:"Strain-free Plan Achromat 4x/10x/20x/40x/100x; DIN infinity; RMS thread",
   eyepieces:"WF 10x/22mm; binocular or trinocular Siedentopf",
   stage:"360° graduated rotating stage; Bertrand lens; lambda plate standard on higher models",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"ScopeImage",
   applications:["Mineralogy","Petrology","Geology","Pharmaceutical crystallography","Materials science"],
   noteworthy:"Euromex’s dedicated polarizing line. Graduated rotating stage, strain-free objectives, and Bertrand lens for conoscopic observation. Popular with European geology departments and pharmaceutical QC labs.",
   oem_source:null},

  {id:"euromex-oxion",name:"Oxion Inverso",series:"Oxion",type:"compound",subtype:"inverted routine / tissue culture",
   introduced:2016,discontinued:false,price_tier:"budget",
   price_new:"800-1800 EUR",price_used:"300-800 EUR",
   illumination:["LED transmitted sub-stage","Variable intensity"],
   magnification:"40x–400x (4x–40x LWD objectives, 10x eyepieces)",
   objectives:"EIS LWD Plan Achromat 4x/10x/20x/40x; DIN infinity; RMS thread",
   eyepieces:"WF 10x/20mm; 30° binocular or trinocular Siedentopf",
   stage:"Fixed stage; large central opening; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"ScopeImage",
   applications:["Tissue culture","Cell biology","IVF","Education","Microbiology"],
   noteworthy:"Euromex’s dedicated inverted tissue culture microscope. Phase contrast standard. LWD plan objectives for viewing through culture vessel bases. Popular in European teaching and small clinical labs as an affordable new inverted. Competes with the Motic AE31 and Zeiss Axiovert 25 in the European market on price.",
   oem_source:null}]});
