// ════════════════════════════════════════════════════
// LABOMED (LABO AMERICA)
// ════════════════════════════════════════════════════
DB.companies.push({id:"labomed",name:"Labo America / Labomed",shortName:"Labomed",flag:"🇺🇸",country:"USA (mfg. India)",
 founded:1982,status:"active",featured:false,hq:"Fremont, California, USA",
 categories:["compound","stereo"],
 overview:"Labo America, Inc. was founded in 1982 and is headquartered in Fremont, California (920 Auburn Court). The company designs, engineers, and distributes microscopes under the Labomed brand, with manufacturing carried out in ISO 9001:2015 and ISO 13485:2016 certified, FDA-registered facilities in India. Labomed occupies a distinctive mid-market position — above commodity OEM brands but well below the Big Four in price — and is particularly well regarded for its price-to-performance ratio in clinical, veterinary, educational, and research settings. A significant and often overlooked aspect of Labomed's history is their OEM manufacturing relationship with Leica Microsystems: Labomed has manufactured several of Leica's educational microscope models, including instruments comparable to the Leica CME, DME, and DM750. Labomed's proprietary MaxLite molecular sputtered coatings (anti-glare, anti-fungal, anti-scratch) and rechargeable LED battery systems are notable product differentiators. Their Prima series of surgical microscopes covers ENT, ophthalmology, dental, and gynecological surgical applications, and is widely used in both developed and developing-world healthcare settings.",
 oem:{acquiredBy:null,acquired:[],
  makesFor:["Leica Microsystems (OEM manufacturer for select educational models including CME, DME equivalents)"],
  madeBy:[],
  notes:"Labomed designs and manufactures instruments in India for distribution under the Labomed brand globally, and has produced OEM instruments sold under the Leica name. Their Lx300 is considered equivalent to the Leica DME; the Lx400 equivalent to the Leica DM750. Labo America is vertically integrated — one of the few remaining microscope companies that designs, tools, manufactures, and distributes entirely in-house."},
 models:[
  {id:"labomed-cxl",name:"CxL",series:"CxL",type:"compound",subtype:"clinical / education upright",
   introduced:2005,discontinued:false,price_tier:"budget",
   price_new:"$450–$750",price_used:"$100–$280",
   illumination:["LED (rechargeable)","Halogen 6V/20W"],
   magnification:"40x–1000x",
   objectives:"Semi-Plan Achromat 4x/10x/40x/100x (forward-facing nosepiece)",
   eyepieces:"10x/18mm, 45° inclined head, 360° rotatable",
   stage:"Plain stage with optional attachable mechanical stage",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Medical education","Clinical routine","Hematology","Urinalysis","K-12 biology"],
   noteworthy:"Entry-level Labomed clinical scope and their highest-volume product. The built-in rechargeable LED battery is a standout feature for field use and student labs without reliable power access. Comparable to the Leica CME in application and price tier. Available monocular or binocular. The forward-facing nosepiece is preferred by some clinical users. Widely used in veterinary clinics, medical schools, and biology classrooms across North America.",
   oem_source:null},
  {id:"labomed-lx300",name:"Lx300",series:"Lx",type:"compound",subtype:"pre-clinical / student upright",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$650–$1,050",price_used:"$150–$380",
   illumination:["LED (rechargeable)","Halogen 6V/20W"],
   magnification:"40x–1000x",
   objectives:"EP2 Plan Infinity Corrected 4x/10x/40x/100x",
   eyepieces:"10x/18mm; unique 'Butterfly' binocular head adjusts high/low position",
   stage:"Double-plate mechanical stage, reversed nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["University education","Pre-clinical labs","Biology education","Field microscopy"],
   noteworthy:"The Lx300's signature 'Butterfly' binocular head pivots between high and low positions for different seating heights — unique in this price range. Considered by multiple dealers to be equivalent to or better than the Leica DME. Infinity-corrected EP2 Plan objectives are a significant step up from the CxL. Built-in rechargeable battery. Good phase contrast option.",
   oem_source:null},
  {id:"labomed-lx400",name:"Lx400",series:"Lx",type:"compound",subtype:"research / clinical upright",
   introduced:2008,discontinued:false,price_tier:"mid",
   price_new:"$900–$1,400",price_used:"$220–$600",
   illumination:["LED (rechargeable)","Halogen 6V/20W or 6V/30W"],
   magnification:"40x–1000x",
   objectives:"RP Infinity Plan Achromat 4x/10x/40x/100x (reversed quadruple nosepiece)",
   eyepieces:"10x/20mm, 30° Siedentopf binocular or trinocular, 360° rotatable, IPD 48–75mm",
   stage:"Rackless double-plate mechanical stage, 76×40mm travel",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["University research","Clinical labs","Hematology","Fluorescence (EPI option)","Veterinary labs","Field research"],
   noteworthy:"The Lx400 is Labomed's flagship mid-range instrument and their most widely reviewed model. RP infinity-corrected Plan Achromat optics with MaxLite anti-fungal coatings. Binocular or trinocular head (30° Siedentopf) with wide 10x/20mm eyepieces. Multiple dealers describe it as equivalent to or better than the Leica DM750 at a significantly lower price. The rackless stage with scratch-resistant finish is a practical durability advantage. Fluorescence (EPI) configuration available.",
   oem_source:null},
  {id:"labomed-lx500",name:"Lx500",series:"Lx",type:"compound",subtype:"premium research upright",
   introduced:2012,discontinued:false,price_tier:"mid",
   price_new:"$1,400–$2,800",price_used:"$400–$1,100",
   illumination:["LED (rechargeable)","Halogen 6V/30W"],
   magnification:"40x–1000x (2.5x–1000x with optional 2.5x obj)",
   objectives:"RP2 Infinity Super Plan Achromat 4x/10x/40x/100x (reversed quintuple nosepiece, ball bearings)",
   eyepieces:"10x/22mm wide field; binocular, trinocular, or unique 0–25° ergonomic articulating head",
   stage:"Rackless ceramic-surface double-plate XY stage 200×160mm, 76×40mm travel",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research labs","Clinical pathology","Hematology","Fluorescence","Polarized light","Darkfield","Veterinary pathology"],
   noteworthy:"Labomed's top compound research platform. RP2 Super Plan optics with MaxLite molecular sputtered coatings (anti-glare, anti-fungal, anti-scratch) are a genuine differentiator. The optional 0–25° articulating ergonomic binocular head is rare in this price tier. True Köhler illumination with flip-top Abbe condenser (NA 1.25). Full modular expansion: EPI fluorescence, phase contrast, darkfield, polarized light, dual-training head. Ceramic-coated rackless stage resists scratching. Represents exceptional value versus the Big Four at equivalent specs.",
   oem_source:null},
  {id:"labomed-tcm400",name:"TCM400",series:"TCM",type:"compound",subtype:"inverted phase / fluorescence",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,500–$3,200",price_used:"$400–$1,200",
   illumination:["Halogen (transmitted)","50W HBO mercury (EPI fluorescence option)"],
   magnification:"40x–400x (with LWD objectives)",
   objectives:"LWD Phase Achromat 4x/10x/20x (long working distance, infinity corrected)",
   eyepieces:"10x/22mm; binocular or trinocular (with C-mount camera port)",
   stage:"Fixed stage standard; optional XY mechanical stage",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Cell culture QC","IVF / embryology","Tissue culture","Phase contrast live cell","Fluorescence cell biology","Veterinary reproduction"],
   noteworthy:"Labomed's inverted platform covering cell culture, IVF, and fluorescence. True-color infinity corrected optics with long working distance objectives for imaging cells in standard culture flasks and dishes. Trinocular with C-mount camera port. EPI fluorescence kit available for upgrade. Widely used in IVF clinics and veterinary reproduction labs as a cost-effective alternative to the Nikon Diaphot or Leica DM IL. Compact footprint for busy workstations.",
   oem_source:null},
  {id:"labomed-luxeo6z",name:"Luxeo 6Z",series:"Luxeo",type:"stereo",subtype:"zoom stereo",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$700–$1,400",price_used:"$180–$550",
   illumination:["LED ring (10-LED) + LED base glow screen","Adjustable angle of incidence ±30°"],
   magnification:"7x–45x (10x eyepieces, 6:1 zoom ratio)",
   objectives:"Fixed zoom body 0.7x–4.5x; optional 0.5x/2x auxiliary",
   eyepieces:"10x/20mm, 45° binocular or trinocular",
   stage:"Large base plate, black/white reversible stage",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Electronics","Jewelry","Gemology","Education","Natural history"],
   noteworthy:"Labomed's primary zoom stereo. The 10-LED ring illuminator with 3-LED transmitted base glow and ±30° adjustable angle of incidence gives versatile contrast options rarely found at this price. Available with boom stand, track stand, or plain stand. Trinocular version widely used for documentation. Good value alternative to Nikon SMZ745T or Zeiss Stemi 305 for non-fluorescence stereo work.",
   oem_source:null},
  {id:"labomed-prima-ent",name:"Prima ENT",series:"Prima",type:"compound",subtype:"surgical microscope (ENT)",
   introduced:2008,discontinued:false,price_tier:"premium",
   price_new:"$8,000–$22,000",price_used:"$2,000–$7,000",
   illumination:["LED (coaxial)","Halogen (optional)"],
   magnification:"5x–40x (zoom with apochromatic objectives)",
   objectives:"Apochromatic zoom optics, MaxLite coatings",
   eyepieces:"10x/22mm binocular (teaching assistant head optional)",
   stage:"Mobile floor stand with articulating arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:true,inverted:false,camera_port:true,
   software:"—",
   applications:["ENT surgery (otolaryngology)","Ear tube placement","Sinus surgery","Laryngoscopy","Clinical ENT examination"],
   noteworthy:"Labomed's Prima ENT surgical microscope is widely used in ENT surgical suites and clinics globally, particularly in cost-conscious healthcare systems. Apochromatic optics with MaxLite coatings, motorized zoom, mobile floor stand. Optional teaching assistant head for training. FDA-cleared. Available in over 200 countries. Used in charitable hospitals in developing nations. Significantly more affordable than Zeiss or Leica surgical microscopes at equivalent optical quality.",
   oem_source:null}
 ,

  {id:"labomed-luxeo2s",name:"Luxeo 2S",series:"Luxeo",type:"stereo",subtype:"step-zoom stereo (Greenough, educational)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$300–$600",price_used:"$100–$300",
   illumination:["LED incident (top)","LED transmitted (bottom, simultaneous or independent)","Variable intensity; 5-position illumination selector"],
   magnification:"10x and 30x (2-position lever switch); fixed step, no continuous zoom",
   objectives:"Greenough fixed 2-step objectives; sealed body",
   eyepieces:"WF 10x/20mm; binocular; 45° incline; 52–74mm IPD",
   stage:"Integrated flat base with black/white reversible plate; stage clips",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["K–12 education","Basic dissection","Introductory biology","Home science"],
   noteworthy:"Labomed entry stereo for education. The 2S designation indicates 2-step (2-position) magnification — a large side-mounted knob switches between 10x and 30x. Simpler and more durable than continuous zoom mechanisms for classroom use. LED dual illumination (incident + transmitted) with 5-setting selector: top only, bottom only, top + bottom at two intensity levels, and off. Single-cast body for durability. Anti-fungal coating. A direct competitor to the Swift SM105 and Motic SMZ-140 in the educational stereo market.",
   oem_source:null},

  {id:"labomed-luxeo4",name:"Luxeo 4Z / Luxeo 4D",series:"Luxeo",type:"stereo",subtype:"zoom stereo (Greenough, mid-tier)",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$400–$900",price_used:"$150–$400",
   illumination:["LED incident with Red Cone ring light (incident)","LED transmitted (base)","Multiple illumination angle presets (front/rear oblique, full)","Variable intensity"],
   magnification:"8x–35x (4.4:1 zoom; 10x/20mm eyepieces); up to 70x with 20x eyepieces",
   objectives:"Greenough 0.8x–3.5x zoom; 0.5x/2x auxiliary objectives compatible; 110mm WD",
   eyepieces:"SWF 10x/20mm super widefield; binocular (Luxeo 4Z) or integrated digital camera (Luxeo 4D); 52–74mm IPD",
   stage:"Integrated base with incident + transmitted LED; black/white reversible stage plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Labomed camera software (4D)",
   applications:["Biological education","QC inspection","Electronics","Entomology","Botany","Natural history"],
   noteworthy:"Labomed mid-tier zoom stereo family. Luxeo 4Z: conventional binocular with integrated LED illumination in a distinctive Red Cone ring light design providing oblique, direct incident, and transmitted illumination in multiple presets via selector switch. Luxeo 4D: identical optical body but with integrated 5MP digital camera replacing one eyetube — one-piece digital stereo solution without a separate camera adapter. Both feature single-cast body, anti-fungal coating, and 4.4:1 zoom ratio (8x–35x). The Luxeo 6Z (already in database) is the higher-tier model in the same family with 6.4:1 zoom.",
   oem_source:null},

  {id:"labomed-csm",name:"CSM2 / CSM3 / CSM4 Common Main Objective (CMO) Series",series:"CSM",type:"stereo",subtype:"research zoom stereo (CMO, infinity optical)",
   introduced:2008,discontinued:false,price_tier:"mid",
   price_new:"$1,500–3,500",price_used:"$400–1,200",
   illumination:["Halogen or LED incident + transmitted (stand-dependent)","Variable intensity; optional fluorescence attachment"],
   magnification:"CSM2: 8x–56x (7:1 zoom); CSM3: 10x–70x; CSM4: 6.4x–45x (different body); 10x eyepieces",
   objectives:"CMO (Common Main Objective) infinity optical system; 1.0x standard; 0.5x/0.75x/1.5x/2x interchangeable objectives; parfocal throughout",
   eyepieces:"SWF 10x/23mm widefield; binocular or trinocular; 54–75mm IPD; ergonomic head options",
   stage:"Multiple stand options; 76mm neck; compatible with brightfield/darkfield bases",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Labomed camera software",
   applications:["Research","Biomedical","Electronics","Industrial QC","Gemology","Neuroscience","Cell biology"],
   noteworthy:"Labomed CMO (Common Main Objective) professional stereo series, competing directly with the Nikon SMZ-U and Meiji RZ series. The CMO infinity optical system provides parallel light paths (vs. Greenough angled paths) resulting in superior image flatness and the ability to insert accessories (filters, polarizers, reticles) between objective and head without affecting focus. CSM2: 7:1 zoom body. CSM3: similar range with ergonomic head option. CSM4: lower ratio, suited for precise measurement applications. All feature anti-static finish, anti-fungal coating, and accept the full Labomed stereo accessory range.",
   oem_source:null},

  {id:"labomed-met400",name:"MET 400 Stereo Metallurgical",series:"MET",type:"stereo",subtype:"zoom stereo with reflected light (metallurgical)",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,200–2,500",price_used:"$400–1,000",
   illumination:["Coaxial (vertical) reflected LED illumination","Optional incident oblique LED","Optional transmitted LED base"],
   magnification:"8x–56x (7:1 zoom; 10x eyepieces); up to 112x with 20x eyepieces",
   objectives:"Greenough or CMO zoom body with coaxial illumination module; 76mm neck",
   eyepieces:"SWF 10x/23mm; binocular or trinocular; 54–75mm IPD",
   stage:"Mechanical stage; coaxial illumination column; optional transmitted base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Labomed camera software",
   applications:["Metallurgy","PCB inspection","Semiconductor","Mineralogy","Surface QC","Failure analysis"],
   noteworthy:"Labomed reflected light stereo for metallurgical and industrial surface inspection. Coaxial illumination directs light vertically through the optics onto the specimen surface — essential for highly reflective surfaces where angled gooseneck illuminators create glare and uneven illumination. Anti-static finish standard. Compatible with Labomed stereo accessory range. Direct competitor to Meiji EMX-1 at similar price point.",
   oem_source:null},

  {id:"labomed-prima",name:"Prima GN / Prima Pro Educational Stereo",series:"Prima",type:"stereo",subtype:"zoom stereo (Greenough, educational/professional)",
   introduced:2015,discontinued:false,price_tier:"budget",
   price_new:"$400–$900",price_used:"$150–$450",
   illumination:["LED incident + transmitted","Variable intensity; illumination selector"],
   magnification:"Prima GN: 7.5x–45x (6:1 zoom; 10x eyepieces); Prima Pro: 8x–50x (6.3:1 zoom)",
   objectives:"Greenough zoom body; 0.5x/2x auxiliary objectives compatible; 110mm WD",
   eyepieces:"SWF 10x/20mm or 10x/23mm; binocular or trinocular (Pro); 52–74mm IPD",
   stage:"Integrated base with incident + transmitted illumination; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Labomed camera software",
   applications:["Education","University teaching","Biological dissection","Routine inspection","Natural history"],
   noteworthy:"Labomed educational and entry-professional stereo tier. Prima GN (General Nature): binocular, 6:1 zoom, designed for K–12 and introductory university biology. Prima Pro: trinocular, 6.3:1 zoom, adds camera port for documentation. Both feature Labomed anti-fungal coating, single-cast body, and LED dual illumination. The Prima line sits between the entry Luxeo 2S and the full Luxeo 4Z/6Z in the Labomed stereo hierarchy. Good balance of optical quality and durability for educational purchase programs.",
   oem_source:null},

  {id:"labomed-sigma",name:"Sigma / StarLine Stereo Series",series:"Sigma/StarLine",type:"stereo",subtype:"zoom stereo (Greenough, specialty/OEM)",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$350–$800",price_used:"$100–$350",
   illumination:["LED incident + transmitted","Variable intensity"],
   magnification:"7x–45x (6.4:1 zoom) or 8x–35x (4.4:1 zoom) depending on configuration",
   objectives:"Greenough zoom body; 0.5x/2x auxiliary objectives compatible",
   eyepieces:"WF 10x/20mm; binocular or trinocular; 45° incline",
   stage:"Post stand or flat base; black/white reversible plate; 76mm neck",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Labomed camera software",
   applications:["Education","Routine inspection","Dissection","Clinical basics"],
   noteworthy:"Labomed Sigma and StarLine are value-oriented stereo lines used for educational bulk purchasing and OEM supply. The Sigma provides a lower cost entry point into Labomed stereos than the Luxeo line. The StarLine is similar in optical specification to the Sigma but with updated aesthetics and minor ergonomic improvements. Both lines are often found in university teaching labs and supplied under institutional purchasing contracts. Anti-fungal coating standard. Compatible with standard Labomed stereo accessories.",
   oem_source:null}]
});
