// ════════════════════════════════════════════════════
// BIG FOUR — LEICA
// ════════════════════════════════════════════════════
DB.companies.push({id:"leica",name:"Leica Microsystems",shortName:"Leica",flag:"🇩🇪",country:"Germany",
 founded:1849,status:"active",featured:true,hq:"Wetzlar, Germany",
 categories:["compound","stereo"],
 overview:"Leica Microsystems is the product of one of the most consequential corporate consolidations in scientific instrument history, uniting four historically distinguished lines. (1) Ernst Leitz Wetzlar (founded 1849 by Carl Kellner): pioneers of oil-immersion objectives (1878), apochromatic objectives, the Ploemopak epi-fluorescence system (1965) — the first practical upright epi-fluorescence setup — and origin of the Leica 35mm camera (designed by Oskar Barnack, 1914; first sold 1925). (2) Wild Heerbrugg (1921, Switzerland): makers of the finest CMO stereo microscopes ever built — the M3, M5, M7, M8, M10, M20 compound, M40 inverted — whose reputation for Swiss mechanical precision remains unmatched. (3) Cambridge Instruments (UK): contributed electron microscopy and quantitative image analysis heritage, including the Quantimet image analyser (1963) — the world’s first commercial image analysis system. (4) Reichert-Jung (Vienna, 1847): cryostats, ultramicrotomes (Om-U), and the Polyvar research upright. The Wild-Leitz merger occurred in 1986; Cambridge Instruments and Reichert-Jung joined in 1990 to form the Leica Group; the name Leica Microsystems was formally adopted in 1997. Bausch & Lomb’s Stereozoom microscope line (the CMO template for all modern stereos) was acquired in 1991. Leica Microsystems was acquired by Danaher Corporation in September 2005 and operates today as an independent Danaher subsidiary. Current flagship products include the DMi8 inverted, DM6 B upright, M205 stereo, Mica multimode confocal, and the LIGHTNING deconvolution platform.",
 oem:{acquiredBy:"Danaher Corporation (2011)",acquired:["Wild Heerbrugg AG (1990)","Ernst Leitz Wetzlar (1986 founding)","Reichert-Jung (1990)","Bausch & Lomb Stereozoom line (~1990)"],makesFor:[],madeBy:["Labomed / Labo America (OEM manufacturer for select educational models)"],notes:"Leica Camera AG is an entirely separate company from Leica Microsystems. Labomed has manufactured OEM educational instruments for Leica including CME and DME equivalents."},
 models:[
  // ── CURRENT ──
  {id:"leica-dm750",name:"DM750",series:"DM",type:"compound",subtype:"clinical upright",
   introduced:2011,discontinued:false,price_tier:"budget",
   price_new:"$1,500–$2,800",price_used:"$400–$900",
   illumination:["LED"],magnification:"40x–1000x",objectives:"HI Plan achromat 4x/10x/40x/100x",
   eyepieces:"10x/18mm",stage:"Mechanical 76×30mm",fluorescence:false,phase_contrast:true,
   darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,software:"LAS EZ",
   applications:["Medical education","Clinical routine","Urinalysis","Hematology"],
   noteworthy:"Ergonomic slim-pillar design with ICC50 camera integration and full LED illumination. Widely adopted in clinical and university teaching labs across Europe and North America.",
   oem_source:null},
  {id:"leica-dmi8",name:"DMi8",series:"DMi",type:"compound",subtype:"inverted modular",
   introduced:2015,discontinued:false,price_tier:"premium",
   price_new:"$25,000–$65,000",price_used:"$6,000–$20,000",
   illumination:["LED (EL6000/CorrLight)","Laser add-on"],magnification:"25x–1000x",
   objectives:"HC PL FLUOTAR / HC PL APO series",eyepieces:"10x/22mm",
   stage:"Motorized 150×100mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"LAS X",
   applications:["Live cell biology","Timelapse imaging","TIRF","High-content screening"],
   noteworthy:"Industry-leading modular 'snap-in' platform. Accepts widefield, TIRF, confocal, light sheet, and super-resolution modules on a single stand without optical compromise.",
   oem_source:null},
  {id:"leica-thunder",name:"THUNDER Imager",series:"THUNDER",type:"compound",subtype:"widefield + computational clearing",
   introduced:2018,discontinued:false,price_tier:"premium",
   price_new:"$25,000–$60,000",price_used:"$8,000–$22,000",
   illumination:["LED (EL6000)"],magnification:"50x–1000x",
   objectives:"HC PL APO series",eyepieces:"10x/22mm",
   stage:"Motorized",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:false,camera_port:true,software:"LAS X with THUNDER GDQ algorithm",
   applications:["3D tissues","Organoids","Embryos","Model organisms","Live 3D imaging"],
   noteworthy:"Uses Computational Clearing (GDQ) to remove out-of-focus haze in real time, delivering confocal-like image quality from a widefield instrument at much higher speed.",
   oem_source:null},
  {id:"leica-m205fa",name:"M205 FA",series:"M",type:"stereo",subtype:"fluorescence stereo / macroscope",
   introduced:2010,discontinued:false,price_tier:"ultra",
   price_new:"$50,000–$120,000",price_used:"$15,000–$42,000",
   illumination:["LED (reflected + transmitted)","EL6000 fluorescence module"],
   magnification:"7.8x–160x (10x ep, 1x PlanAPO; 1280x max with full optics)",
   objectives:"0.5x/0.63x/0.8x/1.0x/1.6x/2.0x planapochromat",eyepieces:"10x/23mm",
   stage:"Large format 210×210mm",fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:true,inverted:false,camera_port:true,software:"LAS X",
   applications:["Developmental biology","Zebrafish","Drosophila","Neuroscience","Fluorescence screening"],
   noteworthy:"20.5:1 zoom ratio — the world's first fluorescence stereo at this zoom range. FusionOptics uses separate channels for high resolution (right eye) and high depth of field (left eye). TripleBeam fluorescence eliminates background noise via a dedicated third beam path.",
   oem_source:null},
  {id:"leica-s9e",name:"S9 E",series:"S",type:"stereo",subtype:"entry zoom stereo",
   introduced:2011,discontinued:false,price_tier:"budget",
   price_new:"$1,200–$2,500",price_used:"$400–$900",
   illumination:["LED ring + LED transmitted"],magnification:"6.7x–45x (10x eyepieces)",
   objectives:"Fixed (Greenough system)",eyepieces:"10x/21mm",
   stage:"Foam / universal stage",fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["QC inspection","Dissection","Electronics","Natural history"],
   noteworthy:"Greenough optical system with excellent ergonomics and robust Leica build quality. Great value for non-fluorescence stereo work. Widely used in European industrial and educational settings.",
   oem_source:null},
  // ── HISTORICAL / COLLECTIBLE ──
  {id:"leica-dmls",name:"DMLS",series:"DM",type:"compound",subtype:"clinical/lab upright",
   introduced:1991,discontinued:2003,price_tier:"budget",
   price_new:null,price_used:"$250–$750",
   illumination:["Halogen 12V/100W"],magnification:"40x–1000x",
   objectives:"N Plan achromat / HI Plan achromat",eyepieces:"10x/18mm",
   stage:"Mechanical",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical labs","Medical education","Hematology","Urinalysis"],
   noteworthy:"Leica's entry-level clinical scope of the 1990s. Widely sold to hospitals, clinics, and universities across Europe. Excellent Leica build quality at a budget price point. Parts still available. Ideal second-hand scope for routine clinical work.",
   oem_source:null},
  {id:"leica-dmlb",name:"DMLB",series:"DM",type:"compound",subtype:"research upright",
   introduced:1993,discontinued:2003,price_tier:"mid",
   price_new:null,price_used:"$600–$1,900",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence"],
   magnification:"50x–1000x",objectives:"HC PL Fluotar / N Plan Achromat",eyepieces:"10x/22mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Histology","Fluorescence","Multi-contrast","Clinical pathology"],
   noteworthy:"The DMLB was Leica's primary research brightfield/fluorescence upright of the 1990s. The HC PL Fluotar objectives provide excellent fluorescence throughput. Very widely used in European research institutions. Affordable entry into high-quality Leica optics on the used market.",
   oem_source:null},
  {id:"leica-dmrb",name:"DMRB",series:"DM",type:"compound",subtype:"research upright (multi-contrast)",
   introduced:1993,discontinued:2003,price_tier:"mid",
   price_new:null,price_used:"$700–$2,500",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence"],
   magnification:"50x–1000x",objectives:"HC PL Fluotar / HC PL APO",eyepieces:"10x/22mm",
   stage:"Mechanical large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","DIC imaging","Fluorescence","Materials","Neuroanatomy"],
   noteworthy:"The DMRB ('Research Brightfield') added full DIC capability over the DMLB. Excellent for demanding research applications. The Normarsky DIC system in these instruments is still considered outstanding. Widely used and well-supported on the second-hand market.",
   oem_source:null},
  {id:"leica-dmirb",name:"DMIRB / DM IRB",series:"DMI",type:"compound",subtype:"inverted research (fluorescence, mid-1990s)",
   introduced:1993,discontinued:2003,price_tier:"mid",price_new:null,price_used:"$500–$3,000",
   illumination:["12V/100W halogen transmitted","100W mercury epi-fluorescence (standard)","5-position fluorescence cube turret"],
   magnification:"20x–1000x; 22mm field number",
   objectives:"Leica ICS infinity-corrected, 200mm tube lens, M25 thread. HCX series: HCX PL Fluotar, HCX Plan-Apochromat LWD. NOT compatible with older Leitz finite objectives.",
   eyepieces:"L 10x/22mm (23.2mm tube); binocular or trinocular",
   stage:"Full mechanical XY stage; large specimen opening",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,motorized:false,inverted:true,camera_port:true,software:"IM50 / FW4000 (era-appropriate)",
   applications:["Cell biology","Fluorescence","FRET","Live cell imaging","DIC","Confocal coupling"],
   noteworthy:"Leica’s mid-range research inverted fluorescence of the 1990s. Extremely common in cell biology department surplus worldwide. Uses Leica’s ICS optical system (200mm tube lens, M25 thread) — NOT compatible with older Leitz 160mm or 170mm objectives. The DMIRBE adds an ergonomic tilting head. Common failure: fluorescence cube turret click-stop detent wear.",
   oem_source:null},

{id:"leica-dmire2",name:"DMIRE2",series:"DMI",type:"compound",subtype:"inverted research",
   introduced:2001,discontinued:2010,price_tier:"premium",
   price_new:null,price_used:"$2,500–$7,000",
   illumination:["Halogen","HBO 100W fluorescence","Metal halide option"],
   magnification:"25x–1000x",objectives:"HC PL Fluotar / HC PL APO LD (long working distance)",
   eyepieces:"10x/22mm",stage:"Motorized 130×100mm (optional)",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"LAS AF (early)",
   applications:["Live cell","Cell culture","Timelapse","Fluorescence","FRET (early)"],
   noteworthy:"The DMIRE2 was Leica's high-end inverted platform of the early 2000s — predecessor to the DMi8. Motorized version supports multi-position timelapse. Still used in many labs and available at excellent value on the used market. Good base for spinning disk or TIRF upgrades.",
   oem_source:null},
  {id:"leica-dm-il",name:"DM IL",series:"DMI",type:"compound",subtype:"inverted routine",
   introduced:1990,discontinued:2005,price_tier:"budget",
   price_new:null,price_used:"$250–$700",
   illumination:["Halogen 6V/20W"],magnification:"40x–400x",
   objectives:"N Plan LWD achromat 4x/10x/20x/40x",eyepieces:"10x/18mm",
   stage:"Mechanical 190×160mm",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell culture QC","Tissue culture","Basic cell biology","Clinical cell examination"],
   noteworthy:"Leica's entry inverted for routine cell culture examination. Used in virtually every cell biology lab and biotech company of the 1990s–2000s. Extremely durable. LWD phase objectives for viewing cells in culture flasks. Very affordable and widely available used.",
   oem_source:null},
  {id:"leica-mz9",name:"MZ9.5",series:"MZ",type:"stereo",subtype:"research zoom stereo",
   introduced:1994,discontinued:2008,price_tier:"mid",
   price_new:null,price_used:"$800–$2,600",
   illumination:["Halogen (external)","Fluorescence option"],
   magnification:"6.3x–80x (with standard objectives)",
   objectives:"0.63x/1.0x/1.6x/2.0x planapochromat",eyepieces:"10x/21mm",
   stage:"Large format",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Model organisms","Fluorescence screening","QC"],
   noteworthy:"The MZ9.5 was the mid-range research stereo in Leica's MZ series — direct descendant of the Bausch & Lomb Stereozoom design. 9.5:1 zoom ratio with planapochromatic optics. Fluorescence-capable. Excellent second-hand value for labs needing a quality research stereo.",
   oem_source:null},
  {id:"leica-mz125",name:"MZ12.5",series:"MZ",type:"stereo",subtype:"research zoom stereo",
   introduced:1997,discontinued:2010,price_tier:"premium",
   price_new:null,price_used:"$1,200–$4,000",
   illumination:["Halogen (external)","Fluorescence module"],
   magnification:"7.9x–100x (with standard objectives)",
   objectives:"0.63x/1.0x/1.6x/2.0x planapochromat",eyepieces:"10x/21mm",
   stage:"Large format 210×160mm",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Fluorescence screening","Dissection","Model organisms"],
   noteworthy:"12.5:1 zoom ratio. The MZ12.5 was the top practical stereo in the MZ line before the M205 era. Widely used in developmental biology labs. Full fluorescence capability. Excellent optical quality and available with a wide range of accessories. Strong second-hand demand.",
   oem_source:null},
  {id:"leica-mz16",name:"MZ16",series:"MZ",type:"stereo",subtype:"research zoom stereo (fluorescence)",
   introduced:2001,discontinued:2010,price_tier:"premium",
   price_new:null,price_used:"$2,000–$6,500",
   illumination:["Halogen (external)","EL6000 fluorescence"],
   magnification:"7.1x–115x (standard; up to 230x with 2x obj)",
   objectives:"0.5x/0.63x/1.0x/1.6x/2.0x planapochromat",eyepieces:"10x/23mm",
   stage:"Large format",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Zebrafish","Drosophila","Fluorescence screening","Neuroscience"],
   noteworthy:"16:1 zoom ratio. The MZ16 was Leica's top-of-the-line stereo before the M205 FA and is the immediate predecessor. Full fluorescence with EL6000 illuminator. Outstanding apochromatic optics. Still used in active research labs and available at excellent value given its capabilities.",
   oem_source:null},

{id:"leica-dialux20",name:"Leitz Dialux 20",series:"Dialux",type:"compound",subtype:"research upright (Leitz era)",
   introduced:1978,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$750",
   illumination:["Halogen 12V/100W","HBO 50/100W fluorescence"],
   magnification:"25x–1000x (2.5x–100x objectives, 10x eyepieces)",
   objectives:"NPL Fluotar / Plan Achromat (160mm, Leitz thread)",
   eyepieces:"10x/22mm; binocular 30°; trinocular available",stage:"Mechanical 145x105mm",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","DIC","Neuroscience","Histology"],
   noteworthy:"Leitz Wetzlar's primary research upright of the late 1970s–80s. Excellent NPL Fluotar objectives widely praised for fluorescence performance. DIC (Nomarski) available. Extremely robust German construction. Widely distributed in European research institutions; still functional and actively used today.",
   oem_source:null},

  {id:"leica-laborlux12",name:"Leitz Laborlux 12",series:"Laborlux",type:"compound",subtype:"clinical / lab upright (Leitz era)",
   introduced:1982,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$700",
   illumination:["Halogen 12V/100W"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"NPL Achromat / NPL Fluotar (160mm, Leitz thread)",
   eyepieces:"10x/18mm; binocular 30°",stage:"Mechanical",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Clinical pathology","Hematology","Research","Histology","Education"],
   noteworthy:"Leitz's mid-tier research/clinical upright of the early 1980s. Simpler than the Dialux 20 but using the same Leitz NPL optical system. Very durable — many remain in daily use. The white body is characteristic of 1980s Leitz instruments.",
   oem_source:null},

  {id:"leica-dm-e",name:"DM E",series:"DM",type:"compound",subtype:"education / routine upright",
   introduced:1994,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$150–$500",
   illumination:["Halogen 6V/15W"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"HI Plan Achromat (infinity corrected)",
   eyepieces:"10x/18mm; binocular 30°",stage:"Mechanical",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Medical education","Clinical routine","Hematology","Basic biology"],
   noteworthy:"Leica's entry education/clinical microscope of the 1990s–2000s. Compact, simple, and extremely durable. Widely sold to European medical schools and hospitals. One of the most common Leica instruments on the second-hand market. The CxL-equivalent in the Leica lineup, often compared to the Nikon E200 and Zeiss Axiolab.",
   oem_source:null},

  {id:"leica-dm500",name:"DM500 / DM300",series:"DM",type:"compound",subtype:"education / clinical upright",
   introduced:2009,discontinued:false,price_tier:"budget",
   price_new:"$900–$2,000",price_used:"$200–$700",
   illumination:["LED"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"HI Plan Achromat (infinity corrected)",
   eyepieces:"10x/18mm; binocular 30°",stage:"Mechanical",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS EZ",
   applications:["Medical education","Clinical routine","Hematology","Urinalysis"],
   noteworthy:"Replaced the DM E as Leica's entry education/clinical scope. Pre-centred, pre-focussed condenser for quick beginner setup. Full LED. The ICC50 W wireless camera integrates without a trinocular head. Particularly popular in veterinary medicine and dental schools.",
   oem_source:null},

  {id:"leica-dm1000",name:"DM1000",series:"DM",type:"compound",subtype:"clinical research upright",
   introduced:2004,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$500–$2,000",
   illumination:["Halogen 12V/100W","HBO 50W fluorescence"],
   magnification:"40x–1000x (4x–100x HC PL objectives, 10x/20mm eyepieces)",
   objectives:"HC PL Fluotar / HI Plan (infinity corrected, M25 thread)",
   eyepieces:"10x/20mm; binocular 0–35°; trinocular available",stage:"Rackless mechanical stage",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS EZ",
   applications:["Clinical pathology","Cytology","Hematology","Histology","Education"],
   noteworthy:"The smallest member of Leica's DM1000–3000 series. Succeeded the DMLS. Adjustable 0–35° head for ergonomics. Rackless stage for safety. Phase contrast and fluorescence available. Height-adjustable focus knobs. Widely used in European clinical and teaching labs through the 2010s.",
   oem_source:null},

  {id:"leica-dm2000",name:"DM2000",series:"DM",type:"compound",subtype:"research upright",
   introduced:2004,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$700–$2,800",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence"],
   magnification:"40x–1000x (4x–100x HC PL objectives, 10x/22mm eyepieces)",
   objectives:"HC PL Fluotar / HC PL APO (infinity corrected)",
   eyepieces:"10x/22mm; binocular 0–35°; trinocular available",stage:"Mechanical; optional motorized",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS",
   applications:["Research","Clinical pathology","Cytology","Hematology","Multi-contrast imaging"],
   noteworthy:"Designed for complex routine pathology and cytology. More capable than the DM1000 — accepts a wider range of contrast methods and the full HC PL objective range. Adjustable 0–35° head. The standard Leica research/clinical upright of the mid-2000s to mid-2010s.",
   oem_source:null},

  {id:"leica-dm2500",name:"DM2500",series:"DM",type:"compound",subtype:"research upright (DIC)",
   introduced:2004,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$1,000–$4,000",
   illumination:["Halogen 100W","LED option","HBO 100W fluorescence"],
   magnification:"40x–1000x (4x–100x HC PL objectives, 10x/22mm eyepieces)",
   objectives:"HC PL APO / HC PL Fluotar (infinity corrected, M25 thread)",
   eyepieces:"10x/22mm; binocular 0–35°; trinocular",stage:"Mechanical 130x90mm; optional motorized",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS",
   applications:["Research","DIC imaging","Fluorescence","Neuroscience","Materials science","Pathology"],
   noteworthy:"Particularly suited for pathology and research requiring DIC. Full Nomarski DIC with HC PL APO objectives. Available with LED illumination. Five fluorescence filter cube positions. One of the most capable Leica research uprights of the 2000s–2010s era.",
   oem_source:null},

  {id:"leica-dm4000",name:"DM4000 B",series:"DM",type:"compound",subtype:"motorized research upright",
   introduced:2007,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$2,000–$7,000",
   illumination:["Halogen 100W","HBO 100W fluorescence","Metal halide option"],
   magnification:"40x–1000x (4x–100x HC PL objectives, 10x/22mm eyepieces)",
   objectives:"HC PL APO / HC PL Fluotar (infinity corrected)",
   eyepieces:"10x/22mm; binocular 0–35°; trinocular",stage:"Motorized encoded 130x90mm",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"LAS AF",
   applications:["Research","Automated multi-position imaging","Fluorescence","Whole slide scanning","Neuroscience"],
   noteworthy:"Leica's motorized research upright of the late 2000s. Motorized stage with encoding for multi-position tiling. Supports automated fluorescence imaging sequences. Widely used in core imaging facilities.",
   oem_source:null},

  {id:"leica-dm6000",name:"DM6000 B",series:"DM",type:"compound",subtype:"automated research upright (flagship)",
   introduced:2007,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$4,000–$15,000",
   illumination:["Halogen 100W","Metal halide","EL6000 fiber-coupled fluorescence"],
   magnification:"40x–1000x (4x–100x HC PL objectives, 10x/22mm eyepieces)",
   objectives:"HC PL APO / HC PL Fluotar (infinity, M25 thread)",
   eyepieces:"10x/22mm; binocular 0–35°; trinocular",stage:"Motorized encoded 130x90mm + piezo Z",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"LAS AF Automation",
   applications:["High-content imaging","Whole slide scanning","Multi-position timelapse","Fluorescence","Digital pathology"],
   noteworthy:"The flagship automated upright from Leica for a decade. Fully motorized with encoded stage and z-drive. Supports multi-position, Z-stack, timelapse, and tile-scan automation. Precursor to the THUNDER Imager. Still found in core imaging facilities worldwide.",
   oem_source:null},

  {id:"leica-dmi1",name:"DMi1",series:"DMi",type:"compound",subtype:"inverted routine",
   introduced:2015,discontinued:false,price_tier:"mid",
   price_new:"$2,500–$6,000",price_used:"$600–$2,200",
   illumination:["LED (transmitted)"],
   magnification:"40x–400x (4x–40x LWD objectives, 10x/20mm eyepieces)",
   objectives:"HI Plan LWD Achromat (4x/10x/20x/40x, infinity corrected)",
   eyepieces:"10x/20mm; binocular 30°",stage:"Mechanical 195x135mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"LAS EZ",
   applications:["Cell culture QC","Tissue culture","IVF","Basic cell biology","Clinical cytology"],
   noteworthy:"Replaced the aging DM IL LED as Leica's entry inverted scope. Modern LED illumination. Simple ergonomic design for routine cell culture observation. Pre-focussed phase contrast kit available. Widely used in IVF clinics and cell biology labs.",
   oem_source:null},

  {id:"leica-mz6",name:"MZ6",series:"MZ",type:"stereo",subtype:"entry research stereo",
   introduced:1996,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$400–$1,300",
   illumination:["Halogen (external ring + transmitted)"],
   magnification:"6.3x–40x (10x eyepieces, 1x objective; 6.3:1 zoom)",
   objectives:"Fixed zoom body 0.63x–4.0x; 0.5x/1.0x/1.6x auxiliary",
   eyepieces:"10x/21mm",stage:"Large flat base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Education","Natural history","Electronics"],
   noteworthy:"Leica's entry stereo zoom in the MZ series — direct descendant of the Bausch & Lomb Stereozoom / Wild design lineage. 6.3:1 zoom ratio. Good optics for the price. Widely adopted in European biology departments and industrial labs. MZ6 accessories interchangeable with MZ7.5 and MZ9.5.",
   oem_source:null},

  {id:"leica-mz75",name:"MZ7.5",series:"MZ",type:"stereo",subtype:"student research stereo",
   introduced:1996,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$500–$1,600",
   illumination:["Halogen (ring + transmitted base)"],
   magnification:"7.5x–50x (10x eyepieces, 1x objective; 6.7:1 zoom)",
   objectives:"Fixed zoom body 0.75x–5.0x; 0.5x/1.0x/2.0x auxiliary",
   eyepieces:"10x/21mm",stage:"Large flat base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","Natural history","Education","QC","Electronics"],
   noteworthy:"Positioned between the MZ6 and MZ9.5. 6.7:1 zoom ratio. Solid ergonomics and typical Leica build quality. Accessories interchangeable across the MZ series. Commonly found in US and European university biology teaching labs.",
   oem_source:null},

  {id:"leica-mz10f",name:"MZ10F",series:"MZ",type:"stereo",subtype:"fluorescence stereo",
   introduced:2003,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,000–$3,800",
   illumination:["Halogen (ring + transmitted)","HBO 100W fluorescence"],
   magnification:"7x–90x (10x eyepieces, 1x obj; up to 180x with 2x obj; 10:1 zoom)",
   objectives:"0.5x/0.63x/1.0x/1.6x/2.0x planapochromat",
   eyepieces:"10x/21mm",stage:"Large format",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS (early)",
   applications:["Developmental biology","GFP/RFP screening","Model organisms","Fluorescence dissection"],
   noteworthy:"Brought fluorescence capability to the MZ series at a more accessible price point than the MZ16. 10:1 zoom with planapochromatic objectives. HBO fluorescence for GFP, RFP, and multi-channel work. Widely used in developmental biology labs screening transgenic model organisms.",
   oem_source:null},

  {id:"leica-m60",name:"M60",series:"M",type:"stereo",subtype:"research stereo",
   introduced:2008,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,500–$5,500",
   illumination:["LED (coaxial + ring)","Optional fluorescence"],
   magnification:"7.5x–120x (10x eyepieces, 1x PlanApo; extended range with objectives)",
   objectives:"0.5x/0.63x/1.0x/1.6x/2.0x PlanApo (M-series mount)",
   eyepieces:"10x/21mm; binocular and trinocular",stage:"Large format; various stands",
   fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS",
   applications:["Developmental biology","Research","Neuroscience","Fluorescence screening","Quality control"],
   noteworthy:"Leica's consolidation of the MZ series heritage into the modular M-series design. PlanApo objectives standard. Compatible with the Leica M-series stand and illumination ecosystem shared with the M80 and M205 FA. Full fluorescence capability.",
   oem_source:null},

  {id:"leica-m80",name:"M80",series:"M",type:"stereo",subtype:"research stereo",
   introduced:2012,discontinued:false,price_tier:"premium",
   price_new:"$5,000–$18,000",price_used:"$1,500–$6,500",
   illumination:["LED (coaxial + ring)","Optional fluorescence module"],
   magnification:"7.5x–120x (10x eyepieces, 1x PlanApo; 0.63x–2.0x objectives extend range)",
   objectives:"0.5x/0.63x/1.0x/1.6x/2.0x PlanApo (M-series mount)",
   eyepieces:"10x/21mm; binocular or trinocular",stage:"Large format; boom arm option",
   fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS",
   applications:["Research","Industrial QC","Neuroscience","Developmental biology","Fluorescence imaging"],
   noteworthy:"Leica's current mid-tier research stereo. Full PlanApo optics. Compatible with the same M-series fluorescence illuminators and camera ports as the M205. The M80 with fluorescence is a popular choice for labs needing quality fluorescence stereo at a lower price than the M205.",
   oem_source:null},

  {id:"leica-mz16a",name:"MZ16 A",series:"MZ",type:"stereo",subtype:"fluorescence stereo",
   introduced:2003,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$2,500–$7,500",
   illumination:["Halogen (ring + transmitted)","EL6000 fluorescence module"],
   magnification:"7.1x–115x (10x eyepieces, 1x PlanApo; up to 230x with 2x obj; 16:1 zoom)",
   objectives:"0.5x/0.63x/1.0x/1.6x/2.0x planapochromat",
   eyepieces:"10x/23mm; binocular and trinocular",stage:"Large format",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS",
   applications:["Developmental biology","Zebrafish","Drosophila","Fluorescence screening","Neuroscience"],
   noteworthy:"The fluorescence-enhanced variant of the MZ16, adding the EL6000 fiber-coupled fluorescence illuminator. 16:1 zoom with PlanApo optics. Widely used in developmental biology labs for zebrafish, C. elegans, and Drosophila fluorescence screening before the M205 FA era.",
   oem_source:null}
,

{id:"leica-mzapo",name:"MZAPO",series:"MZ",type:"stereo",subtype:"research stereo (APO flagship)",
   introduced:1991,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,500–$5,000",
   illumination:["Halogen (ring + transmitted base)","EL6000 fluorescence (optional)"],
   magnification:"8x–80x (10:1 zoom; 10x eyepieces, 1x PlanApo obj; 9 click-stop steps)",
   objectives:"1x PlanApo (M65 thread, same as Wild M10); 0.5x/0.75x/1.5x/2x auxiliary",
   eyepieces:"10x/21mm; binocular or trinocular; 10–50 degree adjustable viewing angle",stage:"Large flat base",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Developmental biology","Fluorescence","Quality inspection","Macrophotography"],
   noteworthy:"The MZAPO is the direct Leica-branded successor to the Wild M10 following the Wild-Leica merger, confirmed sharing the M10 10:1 zoom body and M65 objective thread. First Leica stereo with the MZ-series ergonomic adjustable tube. Highly sought by macrophotographers and developmental biologists as a cosmetically updated M10 with Leica branding and the same PlanApo optical quality.",
   oem_source:null},

  {id:"leica-mz12",name:"MZ12",series:"MZ",type:"stereo",subtype:"research stereo",
   introduced:1993,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$800–$3,200",
   illumination:["Halogen (ring + transmitted base)","EL6000 fluorescence (optional)"],
   magnification:"8x–100x (12.5:1 zoom; 10x/21mm eyepieces, 1x obj; up to 160x with 1.6x obj)",
   objectives:"1x PlanApo / 0.5x/0.63x/1.0x/1.6x auxiliary",
   eyepieces:"10x/21mm; binocular or trinocular",stage:"Large flat base; transmitted light option",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Quality inspection","Developmental biology","Electronics","Fluorescence (optional)"],
   noteworthy:"The MZ12 was the predecessor to the MZ12.5. Same 12.5:1 zoom body (0.8x–10x range with 1x obj) with earlier-generation PlanApo optics. The MZ12.5 later updated the coatings for improved contrast. Accessories and objectives largely interchangeable with the MZ9.5, MZ12.5, and MZ16 series. Very capable research stereo — good value on the used market.",
   oem_source:null},

  {id:"leica-ez4",name:"EZ4 / EZ4 W",series:"EZ",type:"stereo",subtype:"education / student stereo",
   introduced:2004,discontinued:false,price_tier:"budget",
   price_new:"$500–$1,100",price_used:"$100–$350",
   illumination:["Integrated LED (incident + transmitted)"],
   magnification:"8x–35x (4.4:1 zoom; standard 10x eyepieces; 12.8–56x with 16x eyepieces)",
   objectives:"Fixed Greenough zoom body 0.8x–3.5x; no auxiliary objective",
   eyepieces:"10x high-eyepoint (integrated); 60 degree inclination",stage:"Flat base (integrated); 100mm WD",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"LAS EZ",
   applications:["Education","Introductory biology","Dissection","Gross anatomy","Natural history"],
   noteworthy:"Leica entry education stereo — compact, all-in-one, with integrated LED for incident and transmitted light in the same base. 4.4:1 zoom (8–35x with 10x eyepieces; 12.8–56x with 16x eyepieces). EZ4 W is a wired CMOS camera-integrated version for direct image capture. Extremely popular in European and US schools. ETB (Educational Tool Box) accessory kit designed for it. Sealed optics. Direct competitor to Nikon SMZ445.",
   oem_source:null},

  {id:"leica-s6e",name:"S6 E / S6 APO",series:"S",type:"stereo",subtype:"entry research stereo (current)",
   introduced:2007,discontinued:false,price_tier:"mid",
   price_new:"$1,800–$4,500",price_used:"$400–$1,400",
   illumination:["LED (ring + transmitted)"],
   magnification:"6.3x–40x (6.3:1 zoom; 10x eyepieces, standard 1x objective)",
   objectives:"Achromat 1x (S6 E) or APO 1x (S6 APO); 0.5x/0.63x/1.6x/2x auxiliary",
   eyepieces:"10x/21mm; binocular or trinocular",stage:"Large flat base; various stands",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"LAS EZ",
   applications:["Research","Quality control","Education","Dissection","Electronics","Natural history"],
   noteworthy:"The S-series is Leica current entry research stereo family, replacing the MZ6 and MZ7.5. S6 E uses achromatic optics; S6 APO adds apochromatic correction. Both 6.3:1 zoom. Compact and lightweight. S8 APO (8:1 zoom, better optics) is the next tier up. Widely used in European university labs and QC departments.",
   oem_source:null}

]});
