// ════════════════════════════════════════════════════
// ERNST LEITZ WETZLAR (HISTORICAL)
// ════════════════════════════════════════════════════
DB.companies.push({id:"leitz",name:"Ernst Leitz Wetzlar",shortName:"Leitz",flag:"🇩🇪",country:"Germany",
 founded:1849,status:"historical",featured:false,hq:"Wetzlar, Germany (became Leica)",
 categories:["compound","stereo"],
 overview:"Ernst Leitz GmbH (later Ernst Leitz Wetzlar GmbH) traces back to the Optical Institute founded in Wetzlar in 1849 by Carl Kellner, inventor of the Kellner eyepiece. Ernst Leitz I (1843–1920) took control in 1869 and transformed the modest workshop into one of the world’s premier scientific instrument houses, growing from 10 employees to over 1,000 by 1900. Ernst Leitz II continued this expansion, overseeing the introduction of oil-immersion objectives (1878), apochromatic objectives in the 1880s, and eventually the iconic Leica camera — designed by Oskar Barnack (a Leitz employee) from 1914, first sold commercially in 1925 as the Leica I. The camera and microscope divisions shared manufacturing resources for decades; the camera’s precision mechanics directly reflected Leitz’s microscope manufacturing culture. Critical microscopy milestones: the Ortholux I (1937) — the world’s first truly modular research microscope, with interchangeable lamphouses, heads, condensers, and stands all on a single body — setting the template for every modular research microscope since; the Ploemopak epi-fluorescence system (1965), the first practical upright epi-illumination design widely adopted in biological research; and the FS trinocular tube (c.1953), the first widely-adopted trinocular microscope head design with a beam-splitting prism. Important technical note: Leitz used a 170mm tube length for all research objectives until 1976, when the Dialux 20 introduced the 160mm DIN standard — a critical distinction for collectors buying Leitz objectives. Ernst Leitz Wetzlar merged with Wild Heerbrugg in 1986 to form the Wild Leitz Group, which became Leica Microsystems by 1990–97. The Leica camera business was legally separated and operates today as Leica Camera AG, an entirely independent company with no ownership connection to Leica Microsystems.",
 oem:{acquiredBy:"Became Leica Microsystems (1986 merger with Wild Heerbrugg)",acquired:[],makesFor:[],madeBy:[],notes:"Leica Camera AG (M-series rangefinder cameras) is entirely separate from Leica Microsystems."},
 models:[
  {id:"leitz-orthoplan",name:"Orthoplan",series:"Ortho",type:"compound",subtype:"research upright",
   introduced:1965,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$300–$900",
   illumination:["Halogen","HBO fluorescence lamp"],magnification:"40x–1000x",
   objectives:"Leitz Plan Apo / Fluotar series",eyepieces:"10x/25mm",
   stage:"Mechanical, large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Clinical","Fluorescence","Neuroanatomy"],
   noteworthy:"The quintessential research upright microscope of the 1960s–80s. Extremely robust — many remain in working condition. Leitz optics were considered best-in-class during this era.",
   oem_source:null},
  {id:"leitz-aristoplan",name:"Aristoplan",series:"Aristo",type:"compound",subtype:"research upright (flagship)",
   introduced:1980,discontinued:true,price_tier:"ultra",
   price_new:null,price_used:"$600–$2,200",
   illumination:["Halogen","HBO 200W fluorescence"],magnification:"40x–1000x",
   objectives:"Leitz Plan Fluotar / Plan Apo",eyepieces:"10x/25mm",
   stage:"Mechanical, large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence","Confocal add-on (early)","Neuroanatomy"],
   noteworthy:"Top-of-the-line Leitz instrument of the 1980s. Used as the base for the first commercial confocal microscope (Leica/Bio-Rad MRC 500). Optical quality still impresses collectors today.",
   oem_source:null},

{id:"leitz-ortholux",name:"Ortholux",series:"Ortholux",type:"compound",subtype:"research upright (flagship, 170mm era)",
   introduced:1937,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$300–$1,200",
   illumination:["Incandescent (built-in)","HBO mercury arc (optional for fluorescence)"],
   magnification:"25x–1500x (2.5x–100x objectives, 10x eyepieces; up to 1500x with high-power oil obj and 15x ep)",
   objectives:"Leitz achromat / fluorite / apochromat (170mm TL; Leitz 45mm parfocal thread); phase contrast, DIC, fluorescence available",
   eyepieces:"Periplan 10x; binocular FSA head; trinocular phototube (Panphot system)",stage:"Mechanical stage; rotating stage for polarization; 170mm TL",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","Phase contrast","DIC","Polarization","Photomicrography","Metallurgy"],
   noteworthy:"The Ortholux is the instrument that cemented Leitz\u2019s reputation as the world\u2019s premier microscope maker. Introduced in 1937, it was the first truly modular microscope system allowing virtually any contrast technique by swapping components. Three 170mm body tubes, seven nosepiece options, and 14 condenser configurations. Ploemopak epi-fluorescence module (1965) was first fitted to the Ortholux. Sold until the mid-1970s when superseded by the Ortholux II and Orthoplan. First black, later silver-grey finish. Massive accumulative sales helped Leitz reach one million microscopes sold by 1980. Still actively used and praised by polarization and fluorescence microscopists.",
   oem_source:null},

  {id:"leitz-ortholux1",name:"Ortholux I (Black Enamel)",series:"Ortholux",type:"compound",subtype:"research upright (170mm, black era)",
   introduced:1937,discontinued:1975,price_tier:"mid",price_new:null,price_used:"$200–$800",
   illumination:["External lamphouse (single or dual port, era-dependent)","Transmitted + optional epi-illumination from rear limb ports","Mirror option for daylight"],
   magnification:"40x–1600x (3.5x–100x objectives, 10x eyepieces)",
   objectives:"170mm finite, Leitz thread (RMS-compatible after 1960s). SHORT barrel (37mm parfocal) on oldest units; 45mm parfocal DIN objectives on later units. CRITICAL: verify before buying objectives.",
   eyepieces:"Periplan 10x standard (23.2mm tube)",
   stage:"Mechanical cross-stage; planetary gear fine focus (1 division = 1µm)",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Photomicrography","Fluorescence","Phase contrast","Metallurgy","Polarization"],
   noteworthy:"The world’s first truly modular research microscope, introduced in 1937. Three variants: (1) single lamphouse port (pre-1950s); (2) dual lamphouse ports (1950s–60s); (3) dual ports + field diaphragm (1960s+). CRITICAL: Pre-1960s objectives use 37mm parfocal (‘short barrel’). Later DIN objectives use 45mm. NOT interchangeable without shimming. Leitz used 170mm tube length for all research scopes before 1976. 160mm objectives generally work above 16x magnification (2mm difference is within tolerance) but parfocality is not maintained.",
   oem_source:null},

{id:"leitz-ortholux2",name:"Ortholux II",series:"Ortholux",type:"compound",subtype:"research upright (170mm)",
   introduced:1976,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$300–$1,200",
   illumination:["Halogen 12V/100W","HBO mercury arc fluorescence"],
   magnification:"25x–1500x (2.5x–100x objectives, 10x eyepieces)",
   objectives:"NPL Fluotar / Plan objectives (170mm TL; Leitz 45mm parfocal thread); Ploemopak fluorescence",
   eyepieces:"Periplan 10x/18 or 12.5x/GW; binocular FSA; trinocular FSA phototube",stage:"Mechanical stage; optional rotating stage",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","DIC","Polarization","Photomicrography"],
   noteworthy:"The Ortholux II arrived about ten years after the Orthoplan, as a smaller sibling to the larger Orthoplan stand. It uses 170mm tube length (same as Orthoplan) and shares the FSA phototube system, Ploemopak fluorescence system, and the full range of 170mm objectives and condensers. Excellent for research photomicrography with the Aristophot large-format camera. Many Ortholux II units are still in active use for polarized light and fluorescence work. Introduced in 1976 when Leitz adopted DIN 58887 160mm standard for routine microscopes but retained 170mm for research platforms.",
   oem_source:null},

  {id:"leitz-dialux",name:"Dialux",series:"Dialux",type:"compound",subtype:"routine / teaching upright",
   introduced:1955,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$100–$450",
   illumination:["Incandescent (built-in 6V lamp)","Optional external lamp for fluorescence"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Leitz achromat / EF objectives (170mm TL, RMS thread); phase contrast (Phaco) available",
   eyepieces:"Periplan 10x; binocular 45 degree or monocular",stage:"Mechanical stage (optional)",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Teaching","Clinical routine","Hematology","Basic biology","Medical education"],
   noteworthy:"The Dialux was Leitz\u2019s reliable routine and teaching microscope from the 1950s into the 1980s. A clean, robust design with a triangular base and built-in illumination. Several variants: Dialux (standard), Dialux-Pol (polarizing, 1964), and later the white-body Dialux 20/22 generation (1970s). The black-enamel Dialux of the 1960s is a sought-after collector\u2019s instrument known for its outstanding build quality. Phase contrast (Phaco condenser) was a popular accessory. Widely distributed in European medical schools, hospitals, and industrial labs.",
   oem_source:null},

  {id:"leitz-dialux1",name:"Dialux 1 (Black Enamel)",series:"Dialux",type:"compound",subtype:"routine / teaching upright (170mm, black era)",
   introduced:1956,discontinued:1975,price_tier:"budget",price_new:null,price_used:"$100–$350",
   illumination:["Built-in external lamphouse at base front","170mm tube","Daylight mirror option"],
   magnification:"40x–1000x",
   objectives:"170mm finite, Leitz thread. 37mm parfocal (early) or 45mm parfocal (later DIN). Separate coarse/fine focus (not coaxial).",
   eyepieces:"Periplan 10x (23.2mm tube)",
   stage:"Mechanical; 47mm Leitz dovetail condenser fitting",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","Clinical routine","Hematology"],
   noteworthy:"Original black enamel Dialux — a smaller, more affordable sibling to the Ortholux I. Often misidentified as the Ortholux. Completely different from the later grey-era Dialux 20/22. Uses separate (not coaxial) coarse and fine focus knobs. 47mm Leitz condenser mount on substage.",
   oem_source:null},

{id:"leitz-dialux20",name:"Dialux 20 / Dialux 22",series:"Dialux",type:"compound",subtype:"routine / clinical upright (160mm transition era)",
   introduced:1976,discontinued:1988,price_tier:"mid",price_new:null,price_used:"$150–$500",
   illumination:["Built-in 6V 20W halogen (Dialux 20) or 12V 50W (Dialux 22)","Variable intensity; field iris standard"],
   magnification:"40x–1600x",
   objectives:"160mm finite, Leitz/RMS thread, 45mm parfocal. First Leitz production microscope to use 160mm (DIN 58887, adopted 1976). Compatible with the large Leitz 160mm objective library (NPL, PL, EF series).",
   eyepieces:"Periplan GW 10x/20mm (23.2mm tube)",
   stage:"Mechanical coaxial stage; coaxial coarse + fine focus; Abbe condenser",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical lab","Education","Hematology","Histology"],
   noteworthy:"The Dialux 20 (1976) marks Leitz’s transition from 170mm to 160mm DIN — one of the most significant compatibility milestones in Leitz history. Completely new design vs. the black-enamel Dialux 1: coaxial focus, modern angular lines, built-in Köhler-capable illumination. Filter size: early Dialux 20 condensers use 32mm filters (uncommon); later variants use 25mm.",
   oem_source:null},

{id:"leitz-labolux",name:"Labolux / Laborlux S",series:"Labolux",type:"compound",subtype:"routine / teaching upright",
   introduced:1958,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$100–$500",
   illumination:["Incandescent / Halogen 6V (external lamphouse)","Optional Ploem fluorescence"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"EF / NPL Fluotar (170mm TL, Leitz thread); phase contrast available; Ploem epi-fluorescence (optional)",
   eyepieces:"Periplan 10x; binocular or monocular; trinocular phototube available",stage:"Mechanical stage; coaxial coarse/fine focus",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Clinical routine","Hematology","Pathology","Education","Research","IVF (fixed-stage Laborlux II version)"],
   noteworthy:"The Labolux / Laborlux S family was the backbone of European pathology and clinical labs for three decades. Several generations: Laborlux III (1954, triangular base), Laborlux IIIa (1959), Labolux (1963, identical to IIIa), Labolux-D (1967), and the mature Laborlux S (1970s). The fixed-stage Laborlux II was specifically suited to micromanipulation and early IVF work. Leitz\u2019s NPL Fluotar objectives are particularly prized for fluorescence. Periplan eyepieces. The Laborlux S with Ploem epi-illuminator became one of the most widely distributed research-grade instruments in European labs throughout the 1970s\u201380s.",
   oem_source:null},

  {id:"leitz-sm-lux",name:"SM-LUX / HM-LUX",series:"SM",type:"compound",subtype:"student / hobby upright",
   introduced:1962,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$80–$300",
   illumination:["Incandescent 6V (built-in or lampbox)"],
   magnification:"40x–400x (4x–40x objectives, 10x eyepieces; 1000x with optional 100x oil)",
   objectives:"EF objectives (170mm TL, RMS thread); phase contrast kit available",
   eyepieces:"Periplan 5x or 10x; binocular or monocular",stage:"Fixed or simple mechanical stage",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Student education","Hobby microscopy","Basic biology","Introductory clinical"],
   noteworthy:"The SM-LUX (1958, upgraded to SM-LUX HL with halogen by mid-1960s) and HM-LUX (c.1962, budget hobby version) were Leitz\u2019s accessible entry instruments. Compact and light with the characteristic Leitz triangular base. Simple darkfield and phase contrast kits available for the SM-LUX. The SM-POL polarizing variant was used for student mineralogy courses. These instruments introduced Leitz quality to students and hobbyists at a lower price point than the Laborlux series. Still very functional today and popular with collectors due to their compact size and compatibility with standard RMS objectives.",
   oem_source:null},

  {id:"leitz-diavert",name:"Diavert",series:"Diavert",type:"compound",subtype:"inverted tissue culture",
   introduced:1955,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$800",
   illumination:["Incandescent / Halogen 6V","Optional HBO fluorescence"],
   magnification:"40x–400x (4x–40x LWD phase objectives, 10x eyepieces)",
   objectives:"LWD Leitz objectives (170mm TL); Phaco long working distance phase contrast; Ploem fluorescence optional",
   eyepieces:"Periplan 10x; binocular (same heads as upright Laborlux/Ortholux)",stage:"Mechanical stage 190x130mm",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Tissue culture","Cell biology","IVF","Phase contrast of living cells","Fluorescence cell biology"],
   noteworthy:"The Diavert was Leitz\u2019s classic inverted microscope, described as the inverted counterpart to the Ortholux — nearly all components are interchangeable between the two. The Diavert\u2019s L-shaped stand and upward-facing stage allowed imaging of cells in culture flasks and Petri dishes. Phase contrast via long working distance objectives was the primary use. Ploem epi-fluorescence was a major upgrade option. The Diavert was the inverted counterpart used in pioneering cell biology labs through the 1950s\u201380s. Extremely robust and still functional; sought on the used market by live-cell labs and collectors.",
   oem_source:null},

  {id:"leitz-labovert",name:"Labovert / Labovert FS",series:"Labovert",type:"compound",subtype:"inverted routine / tissue culture",
   introduced:1970,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$150–$600",
   illumination:["Halogen 6V/20W","Optional Ploem fluorescence"],
   magnification:"40x–320x (4x–32x Phaco LWD objectives, 10x eyepieces)",
   objectives:"Leitz Phaco LWD 4x/10x/20x/32x (170mm TL); phase contrast standard",
   eyepieces:"Periplan 10x; binocular",stage:"Mechanical stage; FS variant has fixed stage for micromanipulation",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Tissue culture","IVF","Cell biology","Phase contrast","Micromanipulation (FS version)"],
   noteworthy:"The Labovert was Leitz\u2019s more compact and affordable inverted scope alongside the larger Diavert. It resembles a Laborlux turned upside-down with the objective turret below the stage. The Labovert FS (fixed stage) version was specifically configured for micromanipulation work in IVF and cell injection procedures. Condenser lens above the stage. Ploem epi-fluorescence available. Very robust German construction. A condenser lens from the Labovert is separately listed on used microscope sites as a distinctive component. Bunton Instrument lists the Labovert FS as a go-to for IVF micromanipulation setups.",
   oem_source:null},

  {id:"leitz-diaplan",name:"Diaplan",series:"Diaplan",type:"compound",subtype:"general research upright (160mm, last Leitz)",
   introduced:1985,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$300–$1,200",
   illumination:["Halogen 12V/100W","HBO fluorescence"],
   magnification:"25x–1000x (2.5x–100x objectives, 10x eyepieces)",
   objectives:"NPL Fluotar / EF objectives (160mm TL); field iris and aperture iris BOTH in base — unique Leitz feature",
   eyepieces:"Periplan 10x/18; binocular or trinocular FSA-GW",stage:"Mechanical stage 190x130mm; focus stops (coarse and fine)",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","DIC","Phase contrast","Histology","Cytology"],
   noteworthy:"The Diaplan (1985) was Leitz\u2019s last general research upright before the Leica DM series replaced all finite tube length instruments (~1991). A less expensive alternative to the Aristoplan, sharing most accessories and condensers but at a lower price. Distinguished by having BOTH the field iris AND the aperture/condenser iris located in the base of the microscope — a unique design feature first on the Diaplan. The lamphouse is interchangeable with the Aristoplan and accepts mercury, xenon-arc, and tungsten-halogen. Standard Leitz filter blocks used for epi-fluorescence. The last of the 160mm Leitz finite tube length research instruments.",
   oem_source:null},

  {id:"leitz-metalloplan",name:"Metalloplan",series:"Metalloplan",type:"compound",subtype:"research upright (incident light / metallographic)",
   introduced:1975,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$500–$2,500",
   illumination:["Halogen 12V/100W (incident)","Xenon arc (optional)","Transmitted light (optional)"],
   magnification:"25x–2000x (2.5x–200x incident light objectives with 10x eyepieces)",
   objectives:"NPL / EF epi-objectives (incident light, 160mm or ∞); brightfield, darkfield, DIC, polarization",
   eyepieces:"Periplan 10x or 12.5x; binocular; trinocular (motorized nosepiece optional)",stage:"Large format motorized mechanical stage 130x85mm",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"—",
   applications:["Metallography","Materials science","Semiconductor QC","Failure analysis","Mineralogy","Wafer inspection"],
   noteworthy:"The Metalloplan was Leitz\u2019s top incident-light research metallographic microscope. Primarily designed for epi-illumination of opaque specimens (metals, semiconductors, ores, polished surfaces). Brightfield, darkfield, DIC, and polarization all available in incident light mode. Transmitted light option for geological thin sections. Motorized nosepiece available for automated inspection. Used extensively in metals research labs, semiconductor fabs, and geological survey organizations. The Metallux II and Metallux III were lower-cost alternatives to the Metalloplan for routine incident light work.",
   oem_source:null},

  {id:"leitz-ergolux",name:"Ergolux",series:"Ergolux",type:"compound",subtype:"motorized industrial / semiconductor inspection",
   introduced:1975,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$600–$3,500",
   illumination:["Halogen 12V/100W incident","Transmitted light option"],
   magnification:"50x–2000x (5x–200x objectives with 10x eyepieces)",
   objectives:"NPL / EF plan objectives (incident and transmitted); motorized sextuple nosepiece",
   eyepieces:"Periplan 12.5x/GW; ergonomic trinocular tube (tilting for operator comfort)",stage:"Large motorized 6x6 inch (150x150mm) stage; laser autofocus optional",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:true,inverted:false,camera_port:true,
   software:"—",
   applications:["Semiconductor inspection","Wafer QC","IC inspection","Industrial QC","Materials science","Failure analysis"],
   noteworthy:"The Ergolux was Leitz\u2019s motorized industrial inspection microscope designed for semiconductor wafer inspection (100mm and 150mm wafer sizes) and other industrial QC applications. Its motorized sextuple objective nosepiece and large travel 6x6 inch stage (with coordinated X/Y/Z motorization) enabled systematic wafer scanning. The ergonomic trinocular tube with tilting angle reduced operator fatigue during long inspection sessions. Laser autofocus unit optional for automated focal tracking across wafer surfaces. Used in semiconductor fabs, research institutions, and failure analysis laboratories through the 1970s\u201386. The Bunton Instrument company offers restored Ergolux units as one of the finest available incident-light industrial microscopes.",
   oem_source:null}

]});
