// ════════════════════════════════════════════════════
// MEIJI TECHNO
// ════════════════════════════════════════════════════
DB.companies.push({id:"meiji",name:"Meiji Techno",shortName:"Meiji Techno",flag:"🇯🇵",country:"Japan",
 founded:1964,status:"active",featured:false,hq:"Saitama, Japan",
 categories:["compound","stereo"],
 overview:"Meiji Techno (Meiji Techno Co., Ltd.) was founded in 1964 in Japan and remains one of the few microscope companies that manufactures its complete product range — optics, mechanics, and bodies — entirely in Japan. This all-Japan production, combined with a lifetime limited warranty on all optical components, is a genuine and rare differentiator in a market dominated by Chinese manufacture. Meiji occupies a precision mid-market position: pricing typically 30–60% above equivalent Chinese-made instruments, but below Nikon and Olympus, with a quality difference that justifies the premium. The MT biological series (MT4000, MT5000) are particularly respected in US veterinary and educational markets. The MT7000/MT8000 metallurgical series, the MT9000 polarizing line, and the EMZ zoom stereo family (in production since the 1980s) are individually category leaders. The EMZ zoom stereo body design has been extensively copied by Chinese manufacturers — the original is still superior. Meiji has an unusually strong after-sales reputation for a company of its size, supported by its US subsidiary Meiji Techno America (San Jose, CA).",
 oem:{acquiredBy:null,acquired:[],makesFor:["Unitron Instruments (partial)","Various distributors"],madeBy:[],notes:"Some Unitron models use Meiji-sourced optical components."},
 models:[
  {id:"meiji-mt5000",name:"MT5000 Series",series:"MT",type:"compound",subtype:"clinical / research",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,800–$4,200",price_used:"$400–$1,600",
   illumination:["LED","Halogen"],magnification:"40x–1000x",
   objectives:"Plan Achromat / Plan Semi-Apo",eyepieces:"10x/22mm",
   stage:"Mechanical",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical labs","Research","Multi-contrast imaging","Education"],
   noteworthy:"Plan objectives provide flat, well-corrected field. Fluorescence capable. Japanese manufacturing quality at a mid-range price. Popular in North American university biology departments.",
   oem_source:null},
  {id:"meiji-rz",name:"RZ Series Stereo",series:"RZ",type:"stereo",subtype:"zoom stereo",
   introduced:2009,discontinued:false,price_tier:"mid",
   price_new:"$1,200–$2,900",price_used:"$300–$1,100",
   illumination:["LED ring + transmitted base"],
   magnification:"7x–45x (10x eyepieces)",
   objectives:"0.5x / 0.75x / 1.0x / 2.0x auxiliary",eyepieces:"10x/22mm",
   stage:"Universal foam stage",fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Electronics repair","QC inspection","Natural history","Education"],
   noteworthy:"6.3:1 zoom with parallel-arm Greenough design. Popular in US university biology departments as a reliable, durable dissection scope. Excellent value for Japanese-manufactured optics.",
   oem_source:null}
,

  {id:"meiji-mt4000",name:"MT4000 Series",series:"MT4000",type:"compound",subtype:"student / clinical biological upright",
   introduced:2005,discontinued:false,price_tier:"budget",
   price_new:"$600–1,400",price_used:"$150–$500",
   illumination:["LED (standard current)","Halogen 6V/20W (earlier production)","Variable intensity"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"DIN ICOS Semi-Plan Achromat 4x/10x/40x/100x oil; RMS thread",
   eyepieces:"SWH 10x/22mm; Siedentopf 30° binocular or trinocular; 55–75mm IPD",
   stage:"Two-layer mechanical stage with low-position coaxial controls; Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","Clinical basics","Veterinary","Hematology","University"],
   noteworthy:"Meiji’s entry-level biological compound and most widely deployed scope in US veterinary and educational markets. ICOS infinity optics. Semi-Plan Achromat objectives give noticeably flatter field than basic DIN achromats. All-metal all-Japan manufacture with lifetime limited warranty. The MT4000T (trinocular) adds a camera port. Often compared favorably to AmScope B490 and Motic BA310 with a slight edge in build quality and warranty.",
   oem_source:null},

  {id:"meiji-mt7000",name:"MT7000 / MT7500 Metallurgical",series:"MT7000",type:"compound",subtype:"reflected light / metallurgical upright (incident only)",
   introduced:2000,discontinued:false,price_tier:"mid",
   price_new:"$2,000–4,000",price_used:"$500–1,500",
   illumination:["30W halogen vertical Kohler incident illumination","MT7500 adds darkfield (BD objectives)"],
   magnification:"50x–1000x (5x/10x/20x/50x Plan Epi objectives, 10x eyepieces)",
   objectives:"ICOS Plan Epi 5x/10x/20x/50x (incident brightfield); MT7500: Plan Epi BD variants for darkfield; RMS thread",
   eyepieces:"SWH 10x/22mm (FN22); Siedentopf 30°; 80/20 beamsplitter for trinocular",
   stage:"Mechanical stage; 30mm vertical illumination column",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Metallurgy","Materials science","Semiconductor inspection","Mineralogy","Failure analysis"],
   noteworthy:"MT7000 (incident brightfield only) and MT7500 (adds darkfield via BD objectives) for surfaces requiring only reflected light. All-Japan manufacture, lifetime limited warranty. ICOS infinity Plan Epi objectives. The 80/20 beamsplitter on the trinocular allows simultaneous visual and camera capture.",
   oem_source:null},

  {id:"meiji-mt8000",name:"MT8000 / MT8500 Metallurgical",series:"MT8000",type:"compound",subtype:"reflected + transmitted light / metallurgical upright",
   introduced:2000,discontinued:false,price_tier:"mid",
   price_new:"$3,000–5,000",price_used:"$700–2,000",
   illumination:["30W halogen vertical Kohler incident illumination","30W halogen transmitted Kohler illumination","MT8500 adds darkfield and simple polarization"],
   magnification:"50x–1000x standard",
   objectives:"ICOS Plan Epi 5x/10x/20x/50x; MT8500 adds BD variants; RMS thread",
   eyepieces:"SWH 10x/22mm (FN22); Siedentopf 30° binocular or trinocular",
   stage:"Mechanical stage with both incident and transmitted illumination paths",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Metallurgy","Thin sections","Mineralogy","Semiconductors","Translucent materials"],
   noteworthy:"The MT8000/MT8500 add a 30W transmitted light path to the incident-only MT7000 series, enabling both reflected and transmitted illumination. Essential for translucent or thin-section samples. The MT8500 further adds darkfield and simple polarization. All-Japan manufacture, lifetime limited warranty.",
   oem_source:null},

  {id:"meiji-mt9000",name:"MT9000 / MT9400 / MT9900 Polarizing",series:"MT9000",type:"compound",subtype:"research polarizing compound (petrographic)",
   introduced:1998,discontinued:false,price_tier:"mid",
   price_new:"$2,500–5,000",price_used:"$600–2,000",
   illumination:["LED transmitted (current)","Polarizer below stage; analyzer above objectives"],
   magnification:"40x–1600x (4x–100x objectives, 10x eyepieces)",
   objectives:"ICOS Semi-Plan Achromat or Plan Achromat strain-free series; RMS thread",
   eyepieces:"SWH 10x/22mm; 360° graduated rotating stage; Bertrand lens standard",
   stage:"360° graduated rotating stage with vernier (0.1° resolution); centrable condenser",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Petrology","Mineralogy","Geology","Materials science","Pharmaceutical crystallography"],
   noteworthy:"Meiji’s full polarizing petrographic line: MT9000 (basic), MT9400 (adds lambda plate and quartz wedge), MT9900 (full research config). Graduated rotating stage with 0.1° vernier. Strain-free objectives throughout. All-Japan manufacture. A significant option for geologists wanting Japanese-manufactured quality below Nikon Eclipse Pol or Zeiss Axioplan-Pol pricing.",
   oem_source:null},

  {id:"meiji-emz5",name:"EMZ-5 / EMZ-8 / EMZ-13 Stereo",series:"EMZ",type:"stereo",subtype:"zoom stereo (Greenough, professional Japan-manufactured)",
   introduced:1985,discontinued:false,price_tier:"mid",
   price_new:"$800–2,500",price_used:"$200–$900",
   illumination:["External gooseneck fiber illuminators (standard)","Optional ring light","Optional transmitted base","Optional fluorescence (FL150/FT190)"],
   magnification:"EMZ-5: 7x–45x (6.4:1 ratio); EMZ-8: 8x–56x; EMZ-13: 10x–90x",
   objectives:"Greenough design; 1x standard; 0.5x/0.75x/1.5x/2x auxiliary; 76mm neck diameter",
   eyepieces:"SWH 10x/23mm standard; SWH 20x available; trinocular versions add vertical photo port",
   stage:"Multiple stand options; universal dovetail",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Electronics","PCB rework","Entomology","Gemology","Natural history","Industrial QC"],
   noteworthy:"The EMZ series is arguably Meiji’s most important product — in production since the 1980s and one of the most copied stereo zoom designs in the world. The original EMZ is all-Japan-manufactured with ICOS optics and a lifetime limited warranty. EMZ-5 (6.4:1 zoom) is the standard model; EMZ-8 and EMZ-13 offer higher zoom ratios. 76mm neck diameter is compatible with a wide range of stands and accessories. Trinocular (TR) variants most sought after for documentation.",
   oem_source:null},

  {id:"meiji-emz12",name:"EMZ-1 / EMZ-2 / EMZ-10 / EMZ-12 Entry Zoom Stereo",series:"EMZ",type:"stereo",subtype:"zoom stereo (Greenough, entry-professional)",
   introduced:1990,discontinued:false,price_tier:"budget",
   price_new:"$500–1,200",price_used:"$150–$600",
   illumination:["External gooseneck fiber illuminators","Optional ring light","Optional transmitted base"],
   magnification:"EMZ-1: 7x–45x (6.4:1 zoom); EMZ-2: 10x–70x; EMZ-10: 10x–70x (7:1 zoom); EMZ-12: 10x–90x (9:1 zoom); all with 10x eyepieces",
   objectives:"Greenough design; 1x standard; 0.5x/0.75x/1.5x/2x auxiliary objectives; 76mm neck",
   eyepieces:"SWH 10x/23mm; binocular or trinocular (TR suffix); 55–75mm IPD; 45° incline",
   stage:"Post stand, boom stand, or transmitted light base; 76mm neck; universal dovetail",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Education","Electronics","Entomology","Natural history","QC"],
   noteworthy:"Lower-zoom entry models of the legendary Meiji EMZ family. The EMZ-5/8/13 (in database separately) are the core professional line; these lower models serve education and lighter-duty professional use. All-Japan manufacture. Lifetime limited warranty. EMZ-1 (6.4:1): most basic, 7x–45x. EMZ-2 (7:1): improved range 10x–70x. EMZ-10 (7:1): parallel to EMZ-2 in different head configuration. EMZ-12 (9:1): high-performance body below the EMZ-13. All use 76mm neck for full accessory compatibility. All EMZ bodies accept the same auxiliary objectives and stands as the higher-end models.",
   oem_source:null},

  {id:"meiji-emt",name:"EMT-1 / EMT-2 / EMT-3 / EMT-4 Transmitted Light Stereo",series:"EMT",type:"stereo",subtype:"zoom stereo (Greenough, transmitted light)",
   introduced:2000,discontinued:false,price_tier:"mid",
   price_new:"$1,200–2,500",price_used:"$400–1,000",
   illumination:["Integrated transmitted LED illumination (base)","Optional incident LED ring","Brightfield transmitted standard"],
   magnification:"7x–45x (EMT-1: 6.4:1); 10x–70x (EMT-2: 7:1); 10x–90x (EMT-3/4: 9:1); with 10x eyepieces",
   objectives:"Greenough zoom body on transmitted illumination stand; brightfield transmitted standard",
   eyepieces:"SWH 10x/23mm; binocular (EMT-1/2/3) or trinocular (EMT-4); 55–75mm IPD",
   stage:"Transmitted light stand with glass stage plate; large central opening; variable intensity LED",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Entomology (transparent specimens)","Botany (leaf sections)","Aquatic biology","Thin sections","Textile inspection","Transmitted light dissection"],
   noteworthy:"The EMT series mounts the standard Meiji EMZ Greenough zoom body on a dedicated transmitted light stand, enabling stereo observation of transparent or translucent specimens with backlighting. Essential for: thin botanical sections, aquatic microorganisms, insect wing venation, textile fiber analysis, and any work where transmitted illumination reveals internal structure. EMT-1/2/3 = binocular (increasing zoom ratio); EMT-4 = trinocular for camera documentation. All-Japan manufacture. Lifetime limited warranty. Compatible with all standard EMZ accessories and stands.",
   oem_source:null},

  {id:"meiji-emx1",name:"EMX-1 Reflected Light Stereo",series:"EMX",type:"stereo",subtype:"zoom stereo with coaxial reflected light (metallurgical)",
   introduced:2005,discontinued:false,price_tier:"mid",
   price_new:"$1,500–2,800",price_used:"$500–1,200",
   illumination:["Coaxial (vertical) reflected LED illumination","Incident oblique LED","Optional transmitted LED base"],
   magnification:"7x–45x (6.4:1 zoom; 10x eyepieces); up to 90x with 20x eyepieces",
   objectives:"Greenough zoom body with coaxial illumination attachment above objective",
   eyepieces:"SWH 10x/23mm; binocular or trinocular; 55–75mm IPD",
   stage:"Metal stage; optional transmitted base; coaxial illumination column",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Metallurgy","PCB and semiconductor inspection","Surface analysis","Mineralogy","Ceramics","Failure analysis at stereo magnifications"],
   noteworthy:"The EMX-1 adds coaxial (vertical/episcopic) reflected illumination to the standard Meiji EMZ Greenough stereo body. Coaxial illumination directs light straight down through the optics and onto the sample, eliminating shadows on reflective surfaces — essential for PCB inspection, metallurgical surface analysis, and highly reflective specimens where angled gooseneck illumination creates glare. One of very few stereo microscopes offering true coaxial incident illumination at affordable prices. All-Japan manufacture. Lifetime limited warranty.",
   oem_source:null},

  {id:"meiji-gem",name:"GEM / GMZ Series Gemological Stereo",series:"GEM",type:"stereo",subtype:"zoom stereo (Greenough/CMO, gemological)",
   introduced:1995,discontinued:false,price_tier:"mid",
   price_new:"$1,500–3,500",price_used:"$400–1,200",
   illumination:["Integrated brightfield + darkfield transmitted LED","Oblique incident fluorescent or LED","Variable intensity all channels","Iris diaphragm for darkfield control"],
   magnification:"7x–90x (GEM-EMZ5: 6.4:1; GEM-EMZ13: 9:1); GMZ-41: 6.7x–45x; all with 10x eyepieces",
   objectives:"Greenough or CMO body; 1.0x standard gem objective; articulating gem stand with swivel base",
   eyepieces:"SWH 10x/23mm or high-eyepoint 10x; binocular or trinocular; 54–75mm IPD",
   stage:"Articulating gem stand (swivel base, inclinable); gem clamp; brightfield/darkfield transmitted illumination; iris diaphragm; fluorescent or LED incident ring",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Gemology","Diamond grading","Colored stone appraisal","Jewelry manufacture","Engraving","Watch and jewelry repair","Photomicrography of gemstones"],
   noteworthy:"Meiji GEM series are professional gemological stereo systems built on the EMZ Greenough or CMO body mounted on Meiji dedicated gem stands with comprehensive gemological illumination. Three key configurations: GEMZ-5 (EMZ-5 6.4:1 body on gem stand), GEMZ-13 (EMZ-13 9:1 body for higher magnification), GMZ-41BF/DF (trinocular, 6.7:1 CMO body with brightfield/darkfield). All include: swivel inclinable base stand, darkfield transmitted illumination (essential for inclusion viewing in diamonds), fluorescent or LED incident oblique illumination, iris diaphragm, gem clamp, and dust cover. Professional gemological standard. All-Japan manufacture. Lifetime limited warranty. Direct competitor to Nikon SMZ-745T gem configuration and Zeiss SteREO Discovery gem setups.",
   oem_source:null},

  {id:"meiji-sktsw",name:"SKT / SWF Turret and Wide-Field Stereo Series",series:"SKT/SWF",type:"stereo",subtype:"turret stereo / wide-field stereo (Greenough)",
   introduced:2000,discontinued:false,price_tier:"mid",
   price_new:"$600–1,800",price_used:"$200–$700",
   illumination:["External gooseneck fiber illuminators","Optional ring light","Optional transmitted base"],
   magnification:"SKT: 10x/20x/30x or 10x/20x/40x (3-step turret, lever switch); SWF: 7x–45x with super widefield 23mm eyepieces",
   objectives:"Greenough design; fixed step turret (SKT) or zoom body (SWF); 76mm neck",
   eyepieces:"SKT: WF 10x/20mm standard; SWF: SWF 10x/23mm super widefield; binocular or trinocular",
   stage:"Post stand, boom stand options; 76mm neck; universal dovetail",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","Entomology","Dissection","Routine inspection","Natural history"],
   noteworthy:"Two distinct Meiji stereo lines often grouped together. SKT (Student/Turret) Series: fixed-step turret stereo with lever-switched discrete magnifications — ideal for classroom use where simplicity and durability are more important than zoom flexibility. More robust than continuous zoom mechanisms for heavy educational use. SWF Series: continuous zoom Greenough stereo configured with Meiji super widefield 10x/23mm eyepieces as standard, providing a larger field of view than standard 10x/20mm eyepieces. Both lines use 76mm neck and accept standard Meiji accessories. All-Japan manufacture. Lifetime limited warranty.",
   oem_source:null},

  {id:"meiji-skt-3b",name:"SKT-3B",series:"SKT",type:"stereo",subtype:"fixed dual-power educational",
   introduced:1995,discontinued:true,price_tier:"low",
   price_new:null,price_used:"$100–$250",
   illumination:["Incident 12V/10W halogen (built-in)"],
   magnification:"20x–40x standard (WF10X eyepieces); 15x–80x range with optional WF5X/15X/20X eyepieces",
   objectives:"Fixed 2X & 4X paired turret-mount objectives (click-stop rotation)",
   eyepieces:"WF10X standard paired; WF5X/WF15X/WF20X optional (MA101/103/104)",
   stage:"Black/white plain stage plate (opaque, not frosted — reserved for BT variant); stage clips",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Dissection","QC inspection","Coin/specimen examination"],
   noteworthy:"Meiji Techno \u2018New Series\u2019 SKT-3B, entry-level fixed dual-power (non-zoom) educational stereo microscope, ca.1995 (brochure ref 95.08.187). 45° inclined binocular body, 51–75mm IPD adjustment, single-tube diopter correction, rack-and-pinion focus with safety stopper. Base casting is transmitted-capable but wired incident-only (distinguishes \u2018B\u2019 from \u2018BT\u2019 variant, which adds frosted stage + transmitted bulb). Working distance ~44–45mm (manual states 44mm; brochure optical-data table states 45mm for this objective pair). Owner\u2019s note: SN 30374, excellent condition, no flaws.",
   objective_guide:null,
   accessories:{
     illumination:[
       {name:"Spare bulb",code:"MA111",note:"12V/10W, for incident illuminator."}
     ],
     eyepieces:[
       {name:"WF5X paired",code:"MA101",note:"Wide field, lower power."},
       {name:"WF10X paired (standard)",code:"MA102",note:"Owner's current eyepieces."},
       {name:"WF15X paired",code:"MA103",note:"Higher power option."},
       {name:"WF20X paired",code:"MA104",note:"Highest power option."},
       {name:"WF10X with reticule 0.1mm",code:"MA105",note:"For measurement work."}
     ],
     micrometers:[
       {name:"Eyepiece cross-line",code:"MA523"},
       {name:"Eyepiece 10mm/100 units",code:"MA506"},
       {name:"Eyepiece 5mm/100 units",code:"MA509"},
       {name:"Eyepiece 10mm sq./100 squares",code:"MA510"},
       {name:"Objective 1mm/100 parts",code:"MA285"},
       {name:"Objective 10mm sq./100 squares",code:"MA287"}
     ],
     external_illuminators:[
       {name:"Versatile illuminator, 3-lens condensing, adjustable arm",code:"MA264",note:"6.5V/2.75A bulb; spare bulb MA264/05."},
       {name:"Free-stand illuminator, flood bulb",code:"MA263",note:"Spare bulb MA263/05 (120V/30W) or MA263/10 (220/240V/30W)."}
     ],
     storage:[
       {name:"Wooden cabinet for SKT",code:"MA126"}
     ]
   },
   oem_source:null}]});
