// ════════════════════════════════════════════════════
// MOTIC
// ════════════════════════════════════════════════════
DB.companies.push({id:"motic",name:"Motic Group",shortName:"Motic",flag:"🇭🇰",country:"Hong Kong / China",
 founded:1984,status:"active",featured:false,hq:"Xiamen, China",
 categories:["compound","stereo"],
 overview:"Founded in 1984 and headquartered in Xiamen, China, Motic (Motic Instruments Co., Ltd.) has become the world’s largest OEM microscope manufacturer by volume. Motic’s own CCIS (Color Corrected Infinity System) optical platform delivers genuine research-grade correction at mid-market prices, and the BA and Panthera compound series have earned respect as honest-value instruments in clinical and educational labs worldwide. More broadly, Motic functions as the optical backbone of much of the English-speaking mid-market: instruments sold under AmScope, Swift M-series, Accu-Scope, National Optical, and scores of European and Asian distributor brands frequently originate from Motic’s Xiamen manufacturing campus. The BA310 in particular is arguably the most widely distributed compound microscope platform on earth under any single name. Motic’s 2020-era Panthera C2 and digital pathology PSM1000 represent the company’s push into research and digital pathology. The SMZ168 stereo series and AE31 inverted round out a product range that is more sophisticated than the OEM-supplier narrative might suggest.",
 oem:{acquiredBy:null,acquired:[],makesFor:["AmScope","Swift Optical","LW Scientific (partial)","National Optical (partial)","Many regional brands"],madeBy:[],notes:"Many microscopes sold under AmScope and Swift Optical branding are Motic BA or AE series instruments with cosmetic differences only."},
 models:[
  {id:"motic-ba210",name:"BA210",series:"BA",type:"compound",subtype:"education / clinical",
   introduced:2005,discontinued:false,price_tier:"budget",
   price_new:"$400–$750",price_used:"$80–$260",
   illumination:["LED 3W"],magnification:"40x–1000x",objectives:"Achromat 4x/10x/40x/100x",
   eyepieces:"10x/18mm",stage:"Mechanical 140×130mm",fluorescence:false,phase_contrast:true,
   darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,
   software:"Motic Images Plus 3.0",
   applications:["Education","Clinical labs","Parasitology","Basic biology"],
   noteworthy:"The OEM foundation for AmScope B490 and many similar rebranded instruments. Extremely durable; used in developing-world clinical settings due to low cost and global serviceability.",
   oem_source:null},
  {id:"motic-ae2000",name:"AE2000",series:"AE",type:"compound",subtype:"inverted",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$500–$950",price_used:"$100–$320",
   illumination:["Halogen 6V/20W","LED upgrade available"],magnification:"40x–400x",
   objectives:"LWD Phase Achromat 4x/10x/20x/40x",eyepieces:"10x/18mm",
   stage:"Mechanical 190×140mm",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"Motic Images Plus",
   applications:["Cell culture QC","Tissue culture","Basic cell biology"],
   noteworthy:"Entry-level inverted scope. Often rebranded as AmScope IN300/IN380 series. Very affordable entry into inverted microscopy.",
   oem_source:null},
  {id:"motic-panthera-u",name:"Panthera U",series:"Panthera",type:"compound",subtype:"research upright",
   introduced:2018,discontinued:false,price_tier:"mid",
   price_new:"$1,500–$3,800",price_used:"$400–$1,300",
   illumination:["LED 5W"],magnification:"40x–1000x",objectives:"Plan Semi-Apo 4x/10x/40x/100x",
   eyepieces:"10x/22mm",stage:"Mechanical / optional motorized",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,motorized:false,inverted:false,
   camera_port:true,software:"Motic IMAGES ADVANCED",
   applications:["Research","QC","Clinical pathology","Materials"],
   noteworthy:"Motic's entry into the research segment. Semi-APO objectives provide good field flatness. Available with fluorescence kit. Gaining market traction in emerging economies.",
   oem_source:null},
  {id:"motic-smz168",name:"SMZ-168",series:"SMZ",type:"stereo",subtype:"zoom stereo",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$350–$650",price_used:"$80–$220",
   illumination:["LED ring + transmitted LED"],
   magnification:"7.5x–45x (10x eyepieces)",
   objectives:"Fixed Greenough zoom body 0.75x–4.5x (6:1 ratio)",eyepieces:"10x/21mm",
   stage:"Foam base",fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","QC inspection","Electronics","Jewelry"],
   noteworthy:"6:1 zoom ratio. Excellent value stereo, often rebranded by distributors worldwide. Very common in tech labs and schools across Asia, Africa, and Latin America.",
   oem_source:null}
,

  {id:"motic-ba310",name:"BA310 / BA310E",series:"BA310",type:"compound",subtype:"routine / clinical upright (CCIS, mid-tier)",
   introduced:2008,discontinued:false,price_tier:"budget",
   price_new:"$800–1,800",price_used:"$250–$700",
   illumination:["6V/30W halogen (standard) or LED (E series)","Halogen ↔ LED interchangeable on same stand","Variable intensity; field iris (E series)"],
   magnification:"40x–1000x standard",
   objectives:"CCIS EC Plan Achromat 4x/10x/40x/100x; DIN infinity-corrected, RMS thread.",
   eyepieces:"N-WF 10x/20mm; Siedentopf 30° binocular or trinocular",
   stage:"175x140mm rackless mechanical stage (E series); brass gears; 2um fine focus increments",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Clinical lab","Education","Hematology","Histology","Veterinary","University teaching"],
   noteworthy:"The BA310/BA310E is Motic’s mid-tier clinical workhorse and most widely distributed compound microscope globally. The E (Elite) designation adds a rackless stage and full halogen/LED interchangeability without adjustment. CCIS optics. Anti-fungal coating standard. Phase contrast, darkfield, and polarization accessories available. The BA310 is the most commonly OEM-sourced Motic instrument, sold under Swift, Accu-Scope, National Optical, and others.",
   oem_source:null},

  {id:"motic-ba410e",name:"BA410 / BA410E",series:"BA410",type:"compound",subtype:"research / clinical upright (CCIS, flagship)",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,500–3,500",price_used:"$500–1,500",
   illumination:["12V/100W halogen or LED","Full Kohler illumination with field iris","HBO 100W fluorescence optional (BA410E)","Motic Lumos LED fluorescence module compatible"],
   magnification:"40x–2000x; FN22 eyepieces",
   objectives:"CCIS EC-H Plan Achromat or CCIS UC Plan Fluor series; DIN infinity-corrected, RMS thread",
   eyepieces:"N-WF 10x/22mm; Siedentopf 30° binocular or trinocular",
   stage:"Rackless 175x145mm mechanical stage; 2um fine focus",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Research","Clinical pathology","Cytology","Fluorescence","Hematology"],
   noteworthy:"The BA410E is Motic’s flagship upright compound. Offers the best color fidelity in the Motic compound line. The optional Motic Lumos LED fluorescence illuminator integrates without an HBO lamp. Plan Fluor objectives available for higher NA and contrast. Widely regarded as the best-value research-capable compound below Big Four pricing.",
   oem_source:null},

  {id:"motic-ae31e",name:"AE31 / AE31E Inverted",series:"AE",type:"compound",subtype:"inverted routine / tissue culture (CCIS)",
   introduced:2009,discontinued:false,price_tier:"mid",
   price_new:"$1,200–2,800",price_used:"$300–1,000",
   illumination:["Built-in transmitted LED (sub-stage)","Optional HBO 100W fluorescence (AE31E)","Motic Lumos LED fluorescence compatible"],
   magnification:"40x–400x standard tissue culture (4x–40x LWD objectives)",
   objectives:"CCIS LM Plan Achromat LWD series; DIN infinity-corrected, RMS thread",
   eyepieces:"N-WF 10x/20mm; 30° binocular or trinocular Siedentopf",
   stage:"Fixed stage; large central aperture for T-25 to T-175 flasks; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"Motic Images Plus",
   applications:["Tissue culture","Cell biology","IVF","Microbiology"],
   noteworthy:"Motic’s primary inverted tissue culture microscope and one of the most affordable new fluorescence inverteds available. AE31E adds HBO or Lumos LED fluorescence. Direct competitor to the Zeiss Axiovert 40 and Olympus CKX41 at a lower price point. Anti-fungal coating standard.",
   oem_source:null},

  {id:"motic-ba310met",name:"BA310MET Metallurgical",series:"BA310",type:"compound",subtype:"reflected light / metallurgical upright (CCIS)",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,500–3,000",price_used:"$400–1,200",
   illumination:["Reflected (incident) LED or halogen from above","Optional transmitted LED","Full Kohler incident illumination"],
   magnification:"50x–1500x (5x–150x LM Plan Achromat metallurgical objectives)",
   objectives:"CCIS LM Plan Achromat 5x/10x/20x/50x/100x (coverslip-free /0); DIN infinity-corrected, RMS thread",
   eyepieces:"N-WF 10x/22mm; binocular or trinocular Siedentopf 30°",
   stage:"Mechanical stage; incident illumination pillar",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Metallurgy","PCB inspection","Mineralogy","Ceramics","Surface QC"],
   noteworthy:"Motic’s dedicated reflected-light metallurgical scope. Uses coverslip-free (/0) LM Plan Achromat objectives. Darkfield available via BD objective variants. Most affordable new metallurgical scope from a manufacturer with complete optical infrastructure.",
   oem_source:null},

  {id:"motic-panthera-c2",name:"Panthera C2 / E2",series:"Panthera",type:"compound",subtype:"clinical / research upright (CCIS, latest gen)",
   introduced:2020,discontinued:false,price_tier:"mid",
   price_new:"$2,000–4,500",price_used:"$700–1,800",
   illumination:["LED transmitted (100,000-hour)","Field iris standard","Optional fluorescence turret"],
   magnification:"40x–2000x; FN22",
   objectives:"CCIS EC-H Plan Achromat or UC Plan Fluor; DIN infinity-corrected, RMS thread",
   eyepieces:"SWF 10x/22mm; 30° Siedentopf binocular or trinocular; 48–75mm IPD",
   stage:"Rackless mechanical stage; ceramic-coated anti-glare",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic FlowCam / Motic Images Plus",
   applications:["Clinical pathology","Research","Cytology","Fluorescence","Digital pathology"],
   noteworthy:"Motic’s current-generation flagship, launched 2020. Significant update over the BA410E: full LED standard, ceramic-coated stage, wider 48–75mm IPD range. Motic’s answer to the Nikon Ci and Olympus BX43 in the clinical mid-market. Panthera TEC POL is the polarizing variant.",
   oem_source:null},

  {id:"motic-psm1000",name:"PA53 BIO / PSM1000 Scan",series:"PA/PSM",type:"compound",subtype:"digital pathology / whole-slide scanning",
   introduced:2021,discontinued:false,price_tier:"mid",
   price_new:"$5,000–15,000",price_used:null,
   illumination:["LED transmitted","High-uniformity LED for scanning","Automated Kohler alignment"],
   magnification:"40x–400x scanning configuration",
   objectives:"CCIS EC-H Plan Achromat 4x/10x/20x/40x; DIN infinity-corrected, RMS thread",
   eyepieces:"10x/22mm; motorized platform",
   stage:"Motorized XY stage; automated slide handling",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:true,inverted:false,camera_port:true,software:"EasyStitch Pro (whole-slide imaging and stitching)",
   applications:["Digital pathology","Whole-slide imaging","Telepathology","Education","Remote diagnosis"],
   noteworthy:"Motic’s entry into digital pathology / whole-slide imaging. EasyStitch Pro produces whole-slide images from standard glass slides. An affordable alternative to Hamamatsu NanoZoomer or 3DHistech scanners for labs that don’t need high-throughput scanning.",
   oem_source:null},

  {id:"motic-smz171",name:"SMZ-171 / SMZ-172 Series",series:"SMZ-171",type:"stereo",subtype:"zoom stereo (Greenough, flagship)",
   introduced:2018,discontinued:false,price_tier:"mid",
   price_new:"$800–2,500",price_used:"$400–1,200",
   illumination:["3W LED incident (top) + transmitted (bottom)","Variable intensity independent controls","ESD-safe LED option"],
   magnification:"7.5x–50x (6.7:1 zoom ratio; 10x/23mm eyepieces); up to 200x with 20x eyepieces + 2x auxiliary",
   objectives:"Greenough 0.75x–5.0x zoom; 5 click-stops; 0.3x/0.5x/0.7x/1.5x/2x auxiliary objectives available; 110mm WD standard",
   eyepieces:"WF 10x/FN23 standard; 15x/FN16 and 20x/FN13 available; 52–75mm IPD; 45° incline; 360° rotating",
   stage:"Post stand or boom stand; 76mm neck; black/white reversible insert; ESD-safe stage plate option",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Biomedical research","Materials science","Semiconductor QC","Electronics inspection","Education","Natural history"],
   noteworthy:"Motic flagship Greenough stereo, replacing the SMZ-168. Key improvements over SMZ-168: lead-free optics with improved transmission, ESD-safe materials (important for semiconductor cleanroom use), and expanded auxiliary lens compatibility. Variants: SMZ-171-B (binocular), SMZ-171-T (trinocular), SMZ-171-BL/TL (with integrated LED stand), SMZ-171-P (plain stand, no illumination), SMZ-171-ESD (full ESD-safe build). The SMZ-172 is the SMZ-171 platform in a higher-specification configuration with improved head. Anti-fungal coating standard. 5-year warranty.",
   oem_source:null},

  {id:"motic-smz-lower",name:"SMZ-140 / SMZ-143 / SMZ-160 / SMZ-161 Series",series:"SMZ",type:"stereo",subtype:"zoom stereo (Greenough, mid-tier)",
   introduced:2005,discontinued:false,price_tier:"budget",
   price_new:"$300–$900",price_used:"$100–$450",
   illumination:["LED incident and/or transmitted (model dependent)","Variable intensity"],
   magnification:"7x–45x standard (SMZ-140/143: 6.4:1 zoom; SMZ-160/161: similar range); 10x/20mm eyepieces",
   objectives:"Greenough zoom body; 0.5x/0.75x/1.5x/2x auxiliary objectives compatible; 76mm neck",
   eyepieces:"WF 10x/20mm standard; 45° incline; Siedentopf; 360° rotating",
   stage:"Post stand, boom stand, or flat base; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Education","Routine dissection","QC inspection","Electronics","Natural history"],
   noteworthy:"Mid-tier Motic Greenough stereo family, positioned below the SMZ-168/171 flagship. Variants across this group: SMZ-140 (binocular, 6.4:1 zoom), SMZ-143 (trinocular version of SMZ-140), SMZ-160 (binocular, updated optics), SMZ-161 (trinocular version of SMZ-160). The SMZ-168 (already in database) is the upper tier of this family. All use 76mm neck for stand compatibility. Good value entry point into Motic professional stereos.",
   oem_source:null},

  {id:"motic-k-series",name:"K-400 / K-401 / K-500 / K-700 CMO Series",series:"K",type:"stereo",subtype:"research zoom stereo (CMO, infinity)",
   introduced:2000,discontinued:false,price_tier:"mid",
   price_new:"$1,800–4,500",price_used:"$500–1,800",
   illumination:["Halogen 12V/10W incident + transmitted (standard)","LED upgrade available","Variable intensity controls"],
   magnification:"K-400: 6x/12x/25x/50x (4-step, click-stop); K-500: 6.4x/10x/16x/25x/40x (5-step); K-700: 6x–31x (5.2:1 zoom, dovetail ring mechanism); full range 0.9x–320x with auxiliaries",
   objectives:"CMO (Common Main Objective) infinity optical system; standard 1.0x achromatic objective; interchangeable 0.5x/0.75x/1.5x/2x objectives; parfocal throughout range",
   eyepieces:"SWF 10x/FN23 super widefield standard; 54–76mm IPD; binocular or trinocular heads; discussion bridge (DSK) compatible",
   stage:"Large streamline base; integrated illumination stand; 89mm WD (standard); glass stage plate; gliding stage accessory available",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Research","Industrial QC","Biological research","Education","Materials science","Gemology","Training"],
   noteworthy:"Motic flagship CMO stereo line, directly competing with the Nikon SMZ-U and Zeiss Stemi series. The CMO infinity optical system delivers distortion-free, parfocal images throughout the magnification range. K-400: 4-step precision instrument (6x, 12x, 25x, 50x) for exact measurement and comparison. K-500: 5-step (6.4x, 10x, 16x, 25x, 40x) precision. K-700: Continuous zoom (5.2:1) on self-centering dovetail mechanism with total parfocality. K-401 is the K-400 in a newer production run. Discussion bridge (DSK) compatible for dual-user training — see DSK-500/700 entries. Anti-fungal coating. 5-year warranty.",
   oem_source:null},

  {id:"motic-dsk",name:"DSK-500 / DSK-700 Dual Discussion System",series:"DSK",type:"stereo",subtype:"dual discussion stereo (CMO, teaching/training)",
   introduced:2005,discontinued:false,price_tier:"mid",
   price_new:"$4,000–8,000",price_used:"$1,200–3,000",
   illumination:["Halogen or LED incident + transmitted","Optical bridge carries illumination to secondary head"],
   magnification:"DSK-500: based on K-500 (5-step, 6.4x–40x); DSK-700: based on K-700 (zoom, 6x–31x); both expand with auxiliaries",
   objectives:"CMO infinity optical system; standard 1.0x objective; dual-observer simultaneous viewing",
   eyepieces:"WF 10x/FN23; primary + secondary binocular heads both 45° inclined; optical bridge with pointer",
   stage:"Specialized large surface discussion stand; primary + secondary observer positions",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Teaching","Training","QA/QC","Medical education","Gemological appraisal","Dual consultation"],
   noteworthy:"The DSK (Dual Stereo Knowledge/Discussion) systems mount on the K-400/K-500/K-700 CMO bodies and add an optical bridge with pointer, allowing instructor and student (or two consultants) to simultaneously view the same specimen at identical magnification. DSK-500 is based on the K-500 5-step body; DSK-700 on the K-700 zoom body. The optical bridge includes an arrow pointer visible in both fields of view. An essential configuration for gemology training, pathology consultation, and any application requiring two observers on the same specimen.",
   oem_source:null},

  {id:"motic-sm7",name:"SM-7 CMO Stereo Microscope",series:"SM",type:"stereo",subtype:"research zoom stereo (CMO, compact)",
   introduced:2010,discontinued:false,price_tier:"mid",
   price_new:"$1,500–2,800",price_used:"$400–1,000",
   illumination:["LED ring light (standard)","Boom stand with fiber illuminator option"],
   magnification:"8x–56x (standard 10x eyepieces); up to 180x with 20x eyepieces + 2x auxiliary",
   objectives:"CMO optical system; 0.8x–5.6x zoom; 0.5x/0.75x/1.5x/2x auxiliary objectives; 93mm WD",
   eyepieces:"SWF 10x/FN23; binocular or trinocular; 45° incline; 54–76mm IPD",
   stage:"Boom stand or post stand; 84mm neck diameter; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Electronics inspection","PCB rework","Entomology","Natural history","Gemology","Research"],
   noteworthy:"The SM-7 is Motic compact CMO zoom stereo, providing Common Main Objective image quality at a more accessible price than the K-series. 84mm neck diameter. 8x–56x magnification range with standard eyepieces. CMO optical design delivers parallel light paths for superior resolution and flatness vs. Greenough designs at the same zoom power. LED ring light standard. Popular with electronics repair and jewelry professionals seeking CMO quality without the full K-series investment.",
   oem_source:null},

  {id:"motic-gm171",name:"GM-171 Gemological Stereo",series:"GM",type:"stereo",subtype:"zoom stereo (Greenough, gemological)",
   introduced:2018,discontinued:false,price_tier:"mid",
   price_new:"$1,200–2,500",price_used:"$400–1,000",
   illumination:["Incident LED (oblique and direct)","Transmitted brightfield/darkfield LED","Gem clamp with built-in illumination"],
   magnification:"7.5x–50x (6.7:1 zoom; same SMZ-171 optical body); up to 200x with 20x eyepieces",
   objectives:"Greenough 0.75x–5.0x zoom (SMZ-171 optical body); gemological stand with iris diaphragm",
   eyepieces:"WF 10x/FN23; binocular or trinocular; 45° incline",
   stage:"Articulating gemological stand; integrated brightfield/darkfield transmitted illumination; gem clamp; iris diaphragm",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Gemology","Jewelry appraisal","Diamond grading","Watch and jewelry repair","Engraving"],
   noteworthy:"The GM-171 is the SMZ-171 optical body mounted on Motic dedicated gemological stand. The stand provides: brightfield and darkfield transmitted illumination (essential for viewing gem inclusions in darkfield), oblique incident LED for surface illumination, iris diaphragm, and gem clamp for stone positioning. Same 6.7:1 Greenough zoom optics as the SMZ-171. Competes with Meiji GEM series and Nikon SMZ-745T in gemological configuration. ESD-safe option available.",
   oem_source:null},

  {id:"motic-sfc11",name:"SFC-11 Fixed-Head Stereo",series:"SFC",type:"stereo",subtype:"fixed-objective stereo (Greenough, compact)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$300–$700",price_used:"$100–$300",
   illumination:["LED incident","Optional transmitted base"],
   magnification:"Fixed 10x and 30x (two-position lever switch); no zoom",
   objectives:"Fixed Greenough two-step objectives (10x/30x); sealed optical body",
   eyepieces:"WF 10x; binocular; 45° incline; fixed position",
   stage:"Post stand; flat base with black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Basic dissection","Routine inspection","K–12 biology"],
   noteworthy:"Variants: SFC-11A, SFC-11B, SFC-11C (differ in illumination configuration). The SFC-11 is a fixed two-position (10x/30x) stereo with no zoom mechanism, providing simplicity and durability for educational use. Sealed optical body is resistant to dust and misalignment. Less common than the SMZ series but found in budget educational environments. 76mm neck for stand compatibility.",
   oem_source:null}]});
