// ════════════════════════════════════════════════════
// NATIONAL OPTICAL
// ════════════════════════════════════════════════════
DB.companies.push({id:"national-optical",name:"National Optical",shortName:"National Optical",flag:"🇺🇸",country:"USA",
 founded:1956,status:"active",featured:false,hq:"San Antonio, Texas, USA",
 categories:["compound","stereo"],
 overview:"National Optical & Scientific Instruments, Inc. was founded in 1956 and is headquartered in San Antonio, Texas. National Optical occupies a specific and well-defined niche: affordable DIN-standard compound and stereo microscopes for the US K–12, community college, and clinical markets, with US-based distribution, service, and warranty support. Instruments are sourced from Asian OEM manufacturers (Motic on several configurations) with National Optical handling distribution, QC, and customer service domestically. The 160/161/162/163 compound series has been in continuous production for decades and is one of the most widely encountered microscopes in US high school and community college biology labs — the 161 dual-view teaching head (allowing simultaneous instructor and student viewing on the same instrument) is a particularly practical configuration for classroom use. National Optical maintains a strong regional dealer network across Texas and the Southwest US, and supplies several state school district purchasing contracts. Their veterinary-configured scopes with phase contrast and heated stage options are competitive with LW Scientific and AmScope in the vet practice market.",
 oem:{acquiredBy:null,acquired:[],makesFor:[],madeBy:["Various Chinese OEM manufacturers"],notes:"National Optical instruments are rebranded Chinese OEM microscopes with US distribution and service support."},
 models:[
  {id:"natopt-163",name:"Model 163",series:"100",type:"compound",subtype:"student education",
   introduced:2008,discontinued:false,price_tier:"budget",
   price_new:"$120–$260",price_used:"$30–$110",
   illumination:["LED"],magnification:"40x–1000x",objectives:"Achromat 4x/10x/40x/100x",
   eyepieces:"10x",stage:"Mechanical",fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["K-12 education","Basic biology"],
   noteworthy:"Very basic student microscope. Budget price for school district bulk orders. US warranty and service support. OEM Chinese manufacture. Sold in sets of 10–30 for classroom setups.",
   oem_source:null}
,

  {id:"national-optical-160",name:"160 Series",series:"160",type:"compound",subtype:"student / clinical upright (DIN, routine)",
   introduced:1995,discontinued:false,price_tier:"budget",
   price_new:"$300–$800",price_used:"$80–$300",
   illumination:["12V/20W halogen (standard) or LED","Variable intensity rheostat"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"DIN Achromat 4x/10x/40x/100x standard; optional Plan Achromat (-P suffix) or Super High Contrast (-ASC suffix)",
   eyepieces:"WF 10x/18mm; monocular (160), dual-view teaching (161), binocular (162), trinocular (163)",
   stage:"Large 140x135mm rackless mechanical stage; low-position coaxial controls; Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["K–12 education","Clinical basics","Hematology","Veterinary","Community college"],
   noteworthy:"National Optical’s core compound microscope line and one of the most widely used scopes in US high school and community college biology labs. Available in four head configurations: 160 (monocular), 161 (dual-view teaching head for instructor/student simultaneous viewing), 162 (binocular), 163 (trinocular). The 161 dual-view head is particularly popular in US teaching. Available with Achromat, Plan Achromat (-P), or Super High Contrast (-ASC) objectives. The -PH suffix adds plan phase contrast. Manufactured/distributed from San Antonio, Texas.",
   oem_source:null},

  {id:"national-optical-167",name:"167 Series (LED, current production)",series:"167",type:"compound",subtype:"student / professional upright (LED, current)",
   introduced:2015,discontinued:false,price_tier:"budget",
   price_new:"$400–1,000",price_used:"$150–$400",
   illumination:["3W LED variable rheostat","110-220V auto-switching; CE certified"],
   magnification:"40x–1000x",
   objectives:"DIN Plan Achromat 4x/10x/40x/100x; infinity-corrected; RMS thread",
   eyepieces:"WF 10x/18mm; Siedentopf binocular 30°; 54–76mm IPD",
   stage:"140x135mm rackless ball-bearing mechanical stage; low-position coaxial controls; Abbe NA 1.25",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Education","Clinical basics","Veterinary","Hobbyist","Community college"],
   noteworthy:"National Optical’s current LED-standard binocular compound — effectively a modernized 162 with LED illumination and Plan Achromat objectives as standard. Ball-bearing stage and auto-switching power supply are practical upgrades. Still at a budget price point. Very commonly recommended by US microscopy distributors as a step up from pure import-brand scopes.",
   oem_source:null},

  {id:"national-optical-380",name:"380 Series Stereo",series:"380",type:"stereo",subtype:"zoom stereo (Greenough, education/routine)",
   introduced:2000,discontinued:false,price_tier:"budget",
   price_new:"$300–$700",price_used:"$80–$300",
   illumination:["LED incident (top)","LED transmitted (base)","Simultaneous or independent"],
   magnification:"10x–45x standard (3.5:1 zoom; 10x eyepieces); up to 180x with auxiliaries",
   objectives:"Fixed Greenough zoom body 1x standard; 0.5x/2x auxiliary available",
   eyepieces:"WF 10x/20mm; binocular 45°",
   stage:"Large flat base with black/white reversible plate; 110mm WD",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Dissection","Education","Natural history","Entomology","Stamps and coins","K–12"],
   noteworthy:"National Optical’s primary stereo line for education and routine use. The 380 trinocular version adds a camera port. LED dual illumination with simultaneous incident + transmitted use. Common in US high school biology labs alongside the 160 compound series.",
   oem_source:null},

  {id:"national-optical-vet",name:"Veterinary / Clinical Specialty Scopes",series:"Vet",type:"compound",subtype:"veterinary / clinical specialized compound",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$500–1,200",price_used:"$150–$500",
   illumination:["LED variable","12V DC battery option on some models"],
   magnification:"40x–1000x",
   objectives:"Plan Achromat or Semi-Plan DIN infinity; RMS thread",
   eyepieces:"WF 10x/20mm; Siedentopf binocular or trinocular; rotating head",
   stage:"Mechanical rackless stage; low-position controls",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Veterinary practice","Clinical lab","Urine sediment","Fecal flotation","Hematology","Semen analysis"],
   noteworthy:"National Optical produces several veterinary-targeted configurations optimized for common practice diagnostics. These typically include phase contrast and darkfield condensers, a heated stage option, and a trinocular port for HDMI camera documentation. Strong US veterinary dealer network competing directly with LW Scientific and AmScope in the vet practice market.",
   oem_source:null}]});
