// ════════════════════════════════════════════════════
// BIG FOUR — NIKON
// ════════════════════════════════════════════════════
DB.companies.push({id:"nikon",name:"Nikon Instruments",shortName:"Nikon",flag:"🇯🇵",country:"Japan",
 founded:1917,status:"active",featured:true,hq:"Tokyo, Japan",
 categories:["compound","stereo"],
 overview:"Nikon Corporation traces its roots to July 25, 1917, when three Japanese optical manufacturers merged to form Nippon Kogaku K.K. — a government-supported initiative to build a domestic precision optics industry independent of German imports, backed by Mitsubishi’s Koyata Iwasaki. The company officially became Nikon Corporation in 1988. Microscopy milestones: Japan’s first microscope with revolving nosepiece (the Joico, 1925); the CF (Chrome-Free) optical system in the 1970s, which eliminated chromatic aberration across the full objective-to-eyepiece optical path — a significant advance over prior designs that corrected chromatic errors only within the objective; the Optiphot and Labophot research uprights (1978); the Diaphot inverted (1980s) — used in the first IVF procedures in the UK and USA and later in the cloning of Dolly the sheep (1996); the CFI60 infinity optical system (1994) with long working distances and high NA objectives that remain industry-leading; and the Ti/Ti2 inverted research series which became the dominant live-cell imaging platform globally. Nikon introduced two of the most important super-resolution technologies: N-SIM (structured illumination, licensed from UCSF) and N-STORM (stochastic optical reconstruction, licensed from Harvard), both on the Eclipse Ti platform. Nikon is the only major microscope manufacturer that produces its own optical glass, providing end-to-end quality control.",
 oem:{acquiredBy:null,acquired:[],makesFor:[],madeBy:[],notes:"Nippon Kogaku K.K. was renamed Nikon Corporation in 1988. The instruments division operates as Nikon Instruments Inc. in the USA."},
 models:[
  // ── CURRENT ──
  {id:"nikon-e200",name:"Eclipse E200",series:"Eclipse E",type:"compound",subtype:"student / clinical",
   introduced:2005,discontinued:false,price_tier:"budget",
   price_new:"$1,600–$2,800",price_used:"$350–$800",
   illumination:["Halogen 6V/20W","LED upgrade available"],magnification:"40x–1000x",
   objectives:"CFI Achromat 4x/10x/40x/100x",eyepieces:"10x/18mm",
   stage:"Mechanical 130×85mm",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"NIS-Elements Viewer (free)",
   applications:["Medical education","Clinical labs","Hematology","Basic biology"],
   noteworthy:"Industry workhorse for medical schools globally. Robust CFI60 optical system. Simple, durable, widely serviced worldwide.",
   oem_source:null},
  {id:"nikon-eclipse-ti2",name:"Eclipse Ti2-E",series:"Eclipse Ti2",type:"compound",subtype:"inverted research",
   introduced:2017,discontinued:false,price_tier:"premium",
   price_new:"$30,000–$70,000",price_used:"$7,000–$22,000",
   illumination:["LED","Laser (TIRF)","pE illuminators"],magnification:"40x–1000x",
   objectives:"CFI Plan Apo Lambda (1.49 NA TIRF)",eyepieces:"10x/22mm",
   stage:"Motorized 130×85mm + piezo Z",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"NIS-Elements AR",
   applications:["Live cell","TIRF","Single molecule localization","Spinning disk confocal","High-content"],
   noteworthy:"Perfect Focus System 4 (PFS4) for continuous hardware autofocus during live experiments. 25mm field of view — widest in class for sCMOS sensors. Six-port design for simultaneous multi-modal imaging.",
   oem_source:null},
  {id:"nikon-smz25",name:"SMZ25",series:"SMZ",type:"stereo",subtype:"research zoom stereo",
   introduced:2014,discontinued:false,price_tier:"ultra",
   price_new:"$25,000–$70,000",price_used:"$8,000–$28,000",
   illumination:["LED (ring/coaxial/transmitted)","Fluorescence illuminator"],
   magnification:"6.3x–157.5x (10x ep, 1x obj; up to 480x with accessories)",
   objectives:"SHR Plan Apo 0.5x/1x/1.5x/2x (parfocal bayonet)",eyepieces:"10x/25mm",
   stage:"Large transmitted stage 215×240mm",fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:true,inverted:false,camera_port:true,software:"NIS-Elements",
   applications:["Developmental biology","Genetics","Neuroscience","Model organisms","Surgical guidance"],
   noteworthy:"25:1 zoom ratio (zoom body 0.63x–15.75x) — the world's highest zoom ratio in any stereo microscope. Perfect Zoom System dynamically changes optical axis distance during zooming to maintain high resolution and NA at every position.",
   oem_source:null},
  {id:"nikon-smz745",name:"SMZ745T",series:"SMZ",type:"stereo",subtype:"zoom stereo",
   introduced:2011,discontinued:false,price_tier:"mid",
   price_new:"$2,500–$5,500",price_used:"$700–$2,200",
   illumination:["LED ring","Transmitted base (optional)"],
   magnification:"6.7x–50x (standard 10x/22 eyepieces; 3.35x–300x full range with accessories)",
   objectives:"Greenough zoom body 0.67x–5.0x (7.5:1 ratio); auxiliary G-AL 0.5x/0.7x/1.5x/2x",
   eyepieces:"10x/22mm",stage:"Universal foam stage; optional stands",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,motorized:false,inverted:false,
   camera_port:true,software:"—",
   applications:["Dissection","QC inspection","Electronics","Veterinary","Natural history"],
   noteworthy:"7.5:1 zoom ratio; zoom body 0.67x–5.0x. Working distance 115mm. Airtight/anti-mold/ESD-protected design. Trinocular port for camera.",
   oem_source:null},
  // ── HISTORICAL / COLLECTIBLE ──
  {id:"nikon-alphaphot",name:"Alphaphot / Alphaphot-2 (YS / YS2)",series:"Alphaphot",type:"compound",subtype:"student / education upright (finite)",
   introduced:1978,discontinued:2000,price_tier:"budget",price_new:null,price_used:"$80–$300",
   illumination:["Built-in sub-stage halogen 6V 20W","Variable intensity rheostat"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"160mm finite, RMS thread. CF Achromat series: 4x, 10x, 40x, 100x oil.",
   eyepieces:"CFW 10x/18mm standard",
   stage:"Fixed mechanical stage; coarse + fine focus; NA 1.25 Abbe condenser",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Veterinary","Clinical routine","Hematology","Hobbyist"],
   noteworthy:"Nikon’s entry-level microscope line of the 1980s–90s. First student scopes to use CF (Chrome-Free corrected) optics. Very limited accessory interchangeability with the Labophot/Optiphot. The YS2 is the most commonly encountered variant on eBay. Common configurations: YS2 (binocular), YS2-H (binocular with halogen), YS2-T (trinocular). LED conversion is very popular.",
   oem_source:null},

{id:"nikon-labophot",name:"Labophot",series:"Labophot",type:"compound",subtype:"lab / clinical upright (finite, original)",
   introduced:1978,discontinued:1990,price_tier:"mid",price_new:null,price_used:"$150–$500",
   illumination:["Built-in halogen 6V 20W","Variable intensity; filter slot"],
   magnification:"40x–1000x standard",
   objectives:"160mm finite, RMS thread. CF Achromat and CF Plan Achromat (CFN) series.",
   eyepieces:"CFW 10x/20mm standard; 23.2mm tube",
   stage:"Rackless mechanical stage; coarse + fine focus",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical lab","Hematology","Microbiology","Education"],
   noteworthy:"The original Labophot, first generation of Nikon’s mid-range lab microscope. Stands and focus blocks differ significantly from the Labophot-2 era, though objectives are interchangeable. Known plastic gear failure point in the fine focus.",
   oem_source:null},

{id:"nikon-optiphot",name:"Optiphot",series:"Optiphot",type:"compound",subtype:"research upright (finite, original)",
   introduced:1978,discontinued:1990,price_tier:"mid",price_new:null,price_used:"$200–$700",
   illumination:["Built-in halogen 12V 50W or 100W (model dependent)","Variable intensity; wide filter holder"],
   magnification:"40x–1600x; full DIC and fluorescence capable",
   objectives:"160mm finite, RMS thread. CF Achromat, CFN Plan Achromat, CF Fluor, CF Plan Fluor, CF Apochromat series.",
   eyepieces:"CFW 10x/20mm; 23.2mm tube. CF EW 10x/25mm wide-field available.",
   stage:"Large mechanical stage; coarse + fine coaxial; achromatic condenser NA 1.25",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Clinical pathology","Fluorescence","Phase contrast","DIC","Photomicrography"],
   noteworthy:"Top of Nikon’s finite-era upright line — direct competitor to the Olympus BH-2 BHS. Full DIC and epi-fluorescence. Objectives interchangeable with the Labophot and Optiphot-2. Plastic fine-focus gear failure is a known issue. The Optiphot-POL (polarizing) variant is particularly sought after by geologists.",
   oem_source:null},

{id:"nikon-optiphot2",name:"Optiphot-2",series:"Optiphot",type:"compound",subtype:"research upright",
   introduced:1987,discontinued:1994,price_tier:"mid",
   price_new:null,price_used:"$150–$550",
   illumination:["Halogen 6V/30W","HBO fluorescence"],magnification:"50x–1000x",
   objectives:"CF Plan Achromat / CF Plan Fluorite (pre-CFI60)",eyepieces:"10x/18mm",
   stage:"Mechanical large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence","Neuroscience","Histology","Materials"],
   noteworthy:"The Optiphot was Nikon's flagship research upright of the 1980s. The -2 update improved fluorescence capability. Used in thousands of university labs worldwide. Pre-CFI60 objectives but still excellent optical quality. One of the most affordable entry points into Nikon research optics on the used market.",
   oem_source:null},
  {id:"nikon-labophot2",name:"Labophot-2",series:"Labophot",type:"compound",subtype:"lab / clinical upright",
   introduced:1988,discontinued:1995,price_tier:"budget",
   price_new:null,price_used:"$100–$380",
   illumination:["Halogen 6V/20W"],magnification:"40x–1000x",
   objectives:"CF Plan Achromat 4x/10x/40x/100x",eyepieces:"10x/18mm",
   stage:"Mechanical",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical labs","Medical education","Hematology","Basic biology"],
   noteworthy:"Nikon's workhorse clinical/lab upright of the late 1980s–early 1990s. Sold in huge quantities to hospitals, veterinary clinics, and universities. Very durable and well-supported. One of the most common used scopes available, extremely affordable.",
   oem_source:null},
  {id:"nikon-diaphot200",name:"Diaphot 200 / 300",series:"Diaphot",type:"compound",subtype:"inverted research (finite, multi-port)",
   introduced:1994,discontinued:1997,price_tier:"mid",price_new:null,price_used:"$300–$1,500",
   illumination:["12V/50W halogen transmitted","100W mercury epi-fluorescence (optional)","80%/20% eyepiece/side-port split standard","100% bottom port for detectors"],
   magnification:"25x–1000x; optovar 1x/1.5x magnification changer",
   objectives:"160mm finite, RMS thread. CF Fluor, CF Plan Fluor, CF Plan Apochromat series.",
   eyepieces:"CFW 10x/22mm; 45° binocular; Bertrand lens for phase ring alignment built in",
   stage:"Full mechanical stage; multiple plate adapters; tiltable body arm",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell biology","Fluorescence","DIC","Confocal coupling","Video microscopy","Patch clamp"],
   noteworthy:"Introduced 1994 as successor to the original Diaphot. Remained the most widely used research inverted of its era until replaced by the Eclipse TE300 in 1997. Built-in Bertrand lens for phase ring centering. The bottom port provides 100% light transmission to a detector — excellent for confocal. Uses 160mm RMS objectives (same as Labophot/Optiphot). NOT objective-compatible with the CFI60 TE300.",
   oem_source:null},

{id:"nikon-diaphot300",name:"Diaphot (original)",series:"Diaphot",type:"compound",subtype:"inverted routine",
   introduced:1985,discontinued:1994,price_tier:"mid",
   price_new:null,price_used:"$200–$650",
   illumination:["Halogen","HBO fluorescence (optional)"],magnification:"40x–400x",
   objectives:"CF LWD Phase Achromat 4x/10x/20x/40x",eyepieces:"10x/22mm",
   stage:"Mechanical 190×160mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell culture","Tissue culture","IVF","Basic cell biology","Clinical cytology"],
   noteworthy:"The Diaphot was the standard inverted scope for cell culture labs of the late 1980s–90s. The 300 model added fluorescence capability. Used extensively in IVF clinics, biotech, and university cell biology labs. Widely available and affordable on the used market.",
   oem_source:null},
  {id:"nikon-microphot-fxa",name:"Microphot-FXA",series:"Microphot",type:"compound",subtype:"research/photomicrography upright",
   introduced:1986,discontinued:1994,price_tier:"premium",
   price_new:null,price_used:"$200–$750",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence"],magnification:"50x–1000x",
   objectives:"CF Plan Achromat / CF Plan Apochromat",eyepieces:"10x/22mm",
   stage:"Mechanical large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Photomicrography","Fluorescence","Neuroscience","Histology"],
   noteworthy:"Top-of-the-line Nikon research scope of the mid-1980s, designed for photomicrography. The FXA had excellent optics and a dedicated photographic tube. Used in high-end research labs and institutions requiring publishable photomicrographs. Good used value.",
   oem_source:null},
  {id:"nikon-eclipse-e600",name:"Eclipse E600",series:"Eclipse E",type:"compound",subtype:"research upright",
   introduced:1994,discontinued:2005,price_tier:"mid",
   price_new:null,price_used:"$600–$1,900",
   illumination:["Halogen 12V/100W","HBO fluorescence"],magnification:"50x–1000x",
   objectives:"CFI Plan Achromat / CFI Plan Fluor (first CFI60 generation)",eyepieces:"10x/22mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence","Clinical pathology","Neuroscience","Histology"],
   noteworthy:"The Eclipse E600 introduced Nikon's CFI60 (chrome-free infinity) optical system, which remains the standard for Nikon objectives today. First-generation CFI60 objectives. Still highly regarded and widely used. CFI60 objectives from current Nikon systems are backward-compatible.",
   oem_source:null},
  {id:"nikon-eclipse-e800",name:"Eclipse E800",series:"Eclipse E",type:"compound",subtype:"research upright (top-tier)",
   introduced:1994,discontinued:2005,price_tier:"premium",
   price_new:null,price_used:"$1,000–$3,200",
   illumination:["Halogen 12V/100W","HBO 100W / 200W fluorescence","Metal halide option"],
   magnification:"50x–1000x",objectives:"CFI Plan Fluor / CFI Plan Apo (1.4 NA)",eyepieces:"10x/22mm",
   stage:"Mechanical / motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","DIC","Fluorescence","Neuroscience","Materials"],
   noteworthy:"The E800 was the top CFI60 research upright of the 1990s–2000s, with full DIC capability and support for the complete CFI Plan Apo objective range. Excellent optics still competitive with modern instruments. A highly recommended used purchase for well-equipped labs.",
   oem_source:null},
  {id:"nikon-te300",name:"Eclipse TE300",series:"Eclipse TE",type:"compound",subtype:"inverted research",
   introduced:1997,discontinued:2006,price_tier:"premium",
   price_new:null,price_used:"$700–$2,200",
   illumination:["Halogen","HBO 100W fluorescence"],magnification:"40x–1000x",
   objectives:"CFI Plan Fluor LD (long working distance)",eyepieces:"10x/22mm",
   stage:"Mechanical 200×160mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Live cell","Cell culture","Fluorescence","FRET (early)","Timelapse"],
   noteworthy:"First generation CFI60 inverted research scope. Widely used in cell biology labs of the late 1990s–2000s. Good fluorescence capability and DIC. Precursor to the Ti series. Widely available on the used market with strong parts and accessories availability.",
   oem_source:null},
  {id:"nikon-smz1500",name:"SMZ1500",series:"SMZ",type:"stereo",subtype:"research zoom stereo",
   introduced:1999,discontinued:2010,price_tier:"premium",
   price_new:null,price_used:"$2,000–$5,800",
   illumination:["Halogen / LED (ring + transmitted)","Fluorescence option"],
   magnification:"7.5x–225x (with 1.5x objective and 10x eyepieces)",
   objectives:"Plan Apo 0.5x/0.75x/1.0x/1.5x/2.0x",eyepieces:"10x/22mm",
   stage:"Large format transmitted + reflected",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Fluorescence screening","Dissection","Model organisms","Surgery"],
   noteworthy:"15:1 zoom ratio with full fluorescence capability. The SMZ1500 was Nikon's top research stereo before the SMZ25 era. Outstanding optical performance with plan apochromatic objectives. Still very widely used in developmental biology labs for fluorescence screening. Excellent used market value.",
   oem_source:null},

{id:"nikon-optiphot",name:"Optiphot",series:"Optiphot",type:"compound",subtype:"research upright (CF optics)",
   introduced:1978,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$100–$400",
   illumination:["Halogen 6V/30W","HBO fluorescence"],
   magnification:"40x–1000x (4x–100x CF objectives, 10x/18mm eyepieces)",
   objectives:"CF Plan Achromat / CF Plan Fluorite (160mm, pre-CFI60)",
   eyepieces:"10x/18mm; binocular; HFX trinocular camera system",stage:"Mechanical large format",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Fluorescence","Neuroscience","Histology","Phase contrast","Photomicrography"],
   noteworthy:"The original Optiphot (1978) introduced Nikon's CF (Chrome-Free) optical system to the research market. CF optics corrected chromatic aberration within the objectives — a significant improvement over compensating eyepiece systems. The built-in HFX camera system was a major selling point. Extremely durable; thousands remain in active use today.",
   oem_source:null},

  {id:"nikon-diaphot-tmd",name:"Diaphot TMD",series:"Diaphot",type:"compound",subtype:"inverted routine",
   introduced:1982,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$150–$500",
   illumination:["Halogen 6V/20W"],
   magnification:"40x–400x (4x–40x CF LWD objectives, 10x/20mm eyepieces)",
   objectives:"CF LWD Phase Achromat 4x/10x/20x/40x (160mm, long working distance)",
   eyepieces:"10x/20mm; binocular",stage:"Mechanical 190x160mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Cell culture","Tissue culture","IVF","Basic cell biology","Clinical cytology"],
   noteworthy:"The original Diaphot TMD was Nikon's entry inverted of the early 1980s, used in virtually every cell culture and IVF lab equipped with Nikon instruments. Phase contrast via LWD objectives. Extremely common on the used market. Succeeded by the Diaphot 200/300.",
   oem_source:null},

  {id:"nikon-eclipse-e400",name:"Eclipse E400",series:"Eclipse E",type:"compound",subtype:"clinical / routine upright (CFI60)",
   introduced:1994,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$250–$900",
   illumination:["Halogen 6V/20W"],
   magnification:"40x–1000x (4x–100x CFI objectives, 10x/18mm eyepieces)",
   objectives:"CFI Plan Achromat / CFI Plan Fluorite 4x/10x/40x/100x (first CFI60 generation)",
   eyepieces:"10x/18mm; binocular 30°",stage:"Mechanical 130x85mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"NIS-Elements Viewer",
   applications:["Clinical labs","Medical education","Hematology","Basic biology"],
   noteworthy:"The Eclipse E400 introduced the CFI60 optical system to Nikon's routine/clinical segment. First-generation CFI60 optics. Sits between the E200 (education) and E600 (research) in the Eclipse hierarchy. Very affordable entry into CFI60 Nikon optics on the used market.",
   oem_source:null},

  {id:"nikon-eclipse-e1000",name:"Eclipse E1000",series:"Eclipse E",type:"compound",subtype:"research upright (CFI60 flagship)",
   introduced:1994,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$700–$2,800",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence","Metal halide option"],
   magnification:"50x–1000x (5x–100x CFI objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Fluor / CFI Plan Apo (1.4 NA; first CFI60 research generation)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Large format; motorized optional",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Fluorescence","DIC","Neuroscience","Materials","Photomicrography"],
   noteworthy:"Nikon's top research upright in the first CFI60 generation — the flagship above the E800. Accepts the full range of CFI Plan Apo objectives including 1.4 NA 100x oil. Full DIC, fluorescence, and darkfield. The E1000M motorized version for automated imaging. Widely installed in major research institutions through the 2000s.",
   oem_source:null},

  {id:"nikon-eclipse-80i",name:"Eclipse 80i",series:"Eclipse i",type:"compound",subtype:"research upright (digital era)",
   introduced:2005,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,500–$5,500",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence","Metal halide","LED (later)"],
   magnification:"50x–1000x (5x–100x CFI60-2 objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Fluor / CFI Plan Apo (CFI60-2 generation)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized (M version) or manual; large format",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"NIS-Elements",
   applications:["Research","Fluorescence","DIC","Neuroscience","Digital pathology","Multi-position imaging"],
   noteworthy:"One of the first in Nikon's i-series upright range, designed for the digital imaging era. CFI60-2 objectives with improved chromatic correction. Designed around digital camera ports rather than film. Became a very popular research upright in the 2005–2015 era, widely installed in core imaging facilities globally.",
   oem_source:null},

  {id:"nikon-eclipse-90i",name:"Eclipse 90i",series:"Eclipse i",type:"compound",subtype:"motorized research upright",
   introduced:2007,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$2,500–$9,000",
   illumination:["Halogen 12V/100W","Metal halide / LED fluorescence"],
   magnification:"50x–1000x (5x–100x CFI60-2 objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Apo Lambda (1.45 NA; TIRF objectives compatible)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized encoded 130x85mm + piezo Z",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"NIS-Elements AR",
   applications:["Research","Multi-position imaging","Fluorescence","Digital pathology","Automated tiling","Neuroscience"],
   noteworthy:"Nikon's flagship upright research scope of the 2007–2017 era. Added full motorization over the 80i — encoded stage, motorized objective nosepiece, and z-drive. NIS-Elements AR for automation. Perfect Focus System 2 (PFS2) hardware autofocus available. Predecessor to the Eclipse Ni-E.",
   oem_source:null},

  {id:"nikon-eclipse-te2000",name:"Eclipse TE2000",series:"Eclipse TE",type:"compound",subtype:"inverted research (CFI60)",
   introduced:2000,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$600–$2,800",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence","Metal halide option"],
   magnification:"40x–1000x (4x–100x CFI LWD objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Fluor LD / CFI Plan Apo LWD (1.49 NA TIRF compatible)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized 130x85mm (U/E versions)",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,
   software:"NIS-Elements",
   applications:["Live cell","TIRF","Cell biology","Drug discovery","Fluorescence","Spinning disk confocal"],
   noteworthy:"Nikon's first major CFI60 inverted research platform and a landmark instrument that defined inverted microscopy for a generation. Three models: S (standard), U (4 ports), E (motorized, PFS). The Noise Terminator reduced digital imaging artifacts. Widely paired with Yokogawa CSU spinning disks. Predecessor to the Eclipse Ti series.",
   oem_source:null},

  {id:"nikon-eclipse-ti",name:"Eclipse Ti-E",series:"Eclipse Ti",type:"compound",subtype:"inverted research (CFI60-2)",
   introduced:2006,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$3,000–$12,000",
   illumination:["LED","Laser (TIRF)","Metal halide","pE illuminators"],
   magnification:"40x–1000x (4x–100x CFI objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Apo Lambda (1.45 NA TIRF; CFI60-2 generation)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized 130x85mm + piezo Z",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,
   software:"NIS-Elements AR",
   applications:["Live cell","TIRF","STORM","Single molecule","Spinning disk confocal","Drug discovery"],
   noteworthy:"The most widely adopted high-end inverted research scope of the 2006–2017 era. Perfect Focus System 2 (PFS2) hardware autofocus. Six-port design with optical path switching. Versatile platform for spinning disk, TIRF, PALM/STORM, and widefield. Predecessor to the Ti2-E. Still in active use in thousands of labs worldwide.",
   oem_source:null},

  {id:"nikon-eclipse-ci",name:"Eclipse Ci",series:"Eclipse Ci",type:"compound",subtype:"clinical / routine upright",
   introduced:2013,discontinued:false,price_tier:"mid",
   price_new:"$1,800–$4,500",price_used:"$500–$1,600",
   illumination:["LED","Halogen 6V/30W"],
   magnification:"40x–1000x (4x–100x CFI Plan objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Achromat / CFI Plan Fluor (CFI60-2)",
   eyepieces:"10x/22mm; binocular 30°; trinocular available",stage:"Mechanical 130x85mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"NIS-Elements Viewer",
   applications:["Clinical labs","Medical education","Hematology","Histology","Cytology"],
   noteworthy:"Replaced the E200 as Nikon's primary clinical/routine upright. LED illumination standard. Wider CFI60-2 plan objectives providing better flat field than the E200's achromats. The Ci-L is a motorized variant; the Ci-S is a simplified student version. Ergonomic design suited for high-volume clinical use.",
   oem_source:null},

  {id:"nikon-eclipse-ni",name:"Eclipse Ni-E",series:"Eclipse Ni",type:"compound",subtype:"research upright (current)",
   introduced:2013,discontinued:false,price_tier:"premium",
   price_new:"$8,000–$25,000",price_used:"$2,000–$8,500",
   illumination:["LED","Halogen 12V/100W","Metal halide fluorescence"],
   magnification:"50x–1000x (5x–100x CFI Plan Apo Lambda objectives, 10x/22mm eyepieces)",
   objectives:"CFI Plan Apo Lambda (1.4–1.45 NA; highest correction in CFI60-2)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized 130x85mm + piezo Z (E version)",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"NIS-Elements AR",
   applications:["Research","Digital pathology","Multi-position imaging","Fluorescence","Neuroscience","Materials science"],
   noteworthy:"Nikon's current flagship research upright, succeeding the 90i. CFI Plan Apo Lambda objectives — the highest-correction Nikon objectives. Perfect Focus System 3 (PFS3) hardware autofocus. Full motorization for automated tile scans and multi-position experiments. ApoTome 2 structured illumination compatible.",
   oem_source:null},

  {id:"nikon-smz-u",name:"SMZ-U",series:"SMZ",type:"stereo",subtype:"research zoom stereo",
   introduced:1995,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$600–$2,200",
   illumination:["Halogen (ring + transmitted)","Fluorescence option"],
   magnification:"7.5x–225x (7.5:1 zoom; 10x eyepieces with 0.5x–2.0x objectives)",
   objectives:"Plan Apo 0.5x/0.75x/1.0x/1.5x/2.0x (parfocal)",
   eyepieces:"10x/22mm; binocular or trinocular",stage:"Large format",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Developmental biology","Fluorescence screening","Dissection","Model organisms"],
   noteworthy:"Nikon's first true research-grade zoom stereo with plan apochromatic objectives. 7.5:1 zoom with parfocal interchangeable objectives. Full fluorescence capability. Important predecessor to the SMZ1500 and SMZ25. Widely used in developmental biology labs in the late 1990s–early 2000s.",
   oem_source:null},

  {id:"nikon-smz2t",name:"SMZ-2T",series:"SMZ",type:"stereo",subtype:"zoom stereo (Greenough, trinocular)",
   introduced:1982,discontinued:1995,price_tier:"mid",price_new:null,price_used:"$150–$500",
   illumination:["External gooseneck fiber illuminator","Optional transmitted base"],
   magnification:"7x–30x (binocular configuration; 3.5:1 zoom)",
   objectives:"Greenough design; fixed objective pair; 1x standard",
   eyepieces:"FW 10x/20mm; 45° incline",
   stage:"Flat base standard; 76mm neck diameter",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Education","Electronics","Entomology"],
   noteworthy:"Trinocular variant of the classic Nikon SMZ-2 stereo, adding a vertical photo port. Very common in school and university surplus. 76mm neck diameter compatible with a wide range of Nikon SMZ-series stands. LED ring light adapters available.",
   oem_source:null},

{id:"nikon-smz800",name:"SMZ800 / SMZ800N",series:"SMZ",type:"stereo",subtype:"zoom stereo",
   introduced:2001,discontinued:false,price_tier:"mid",
   price_new:"$2,000–$5,000",price_used:"$400–$1,500",
   illumination:["LED ring + transmitted base"],
   magnification:"10x–80x (8:1 zoom; standard 10x/22mm eyepieces)",
   objectives:"Greenough zoom body 1.0x–8.0x; optional 0.5x/2.0x auxiliary",
   eyepieces:"10x/22mm; binocular or trinocular",stage:"Universal flat base; boom stand option",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Electronics","Education","Natural history"],
   noteworthy:"Mid-tier zoom stereo between the SMZ745 and the research SMZ1500/SMZ25. 8:1 zoom. Airtight construction prevents dust/fungus contamination. The SMZ800N (2013 update) includes ESD protection for electronics inspection. Very widely used in biological dissection and industrial QC environments.",
   oem_source:null},

  {id:"nikon-smz18",name:"SMZ18",series:"SMZ",type:"stereo",subtype:"research zoom stereo",
   introduced:2016,discontinued:false,price_tier:"ultra",
   price_new:"$18,000–$55,000",price_used:"$5,000–$20,000",
   illumination:["LED ring/coaxial/transmitted","Fluorescence illuminator"],
   magnification:"3.15x–480x (18:1 zoom; 10x eyepieces, 1x obj; full accessory range)",
   objectives:"SHR Plan Apo 0.5x/1x/1.5x/2x (parfocal bayonet mount)",
   eyepieces:"10x/25mm; binocular or trinocular",stage:"Large transmitted stage",
   fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:true,inverted:false,camera_port:true,
   software:"NIS-Elements",
   applications:["Developmental biology","Model organisms","Fluorescence screening","Neuroscience"],
   noteworthy:"18:1 zoom companion to the SMZ25. Same Perfect Zoom System optical design. Plan Apo objectives with parfocal bayonet mount. Fly-eye fluorescence for uniform illumination. Sits between the SMZ745T and SMZ25 in the Nikon stereo lineup.",
   oem_source:null},

  {id:"nikon-az100",name:"AZ100 Multizoom",series:"AZ",type:"stereo",subtype:"macro zoom / multizoom",
   introduced:2007,discontinued:false,price_tier:"ultra",
   price_new:"$15,000–$45,000",price_used:"$4,000–$15,000",
   illumination:["LED ring + coaxial","Fluorescence illuminator (AZ-FLamp)"],
   magnification:"1x–400x (10x eyepieces; 0.5x–8x zoom body × multiple objectives)",
   objectives:"AZ Plan Fluor 0.5x/1x/2x/4x (large-format, 45mm parfocal)",
   eyepieces:"10x/22mm; binocular or trinocular",stage:"Large format 215x195mm",
   fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:true,inverted:false,camera_port:true,
   software:"NIS-Elements",
   applications:["Macro-to-micro imaging","Developmental biology","Brain atlasing","Whole organ imaging","Model organisms"],
   noteworthy:"A unique instrument bridging the gap between stereo and compound microscopy. 1x–400x total range without changing the specimen. The AZ Plan Fluor 1x objective covers a 15mm field of view at 10x magnification. Widely used in brain atlas projects and whole-organism fluorescence imaging. Outstanding for zebrafish, mouse brain sections, and cleared tissue.",
   oem_source:null}
,

{id:"nikon-smz1",name:"SMZ-1 / SMZ-2T",series:"SMZ",type:"stereo",subtype:"zoom stereo (original series)",
   introduced:1966,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$100–$400",
   illumination:["Halogen (incident ring light or external gooseneck)","Optional transmitted base"],
   magnification:"7x–30x (SMZ-1 with 10x/22mm eyepieces; 0.7x–3x body zoom)",
   objectives:"Fixed Greenough zoom body 0.7x–3.0x; 0.5x/2x auxiliary",
   eyepieces:"10x/22mm (30mm eyetube on original SMZ-1); SMZ-2T adds trinocular port",stage:"Flat base or transmitted light base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","Education","Basic biological observation","Natural history"],
   noteworthy:"The original SMZ series launched in 1966 was Nikon first stereomicroscope line. The SMZ-2T (trinocular version) was widely used for photomicrography in the 1970s–1980s. Simple Greenough zoom design. The SMZ-1B (updated variant) added improved ergonomics. Different mechanism from all later SMZs — zoom via a collar ring rather than a side knob.",
   oem_source:null},

  {id:"nikon-smz10",name:"SMZ10 / SMZ10A",series:"SMZ",type:"stereo",subtype:"zoom stereo (Greenough)",
   introduced:1980,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$700",
   illumination:["Halogen (ring light or external gooseneck)","Optional transmitted base"],
   magnification:"6.6x–40x (0.66x–4.0x body zoom; standard 10x eyepieces)",
   objectives:"Fixed Greenough zoom body 0.66x–4.0x; auxiliary objectives available",
   eyepieces:"10x/22mm; binocular; trinocular (SMZ10A) available",stage:"Flat base or transmitted light base",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Education","Natural history","Biology"],
   noteworthy:"The SMZ10 was Nikon second-generation stereo (~1980), successor to the SMZ-1. Improved optics with zoom collar mechanism. The SMZ10A added a trinocular head with photo switching. Notable: both left and right optical paths can be used for photography on the SMZ10 — allowing genuine stereo photography. Succeeded by the SMZ-U in the early 1990s.",
   oem_source:null},

  {id:"nikon-smz645",name:"SMZ645",series:"SMZ",type:"stereo",subtype:"zoom stereo (Greenough)",
   introduced:2001,discontinued:false,price_tier:"mid",
   price_new:"$900–$2,500",price_used:"$200–$650",
   illumination:["Halogen ring light P-ILLD (standard)","External gooseneck fiber illuminator","Transmitted light stand P-TBD (optional below-stage)","EPI fluorescence module P-FLA (optional)","Dual above + below simultaneous with P-TBD base + ring light"],
   magnification:"8x–50x (6.3:1 zoom; standard C-W10x/22mm eyepieces; up to 200x with 2x aux obj + 20x eyepieces)",
   objectives:"Fixed Greenough twin-zoom body 0.8x–5.0x; click-stops at 1x intervals; 0.5x/0.7x/1.5x/2x auxiliary objectives available",
   eyepieces:"C-W10x/22mm standard (also 15x, 20x, 30x available); 45° eyetube inclination",
   stage:"Universal flat base; boom stand option; transmitted light stand option; 115mm WD with 1x objective",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Electronics","Entomology","Education","Natural history","Semiconductors","Geology"],
   noteworthy:"The SMZ645 is Nikon’s workhorse mid-range stereo. 6.3:1 zoom with click-stops at 1x intervals for reliable magnification recall. Patented triple-A design: Airtight (JIS Type 1), Anti-mold, Anti-electrostatic discharge. 115mm working distance. Optional EPI fluorescence (P-FLA). ESD stage plate option. 45° eyetube inclination. Owner’s note: SN 0208-082, equipped with C-W10x/22mm oculars and dual illumination (above and below stage).",
   accessories:{
     auxiliary_objectives:[
       {name:"G-AL 0.5x",code:"MMH31055",note:"0.5x auxiliary lens. Increases working distance; magnification range 4x–25x (with standard 10x eyepieces). Marked ‘G-AL 0.5x’ on barrel."},
       {name:"G-AL 0.7x",code:"MMH31075",note:"0.7x auxiliary lens. Intermediate working distance increase; magnification range 5.6x–35x. Marked ‘G-AL 0.7x’ on barrel."},
       {name:"G-AL 1.5x",code:"MMH31155",note:"1.5x auxiliary lens. Increases magnification range to 12x–75x; reduced working distance. Marked ‘G-AL 1.5x’ on barrel."},
       {name:"G-AL 2.0x",code:"MMH31205",note:"2.0x auxiliary lens. Highest magnification range 16x–100x with 10x eyepieces; pairs with 20x eyepieces for up to 200x. Reduced working distance (~34mm). Marked ‘G-AL 2.0x’ on barrel."}
     ],
     eyepieces:[
       {name:"C-W10x/22mm (standard)",code:"MBH10220",note:"Included with your SMZ645. Your current oculars."},
       {name:"C-W15x/16mm",code:"MBH15160",note:"1.5x magnification increase without changing objective."},
       {name:"C-W20x/12.5mm",code:"MBH20125",note:"High power; pairs with 2x auxiliary for max ~200x."}
     ],
     stands:[
       {name:"Universal flat base (P-FBD)",note:"Standard — included."},
       {name:"Transmitted light stand (P-TBD)",note:"Genuine Nikon OEM below-stage illumination option. Your unit does NOT use this — it's fitted with a confirmed third-party dual-illumination base instead (G4 6V/15W halogen top + PL-5W/G23 compact fluorescent bottom, 120V/60Hz, 2A fuse)."},
       {name:"Boom stand (P-BSD)",note:"Arm mount; useful for large or irregularly shaped specimens."}
     ],
     cameras:[
       {name:"C-Mount adapter (P-VC)",note:"Allows any C-mount camera to attach to trinocular port."},
       {name:"0.5x C-mount reducer",note:"Reduces magnification at sensor to better fill frame."}
     ]
   },
   oem_source:null},

  {id:"nikon-smz660",name:"SMZ660",series:"SMZ",type:"stereo",subtype:"zoom stereo (Greenough, 60 degree)",
   introduced:2001,discontinued:false,price_tier:"mid",
   price_new:"$1,200–$3,000",price_used:"$300–$900",
   illumination:["Halogen (ring + external gooseneck)","Optional transmitted base","Optional EPI fluorescence"],
   magnification:"8x–50x (6.3:1 zoom; standard 10x/22mm eyepieces)",
   objectives:"Fixed Greenough twin-zoom body 0.8x–5.0x; click-stops; same auxiliary as SMZ645",
   eyepieces:"C-W10x/22mm standard; 60 degree eyetube inclination (vs 45 on SMZ645)",stage:"Universal flat base; boom stand; 115mm WD",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Electronics","Education","Natural history","Documentation"],
   noteworthy:"The SMZ660 is the 60-degree-inclination companion to the SMZ645, sharing the same optical body and zoom system but with a more upright tube angle preferred for extended observation sessions. Identical triple-A design, click-stops, and accessory compatibility. Trinocular port makes this model popular for digital camera documentation.",
   oem_source:null},

  {id:"nikon-smz1000",name:"SMZ1000",series:"SMZ",type:"stereo",subtype:"research zoom stereo",
   introduced:2001,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$800–$3,000",
   illumination:["Halogen (ring + transmitted base)","Optional fluorescence illuminator"],
   magnification:"8x–80x (10:1 zoom; 10x eyepieces, 1x Plan Apo obj; up to 480x with full accessories)",
   objectives:"Plan Apo 1x (NA 0.1, 300 lp/mm resolution); 0.5x/0.75x/1.5x/2x parfocal objectives",
   eyepieces:"C-W10x/23mm standard; binocular or trinocular",stage:"Large format; transmitted light stand",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Developmental biology","Fluorescence","Dissection","Neuroscience","Model organisms"],
   noteworthy:"The SMZ1000 bridges the gap between the SMZ645 and the flagship SMZ1500. 10:1 zoom with Plan Apo 1x objective (NA 0.1, 300 lp/mm). ED (Extra-low Dispersion) glass objectives control chromatic aberration. Click-stop zoom. Full fluorescence capability. Represents good value for labs needing research-grade optics without the SMZ1500 price tag. Widely used in developmental biology and model organism labs.",
   oem_source:null},

  {id:"nikon-smz445",name:"SMZ445 / SMZ460",series:"SMZ",type:"stereo",subtype:"entry zoom stereo (Porro prism)",
   introduced:2003,discontinued:false,price_tier:"budget",
   price_new:"$600–$1,400",price_used:"$150–$450",
   illumination:["LED (diascopic and episcopic combined stand)","Optional external illuminators"],
   magnification:"SMZ445: 8x–35x (4.4:1 zoom; 10x eyepieces); SMZ460: 7x–30x (4.3:1 zoom; 60 degree)",
   objectives:"Porro prism twin-zoom body; SMZ445: 0.8x–3.5x; SMZ460: 0.7x–3.0x; AL0.5x/AL0.7x auxiliary",
   eyepieces:"SM 10xB/21mm standard (also 15xB, 20xB); SMZ445 = 45 deg, SMZ460 = 60 deg",stage:"Flat base; 100mm WD; C-LEDS combined stand",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Education","Introductory biology","Dissection","Natural history","Hobbyist","Basic QC"],
   noteworthy:"Nikon most affordable stereos — compact, lightweight, with all-new Porro prism design. The C-LEDS stand integrates both diascopic and episcopic LED illumination with independently adjustable intensities in one base. Anti-mold coating on optical surfaces. 100mm working distance. SMZ445 = 4.4:1 zoom at 45 degrees; SMZ460 = 4.3:1 zoom at 60 degrees. Excellent entry-level stereo for schools and casual users. Porro prism enables a particularly compact and light body.",
   oem_source:null}

]});
