// ════════════════════════════════════════════════════
// BIG FOUR — OLYMPUS / EVIDENT
// ════════════════════════════════════════════════════
DB.companies.push({id:"olympus",name:"Evident Scientific (Olympus)",shortName:"Evident/Olympus",flag:"🇯🇵",country:"Japan",
 founded:1919,status:"active",featured:true,hq:"Tokyo, Japan",
 categories:["compound","stereo"],
 overview:"Founded October 12, 1919 as Takachiho Seisakusho (Takachiho Manufacturing) in Tokyo by Takeshi Yamashita, initially producing microscopes and thermometers. The Olympus trademark was registered in 1921; the company became Olympus Optical Co., Ltd. in 1949 and Olympus Corporation in 2003. Key corporate event: in 1987 Olympus acquired KeyMed (Medical and Industrial Equipment Ltd., UK), its primary European distributor, bringing endoscope and microscope distribution in-house across Europe. The scientific solutions division was spun off as Evident Corporation (April 2022) and sold to Bain Capital Private Equity for ~¥427.6 billion (~$3.1B) in April 2023. Microscopes now trade under the Evident brand with full product continuity. Optical system milestones: UIS (Universal Infinity System, 1987) — Olympus’s first infinity optical system — and UIS2 (introduced with the BX50/IX70 era), which remains current in the BX43, BX53, IX83, and FLUOVIEW confocal series. Key instrument families: the BH-2 (dominant research upright of the 1980s across Japan and Asia-Pacific); the CK2/CKX series inverted tissue culture microscopes; the IX-70/71/81/83 research inverted series widely used for IVF, live-cell imaging, and confocal coupling; and the BX upright clinical/research series in use worldwide. Olympus / Evident is recognized for outstanding ergonomic design, the FLUOVIEW confocal series, and the SpinSR spinning disk super-resolution system.",
 oem:{acquiredBy:"Bain Capital (Evident Scientific, 2022 spin-off from Olympus Corp.)",acquired:[],makesFor:[],madeBy:[],notes:"In 2022, Olympus's scientific solutions division was separated and rebranded as Evident Scientific. Olympus Corporation itself (endoscopy, cameras) is unrelated."},
 models:[
  // ── CURRENT ──
  {id:"olympus-bx53",name:"BX53",series:"BX",type:"compound",subtype:"research upright",
   introduced:2012,discontinued:false,price_tier:"mid",
   price_new:"$5,000–$15,000",price_used:"$1,500–$5,500",
   illumination:["LED (TH4-200)","Metal Halide (fluorescence)"],magnification:"20x–1000x",
   objectives:"UPlan FL N / UPlanSApo series",eyepieces:"10x/22mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"cellSens Standard",
   applications:["Pathology","Histology","Materials science","Research","Multi-contrast"],
   noteworthy:"Modular design accepts polarization, darkfield, DIC, and fluorescence. Accepts U-SRG3 motorized stage. Widely used in pathology departments worldwide.",
   oem_source:null},
  {id:"olympus-bx63",name:"BX63",series:"BX",type:"compound",subtype:"automated upright",
   introduced:2012,discontinued:false,price_tier:"premium",
   price_new:"$20,000–$50,000",price_used:"$5,000–$18,000",
   illumination:["LED (TH4-200)","Metal Halide","Laser (option)"],magnification:"20x–1000x",
   objectives:"UPlanSApo / UPlan FL N series",eyepieces:"10x/22mm",
   stage:"Motorized encoded 120×80mm",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,software:"cellSens Dimension",
   applications:["Tissue sections","High-content imaging","Multiplex immunofluorescence","Digital pathology"],
   noteworthy:"Fully motorized for tiling, Z-stacking, and multi-position workflows. Used for automated histology and multiplex immunofluorescence workflows (CODEX, OPAL panels).",
   oem_source:null},
  {id:"olympus-ix83",name:"IX83",series:"IX",type:"compound",subtype:"inverted modular",
   introduced:2013,discontinued:false,price_tier:"premium",
   price_new:"$25,000–$65,000",price_used:"$6,000–$22,000",
   illumination:["LED (SPECTRA X / pE)","Metal Halide","Laser"],magnification:"40x–1000x",
   objectives:"UPlanSApo / TIRF PLAPO series",eyepieces:"10x/22mm",
   stage:"Motorized 130×85mm + piezo Z",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"cellSens Dimension",
   applications:["Live cell","TIRF","Single molecule","Spinning disk confocal","Drug discovery"],
   noteworthy:"Modular pyramid design gives optical access without moving the sample. Deck system for mounting scan heads (Yokogawa CSU). Industry-leading flexibility for high-end live cell imaging platforms.",
   oem_source:null},
  {id:"olympus-szx16",name:"SZX16",series:"SZX",type:"stereo",subtype:"research zoom stereo",
   introduced:2006,discontinued:false,price_tier:"premium",
   price_new:"$15,000–$40,000",price_used:"$4,000–$14,000",
   illumination:["LED","Metal Halide (fluorescence)"],
   magnification:"7x–115x (10x ep, 1x obj; up to 230x with 2x obj)",
   objectives:"SDF PlanApo 0.5x/1.0x/1.6x/2.0x (parfocal)",eyepieces:"10x/22mm",
   stage:"Large format 210×240mm",fluorescence:true,phase_contrast:false,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"cellSens Standard",
   applications:["Developmental biology","Zebrafish","C. elegans","Drosophila","GFP/RFP screening"],
   noteworthy:"16.4:1 zoom ratio (zoom body 0.7x–11.5x). Max NA 0.30, resolution to 900 lp/mm. Widely used for GFP/RFP screening in zebrafish, C. elegans, and Drosophila.",
   oem_source:null},
  // ── HISTORICAL / COLLECTIBLE ──
  {id:"olympus-bh2",name:"BH-2",series:"BH",type:"compound",subtype:"research upright",
   introduced:1980,discontinued:1993,price_tier:"mid",
   price_new:null,price_used:"$200–$750",
   illumination:["Halogen 6V/30W (BHT)","Halogen 12V/100W (BHS)","HBO 50W fluorescence (optional)"],
   magnification:"40x–1000x standard; 20x–1000x with 2x/4x objectives",
   objectives:"SPlan / SPlanApo LB (Long Barrel) — 45mm parfocal, 160mm tube, RMS thread",
   eyepieces:"WHK 10x/20L, SWHK 10x/23L, CWHK 10x/18L (‘L’ suffix = Long Barrel series)",
   stage:"Mechanical large format 125×90mm; optional rotating stage; optional vernier stage",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Clinical pathology","Fluorescence","Neuroscience","Histology","Polarization","DIC","Photomicrography"],
   noteworthy:"The BH-2 (BHS and BHT models) was the dominant research upright of the 1980s in Japan and Asia-Pacific. Extremely robust construction. The SPlanApo objectives were outstanding for their era. Still widely used in Asia. One of the most durable microscopes ever made. Very affordable on the used market. Owner’s note: SN 217796, equipped with dual teaching head.",
   objective_guide:{
     warning:"CRITICAL COMPATIBILITY: The BH-2 uses RMS thread (20.32mm, 0.706 pitch) — the same as most older microscopes — BUT the parfocal distance is 45mm (‘Long Barrel’ / ‘LB’), NOT the standard 36.65mm. A generic or non-BH-2 objective will screw in but be too short to reach focus. This is an extremely common eBay mistake.",
     tube_length:"160mm finite. Do NOT use objectives labeled ‘∞’ (infinity-corrected).",
     thread:"RMS — 20.32mm diameter, 0.706mm pitch.",
     parfocal:"45mm — critical requirement. Older Olympus BH (pre-BH-2) objectives are 36.65mm and will NOT work correctly.",
     compatible_series:[
       {name:"DPlan Achromat",code:"A / DPlan",note:"Most affordable BH-2 objective. Excellent for routine brightfield. Very common on eBay. Available 4x, 10x, 20x, 40x, 100x oil. Confirm ‘160/0.17’ on barrel."},
       {name:"SPlan Semi-Plan Fluorite",code:"SPlan",note:"Higher NA and flatter field than DPlan. Superior for phase contrast and fluorescence. The recommended upgrade for your scope. Available 4x–100x."},
       {name:"SPlanApo Plan Apochromat",code:"SPlanApo",note:"Top of the BH-2 biological line. Superb color correction. Expensive on used market but outstanding optical quality."},
       {name:"MSPlan Metallurgical",code:"MSPlan",note:"For reflected-light metallurgy. Marked ‘/0’ — no coverslip. Not for standard biological slides."},
       {name:"NeoDPlan / NeoSPlan (IC series)",code:"NeoDPlan / NeoSPlan",note:"Infinity-corrected, marked ‘f=180’. Require the BH2-UMA illuminator. NOT drop-in compatible with standard BH-2 biological setups."}
     ],
     incompatible:[
       "Any objective labeled ‘∞’ (infinity-corrected) — tube length mismatch",
       "Standard generic RMS objectives with 36.65mm parfocal — will screw in but be too short to focus (the eBay 40x problem)",
       "Olympus BH (pre-BH-2) objectives with 36.65mm or 42.5mm parfocal",
       "Olympus UIS/UIS2 objectives (BX-series, labeled ‘∞/0.17’) — infinity corrected",
       "Nikon CFI objectives — different thread standard (M25)",
       "Leica objectives — different thread (M25)"
     ],
     buying_tips:"Search eBay for ‘Olympus SPlan BH2’ or ‘Olympus DPlan LB’. Confirm the listing shows tube length ‘160’ and parfocal ‘45mm’. The letters ‘LB’ on the barrel confirm Long Barrel compatibility. Avoid listings that say ‘RMS’ without specifying tube length.",
     eyepiece_compatibility:"Use eyepieces with ‘L’ in the designation (WHK 10x/20L, SWHK 10x/23L). For photo documentation, use NFK photo eyepieces (NFK 2.5x for full-frame digital)."
   },
   accessories:{
     stands:["BHS — standard halogen illuminated stand (most common)","BHT — high-current halogen stand with stabilized illumination","BHSP — polarizing configuration with strain-free components"],
     heads:["BH2-B binocular head (30° incline, most common)","BH2-T trinocular head (for camera attachment)","BH2-TR trinocular rotating head","BH2-SWTR30 superwide trinocular (desirable, expensive)"],
     condensers:["BH2-CD Abbe condenser NA 1.25 (standard, very common)","BH2-SC swing-top condenser (best for low-power 2x–4x objectives)","BH2-AAC Aplanatic-achromatic condenser (best for oil immersion)","BH2-ULC ultra-low condenser for 1x–2x objectives"],
     fluorescence:["BH2-EPI episcopic illuminator (for fluorescence and DIC)","Standard Olympus filter cubes: B (FITC), G (TRITC), U (DAPI)","HBO 50W or 100W mercury lamp housing"],
     cameras:["NFK photo eyepieces required for 35mm or DSLR attachment","PM-PBH trinocular photo attachment","T-mount adapters for Canon EOS, Nikon F"],
     teaching:["BH2-DU dual teaching head — two-observer simultaneous use (owner’s unit is so equipped)"]
   },
   oem_source:null},
  {id:"olympus-ch",name:"CH / CHA / CHB / CH30",series:"CH",type:"compound",subtype:"student / clinical upright (finite, pre-CH2)",
   introduced:1974,discontinued:1985,price_tier:"budget",price_new:null,price_used:"$60–$250",
   illumination:["Sub-stage mirror (CH) or built-in 6V 15W halogen (CHA, CHB)","CH30: 6V 20W halogen"],
   magnification:"40x–1000x",
   objectives:"160mm finite, RMS thread, 36.65mm parfocal (SHORT barrel — NOT Long Barrel). IMPORTANT: unlike the BH-2 era, the original CH series uses standard 36.65mm parfocal objectives.",
   eyepieces:"H 10x/18mm standard (23.2mm tube)",
   stage:"Mechanical or fixed stage; Abbe condenser",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Clinical routine","Hematology","Veterinary"],
   noteworthy:"Original CH series predates the CH-2 and uses 36.65mm parfocal (short barrel), NOT the Long Barrel (LB) 45mm of the BH-2 era. CH = mirror-base; CHA = built-in illumination; CHB = clinical version; CH30 = later improved model. Objectives from the DPlan LB (BH-2 era) will NOT work on these scopes.",
   oem_source:null},

{id:"olympus-ch2",name:"CH-2",series:"CH",type:"compound",subtype:"student / clinical",
   introduced:1986,discontinued:1997,price_tier:"budget",
   price_new:null,price_used:"$100–$320",
   illumination:["Halogen 6V/15W"],magnification:"40x–1000x",
   objectives:"CHAchromat 4x/10x/40x/100x",eyepieces:"10x/18mm",
   stage:"Mechanical",fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Clinical routine","Basic biology","Hematology"],
   noteworthy:"The CH-2 was Olympus's dominant student and clinical microscope of the late 1980s–90s. Sold in enormous quantities to schools, hospitals, and clinics worldwide. Extremely durable and simple to service. Very abundant on the used market at very low prices.",
   oem_source:null},
  {id:"olympus-imt2",name:"IMT-2",series:"IMT",type:"compound",subtype:"inverted routine",
   introduced:1988,discontinued:1996,price_tier:"mid",
   price_new:null,price_used:"$200–$650",
   illumination:["Halogen 6V/30W","HBO fluorescence (option)"],magnification:"40x–400x",
   objectives:"SPlan LWD achromat 4x/10x/20x/40x",eyepieces:"10x/20mm",
   stage:"Mechanical 190×140mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell culture","Tissue culture","IVF","Basic cell biology"],
   noteworthy:"Olympus's standard inverted scope of the late 1980s–90s. Used in IVF clinics, hospitals, and cell biology labs worldwide. Extremely common on the used market. Fluorescence option available. Good parts availability.",
   oem_source:null},
  {id:"olympus-bx40",name:"BX40",series:"BX",type:"compound",subtype:"clinical / research upright",
   introduced:1993,discontinued:2002,price_tier:"mid",
   price_new:null,price_used:"$400–$1,300",
   illumination:["Halogen 12V/100W","HBO fluorescence"],magnification:"40x–1000x",
   objectives:"UPlan Achromat / UPlan Fluorite (first UIS generation)",eyepieces:"10x/20mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical pathology","Research","Histology","Fluorescence","Education"],
   noteworthy:"The BX40 introduced the UIS (Universal Infinity System) optical design, which forms the basis of all modern Olympus/Evident objectives. UPlan objectives are still compatible with current BX53/BX63 systems. Good used value and excellent optical quality.",
   oem_source:null},
  {id:"olympus-bx50",name:"BX50",series:"BX",type:"compound",subtype:"research upright",
   introduced:1993,discontinued:2003,price_tier:"mid",
   price_new:null,price_used:"$600–$2,100",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence","Metal halide option"],
   magnification:"40x–1000x",objectives:"UPlan Fluorite / UPlanApo (UIS system)",eyepieces:"10x/22mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","DIC","Fluorescence","Neuroscience","Materials","Histology"],
   noteworthy:"The BX50 was Olympus's top research upright of the 1990s. Full DIC capability with UIS optics. The UPlanApo objectives are still competitive with modern plan apochromats. UIS objectives are compatible with current BX53/BX63. A highly recommended used purchase.",
   oem_source:null},
  {id:"olympus-ix50",name:"IX50",series:"IX",type:"compound",subtype:"inverted research",
   introduced:1994,discontinued:2001,price_tier:"mid",
   price_new:null,price_used:"$400–$1,500",
   illumination:["Halogen","HBO fluorescence"],magnification:"40x–600x",
   objectives:"UPlan LWD achromat / LWD Fluorite",eyepieces:"10x/22mm",
   stage:"Mechanical 225×175mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell culture","Fluorescence","Timelapse (film/early digital)","Basic live cell"],
   noteworthy:"The IX50 introduced the IX (Infinity + X) inverted platform. Mid-tier version of the IX line, offering UIS fluorescence capability at lower cost. Still used in IVF and cell culture labs. Good used market availability.",
   oem_source:null},
  {id:"olympus-ix70",name:"IX70",series:"IX",type:"compound",subtype:"inverted research (high-end)",
   introduced:1995,discontinued:2005,price_tier:"premium",
   price_new:null,price_used:"$1,000–$3,500",
   illumination:["Halogen 12V/100W","HBO 100W fluorescence","Metal halide option"],
   magnification:"40x–1000x",objectives:"UPlanApo / UPlan Fluorite LWD",eyepieces:"10x/22mm",
   stage:"Mechanical / motorized option",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Live cell","Fluorescence","DIC","FRET (early)","Cell biology","Drug discovery"],
   noteworthy:"Top-of-the-line Olympus inverted of the late 1990s–2000s. Full DIC with UPlanApo objectives. Predecessor to the IX71/IX81. Excellent used value for a capable fluorescence inverted. UIS objectives fully compatible with current IX83 hardware.",
   oem_source:null},
  {id:"olympus-szh10",name:"SZH10",series:"SZH",type:"stereo",subtype:"research zoom stereo",
   introduced:1987,discontinued:2000,price_tier:"premium",
   price_new:null,price_used:"$1,500–$4,800",
   illumination:["Halogen (ring + transmitted)","HBO fluorescence module"],
   magnification:"7x–175x (with 2.5x objective)",
   objectives:"0.5x/1.0x/1.6x/2.5x SDF planapochromat",eyepieces:"10x/22mm",
   stage:"Large format transmitted",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Fluorescence screening","Whole organism imaging","Dissection"],
   noteworthy:"The SZH10 was the top fluorescence-capable stereo of the late 1980s–90s. SDF planapochromatic objectives are still outstanding. Full fluorescence capability with HBO illuminator. Was used extensively for early GFP transgenic organism screening. Still in use in many labs.",
   oem_source:null},
  {id:"olympus-szx10",name:"SZX10",series:"SZX",type:"stereo",subtype:"research zoom stereo",
   introduced:2001,discontinued:2012,price_tier:"premium",
   price_new:null,price_used:"$2,000–$5,500",
   illumination:["LED","Metal Halide (fluorescence)"],
   magnification:"6.3x–90x (10x ep, 1x obj)",
   objectives:"SDF PlanApo 0.5x/1.0x/1.6x/2.0x (parfocal)",eyepieces:"10x/22mm",
   stage:"Large format 210×200mm",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Model organisms","Fluorescence screening","Dissection"],
   noteworthy:"The mid-tier SZX line scope. 10:1 zoom ratio with SDF planapochromatic optics. Full fluorescence capability. The SZX objectives (0.5x–2.0x) are parfocal and interchangeable between the SZX10 and SZX16. Very strong used market value.",
   oem_source:null},

{id:"olympus-bh",name:"BH",series:"BH",type:"compound",subtype:"research upright (pre-BH-2)",
   introduced:1974,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$150–$500",
   illumination:["Halogen 6V/20W","HBO fluorescence"],
   magnification:"40x–1000x (4x–100x SPlan objectives, 10x/18mm eyepieces)",
   objectives:"SPlan / SPlanApo (pre-UIS, 160mm, RMS thread; 36.65mm parfocal short-mount)",
   eyepieces:"10x/18mm; binocular; trinocular available",stage:"Mechanical large format; optional rotating stage",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","Phase contrast","DIC","Photomicrography"],
   noteworthy:"The original BH (1974) introduced coaxial stage controls and the Y-shaped stand design that defined Olympus compound microscopes for 20 years. First Olympus scope with both horizontal and vertical stage movement via coaxial handles. SPlanApo objectives of excellent quality. Uses the older 36.65mm parfocal RMS short-mount objectives (not the later BH-2 long-barrel LB series). The BH-2 (1980) was a significant optical upgrade with the new LB objective line.",
   oem_source:null},

  {id:"olympus-ckx31",name:"CKX31 / CKX41",series:"CKX",type:"compound",subtype:"inverted routine / tissue culture (UIS2)",
   introduced:2003,discontinued:2015,price_tier:"mid",price_new:"$2,000–$6,000",price_used:"$400–$1,500",
   illumination:["Built-in transmitted halogen (sub-stage)","Variable intensity"],
   magnification:"20x–400x (4x–40x objectives typical)",
   objectives:"UIS2 infinity-corrected (M25 thread). LWD objectives for culture dishes and flasks.",
   eyepieces:"WHB 10x/20mm; 30° incline; ergonomic low-positioned stage",
   stage:"Fixed stage, focusing nosepiece; large aperture for T-25 to T-175 flasks",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Tissue culture","Cell biology","IVF","Microbiology","Live cell imaging"],
   noteworthy:"Mid-tier Olympus inverted for routine tissue culture. CKX41 adds condenser aperture diaphragm and better phase contrast optics. Very common in hospital IVF labs. Uses UIS2 M25 objectives same as CX and BX series.",
   oem_source:null},

{id:"olympus-ckx22",name:"CKX22",series:"CKX",type:"compound",subtype:"inverted student / tissue culture (basic)",
   introduced:2003,discontinued:2020,price_tier:"budget",price_new:"$800–$2,000",price_used:"$150–$500",
   illumination:["Built-in 6V/20W halogen transmitted","Fixed intensity"],
   magnification:"40x–400x (4x–40x objectives typical)",
   objectives:"UIS2 infinity-corrected (M25 thread). LCACH LWD achromat series.",
   eyepieces:"WHB 10x/20mm; 30° binocular",
   stage:"Fixed stage; no full XY stage",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:false,software:"—",
   applications:["Teaching","Tissue culture routine","IVF monitoring","Microbiology education"],
   noteworthy:"Simplified entry-level inverted below the CKX31/CKX41. No camera port, no mechanical XY stage, no variable illumination. Phase contrast only. Common in teaching labs and small clinics. Step up to CKX41 for documentation and IVF work.",
   oem_source:null},

{id:"olympus-ck2",name:"CK2 / CK40",series:"CK",type:"compound",subtype:"inverted student / clinical",
   introduced:1976,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$100–$350",
   illumination:["Halogen 6V/15W"],
   magnification:"40x–400x (4x–40x LWD objectives, 10x eyepieces)",
   objectives:"LWD Phase Achromat 4x/10x/20x/40x (160mm, long working distance)",
   eyepieces:"10x binocular",stage:"Mechanical 190x140mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Cell culture QC","Tissue culture","IVF","Student cell biology","Clinical cytology"],
   noteworthy:"The CK2 and its successor CK40 were Olympus's entry inverted scopes of the 1970s–1990s, found in every cell culture and IVF lab using Olympus equipment. The CK40 (c.1988) improved ergonomics and illumination. Replaced by the IX50 in the mid-1990s. Extremely common on the used market — one of the most abundant second-hand inverted scopes available.",
   oem_source:null},

  {id:"olympus-bx43",name:"BX43",series:"BX",type:"compound",subtype:"clinical / research upright (UIS2, LED)",
   introduced:2012,discontinued:false,price_tier:"mid",price_new:"$4,000–$10,000",price_used:"$2,000–$5,000",
   illumination:["LED (100,000-hour lifetime, no warm-up)","Pre-centered, no alignment required","Optional fluorescence (BX3-RFAA filter turret)"],
   magnification:"40x–2000x (UIS2 objectives); wide-field 22mm FOV",
   objectives:"UIS2 infinity-corrected, 180mm tube lens, M25 thread. Compatible with BX41/BX51/BX53 objectives.",
   eyepieces:"WHSZ 10x/22mm standard (FN22)",
   stage:"Rackless mechanical stage; universal condenser with DIC prism slot",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,motorized:false,inverted:false,camera_port:true,software:"cellSens (optional)",
   applications:["Clinical pathology","Hematology","Histology","Research","Education"],
   noteworthy:"LED-equipped successor to the BX41 and current Olympus/Evident standard clinical upright. LED requires no warm-up and eliminates bulb replacement. Part of the current BX3 generation alongside the BX53 and BX63.",
   oem_source:null},

{id:"olympus-bx53",name:"BX53",series:"BX",type:"compound",subtype:"research upright (UIS2, LED, motorized option)",
   introduced:2012,discontinued:false,price_tier:"mid",price_new:"$8,000–$25,000",price_used:"$4,000–$12,000",
   illumination:["LED transmitted (standard)","Optional motorized fluorescence turret","Optional laser coupling"],
   magnification:"40x–2000x; wide-field FN22",
   objectives:"UIS2 infinity-corrected, 180mm tube lens, M25 thread.",
   eyepieces:"WHSZ 10x/22mm; FN22 field number",
   stage:"Motorized stage option; encoded XY and Z; universal condenser",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,motorized:true,inverted:false,camera_port:true,software:"cellSens",
   applications:["Research","Neuroscience","Materials science","Fluorescence","DIC","Confocal coupling","Live imaging"],
   noteworthy:"Current research-grade BX flagship, replacing the BX51. LED illumination standard. Available motorized (BX53F/BX53-P) and manual configurations. Designed for integration with confocal scanners and super-resolution modules.",
   oem_source:null},

{id:"olympus-bx41",name:"BX41",series:"BX",type:"compound",subtype:"clinical / research upright (UIS2)",
   introduced:1997,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$600–$2,500",
   illumination:["Halogen 6V/30W","HBO fluorescence (optional)"],
   magnification:"40x–1000x (4x–100x UPlan FL N objectives, 10x/20mm eyepieces)",
   objectives:"UPlan FL N / UPlan Achromat (UIS2, infinity corrected)",
   eyepieces:"10x/20mm; binocular 30°; trinocular available",stage:"Mechanical 130x85mm",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"cellSens Standard",
   applications:["Clinical pathology","Histology","Education","Routine research","Hematology"],
   noteworthy:"Olympus's primary clinical/routine upright of the late 1990s–2000s. UIS2 optical system. Simpler and less expensive than the BX51 — no DIC capability. Very widely distributed in hospitals, veterinary clinics, and university teaching labs worldwide.",
   oem_source:null},

  {id:"olympus-bx51",name:"BX51",series:"BX",type:"compound",subtype:"research upright (UIS2, full DIC)",
   introduced:1997,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$900–$3,500",
   illumination:["Halogen 12V/100W","Metal halide fluorescence","HBO option"],
   magnification:"40x–1000x (4x–100x UPlanSApo objectives, 10x/22mm eyepieces)",
   objectives:"UPlanSApo / UPlanFLN (UIS2, infinity corrected; full DIC compatible)",
   eyepieces:"10x/22mm; binocular 30°; trinocular",stage:"Mechanical; optional U-SRG3 motorized",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"cellSens Standard",
   applications:["Research","DIC imaging","Fluorescence","Neuroscience","Materials","Histology"],
   noteworthy:"The BX51 was Olympus's full research upright — the BX41 with DIC capability added. The UIS2 optical system with UPlanSApo objectives is still considered outstanding. Full Nomarski DIC. Wide range of motorization and imaging options. A classic research workhorse of the 2000s–2010s. UIS2 objectives are fully compatible with the current BX53/BX63 and IX83.",
   oem_source:null},

  {id:"olympus-ix71",name:"IX71",series:"IX",type:"compound",subtype:"inverted research (UIS2)",
   introduced:2002,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$800–$3,500",
   illumination:["Halogen 12V/100W","Metal halide fluorescence","Laser (TIRF option)"],
   magnification:"40x–1000x (4x–100x UPlanSApo LWD objectives, 10x/22mm eyepieces)",
   objectives:"UPlanSApo / TIRF PLAPO (UIS2, LWD, infinity corrected)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized 130x85mm + piezo Z",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,
   software:"cellSens",
   applications:["Live cell","Fluorescence","TIRF","Spinning disk confocal","Cell biology","Drug discovery"],
   noteworthy:"Replaced the IX70 as Olympus's primary inverted research platform. Modular pyramid design for optical access without moving the sample. TIRF capability with 1.45 NA objectives. Deck system for spinning disk scanheads (Yokogawa CSU). UIS2 objectives are compatible with the current IX83 platform.",
   oem_source:null},

  {id:"olympus-ix81",name:"IX81",series:"IX",type:"compound",subtype:"motorized inverted research (UIS2)",
   introduced:2002,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,200–$5,000",
   illumination:["Halogen 12V/100W","Metal halide / LED fluorescence","Laser (TIRF)"],
   magnification:"40x–1000x (4x–100x LWD objectives, 10x/22mm eyepieces)",
   objectives:"UPlanSApo / TIRF PLAPO 150x / APON TIRF 60x (1.45 NA)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized encoded 130x85mm + piezo Z",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,
   software:"cellSens Dimension",
   applications:["Live cell","TIRF","Multi-position timelapse","High-content screening","Drug discovery","Spinning disk confocal"],
   noteworthy:"The fully motorized companion to the IX71. Olympus's flagship automated inverted for the 2000s–2010s. Perfect Focus System (PFS) hardware autofocus for long-term live experiments. Wide range of motorization including objective turret, filter wheels, and shutters. Predecessor to the IX83.",
   oem_source:null},

  {id:"olympus-ix73",name:"IX73",series:"IX",type:"compound",subtype:"inverted modular (UIS2, updated)",
   introduced:2012,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$2,000–$7,000",
   illumination:["LED (transmitted)","Metal halide / LED fluorescence","Laser option"],
   magnification:"40x–1000x (4x–100x UIS2 objectives, 10x/22mm eyepieces)",
   objectives:"UPlanSApo / UPLSAPO / TIRF PLAPO (UIS2, infinity corrected)",
   eyepieces:"10x/22mm; binocular; trinocular",stage:"Motorized 130x85mm + piezo Z (optional)",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,
   software:"cellSens Dimension",
   applications:["Live cell","Timelapse","Fluorescence","Spinning disk confocal","Drug discovery"],
   noteworthy:"An intermediate-tier update between the IX71/81 and the current IX83. LED transmitted illumination standard. Simplified deck design retaining modular flexibility. Perfect Focus System 2 (PFS2). Largely replaced by the IX83 which offers wider motorization options.",
   oem_source:null},

  {id:"olympus-cx21",name:"CX21 / CX23",series:"CX",type:"compound",subtype:"education / clinical upright",
   introduced:2003,discontinued:false,price_tier:"budget",
   price_new:"$650–$1,400",price_used:"$100–$500",
   illumination:["Halogen 6V/20W","LED (CX23)"],
   magnification:"40x–1000x (4x–100x UPlan objectives, 10x/18mm eyepieces)",
   objectives:"CHAchromat / UPlan Achromat (UIS2 compatible)",
   eyepieces:"10x/18mm; binocular 30°",stage:"Mechanical",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Medical education","Clinical routine","Hematology","Basic biology","Veterinary"],
   noteworthy:"The CX21 and its successor CX23 (2015, with LED) are Olympus's long-running clinical/education uprights. Very compact and lightweight. One of the most widely sold educational microscopes globally, used in schools, medical colleges, and veterinary clinics across Asia, Europe, and the Americas.",
   oem_source:null},

  {id:"olympus-cx31",name:"CX31 / CX41",series:"CX",type:"compound",subtype:"clinical / research upright",
   introduced:2007,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$250–$900",
   illumination:["Halogen 6V/30W","LED (later versions)"],
   magnification:"40x–1000x (4x–100x UPlan FL N objectives, 10x/20mm eyepieces)",
   objectives:"UPlan FL N / UPlan Achromat (UIS2 infinity corrected)",
   eyepieces:"10x/20mm; binocular 30°; trinocular (CX41)",stage:"Mechanical 120x76mm",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"cellSens Entry",
   applications:["Clinical labs","Medical education","Hematology","Cytology","Basic research"],
   noteworthy:"The CX31 (standard) and CX41 (trinocular) were Olympus's mid-range clinical/routine uprights of the 2007–2015 era. UIS2 plan objectives. The CX41 trinocular is widely used with digital cameras for clinical documentation. Durable, ergonomic, and competitively priced versus the Nikon E200 and Zeiss Axiolab.",
   oem_source:null},

  {id:"olympus-sz61",name:"SZ61 / SZ51",series:"SZ",type:"stereo",subtype:"zoom stereo",
   introduced:2000,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$800",
   illumination:["Halogen ring + transmitted","LED upgrade available"],
   magnification:"7x–45x (6.7:1 zoom; standard 10x/22mm eyepieces)",
   objectives:"Fixed Greenough zoom body 0.7x–4.5x; 0.5x/2x auxiliary",
   eyepieces:"10x/22mm (SZ61); 10x/20mm (SZ51)",stage:"Flat base; transmitted light stand; boom arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Electronics","Education","Natural history"],
   noteworthy:"The SZ61 (research) and SZ51 (student) are the workhorses of Olympus's Greenough stereo line for the 2000s–2010s. ComfortView eyepieces reduce eye strain during extended viewing sessions. Very widely distributed in North American and Asian biology departments. The SZ61 trinocular variant is commonly paired with Olympus DP cameras for documentation.",
   oem_source:null},

  {id:"olympus-szx7",name:"SZX7",series:"SZX",type:"stereo",subtype:"research zoom stereo",
   introduced:2005,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$800–$3,800",
   illumination:["LED","Metal halide (fluorescence option)"],
   magnification:"7x–90x (10x eyepieces, 1x obj; 8:1 zoom; up to 160x with 2x obj)",
   objectives:"SDF PlanApo 0.5x/1.0x/1.6x/2.0x (parfocal, shared with SZX10/SZX16)",
   eyepieces:"10x/22mm; binocular or trinocular",stage:"Large format; transmitted light base",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"cellSens",
   applications:["Developmental biology","Model organisms","Fluorescence screening","Dissection","QC"],
   noteworthy:"Entry point of Olympus's premium SZX research stereo line. 8:1 zoom. SDF PlanApo objectives are parfocal and interchangeable across the entire SZX series (SZX7/SZX10/SZX16) — a major advantage for labs that may later upgrade. Full fluorescence capability via the same illuminator used on the SZX10/16.",
   oem_source:null}
,

{id:"olympus-sz30",name:"SZ30 / SZ3060",series:"SZ",type:"stereo",subtype:"zoom stereo (Greenough, entry)",
   introduced:1982,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$100–$400",
   illumination:["Halogen (incident)","Optional transmitted base"],
   magnification:"9x–40x (4.4:1 zoom; 10x eyepieces; body zoom 0.9x–4x)",
   objectives:"Fixed Greenough zoom body 0.9x–4.0x; 110AL auxiliary objectives available",
   eyepieces:"GSWH10x/22mm binocular 45 degree",stage:"Flat base (SZ-ST); transmitted base (SZ-STR); boom arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Education","Basic dissection","Natural history","Introductory biology"],
   noteworthy:"The SZ30 (SZ3060 = 60 degree variant) was the entry model in Olympus first-generation plastic-body SZ stereo series. 4.4:1 zoom. All SZ30/SZ40/SZ60/SZ11 models use 48mm x 0.75mm threads for supplementary objectives and share stands, illuminators, and photo tubes. Can be converted to trinocular via the SZ-TRU mirror unit.",
   oem_source:null},

  {id:"olympus-sz40",name:"SZ40 / SZ4045",series:"SZ",type:"stereo",subtype:"zoom stereo (Greenough, mid)",
   introduced:1984,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$150–$600",
   illumination:["Halogen (incident + optional coaxial SZ-CHI)","Optional transmitted base"],
   magnification:"6.7x–40x (6:1 zoom; 10x eyepieces; body zoom 0.67x–4x)",
   objectives:"Fixed Greenough zoom body 0.67x–4.0x; 110AL 0.25x–2x auxiliary; 110mm WD",
   eyepieces:"GSWH10x/22mm binocular 45 deg (SZ4045) or 60 deg (SZ4060)",stage:"Flat base; transmitted base; boom arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Education","Biology","Electronics","Natural history"],
   noteworthy:"The SZ40 is the mid-range 1980s SZ stereo. 6:1 zoom with 110mm working distance. Optional SZ-CHI coaxial episcopic illuminator (12V/100W) for surface inspection — uncommon at this price tier. SZ-TRU trinocular conversion available. ESD-protected version for semiconductor work. One of the most commonly found used Olympus stereos alongside the SZ60.",
   oem_source:null},

  {id:"olympus-sz60",name:"SZ60 / SZ6045",series:"SZ",type:"stereo",subtype:"zoom stereo (Greenough, high)",
   introduced:1984,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$750",
   illumination:["Halogen (incident + optional coaxial)","Optional transmitted base"],
   magnification:"10x–63x (6.3:1 zoom; 10x eyepieces; body zoom 1.0x–6.3x)",
   objectives:"Fixed Greenough zoom body 1.0x–6.3x; 110AL 0.25x–2x auxiliary; 73mm WD",
   eyepieces:"GSWH10x/22mm binocular 45 or 60 degree",stage:"Flat base; transmitted base; boom arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Dissection","QC inspection","Research","Electronics","Natural history","Semiconductor"],
   noteworthy:"The SZ60 (SZ6045) was upper-mid tier of the 1980s SZ series. 6.3:1 zoom reaching 63x with standard 10x eyepieces. Higher magnification than the SZ40 at cost of shorter working distance (73mm vs 110mm). Optional coaxial illuminator for surface inspection. Trinocular conversion via SZ-TRU. NFK photo eyepieces for photomicrography. Widely used in semiconductor inspection and research dissection labs.",
   oem_source:null},

  {id:"olympus-sz11",name:"SZ11 / SZ1145",series:"SZ",type:"stereo",subtype:"zoom stereo (Greenough, research)",
   introduced:1984,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$300–$1,200",
   illumination:["Halogen (incident + optional coaxial)","Optional transmitted base"],
   magnification:"18x–110x (6.1:1 zoom; 10x eyepieces; body zoom 1.8x–11x; up to 330x with accessories)",
   objectives:"Fixed Greenough zoom body 1.8x–11.0x; 110AL auxiliary; 63mm WD",
   eyepieces:"GSWH10x/22mm binocular 45 or 60 degree; trinocular (SZ1145TRPT)",stage:"Flat base; transmitted base; boom arm",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Semiconductor inspection","High-magnification QC","Electronics","Entomology"],
   noteworthy:"The SZ11 (SZ1145) was the top of the 1980s SZ series, reaching 110x with standard 10x eyepieces and 330x at maximum. 6.1:1 zoom ratio well above the SZ60. Optional coaxial illuminator. Trinocular version (SZ1145TRPT) with dedicated photo tube. Used extensively in semiconductor inspection and high-detail biological dissection. Succeeded by the SZH10 for research applications.",
   oem_source:null},

  {id:"olympus-szx9",name:"SZX9",series:"SZX",type:"stereo",subtype:"research zoom stereo (SZX series)",
   introduced:2000,discontinued:true,price_tier:"premium",
   price_new:null,price_used:"$1,200–$4,500",
   illumination:["LED or halogen (ring/transmitted)","Metal halide (fluorescence option)"],
   magnification:"9x–90x (9:1 zoom; 10x eyepieces, 1x PlanApo obj; up to 160x with 2x obj)",
   objectives:"SDF PlanApo 0.5x/1.0x/1.6x/2.0x (parfocal; interchangeable with SZX7, SZX10, SZX16)",
   eyepieces:"10x/22mm; binocular or trinocular",stage:"Large format; transmitted light base",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"cellSens",
   applications:["Research","Developmental biology","Model organisms","Fluorescence screening","Dissection"],
   noteworthy:"The SZX9 sits between the SZX7 (8:1) and SZX10 (10:1) in Olympus premium SZX research stereo series. 9:1 zoom. SDF PlanApo objectives are parfocal and fully interchangeable across all SZX models — a major advantage for labs that may later upgrade. Built-in aperture iris for depth of field control. Full fluorescence. Widely used in developmental biology labs.",
   oem_source:null}

]});
