// ════════════════════════════════════════════════════
// SWIFT OPTICAL INSTRUMENTS
// ════════════════════════════════════════════════════
DB.companies.push({id:"swift",name:"Swift Optical Instruments",shortName:"Swift",flag:"🇺🇸",country:"USA",
 founded:1926,status:"active",hq:"Corpus Christi, Texas, USA",
 categories:["compound","stereo"],
 overview:"Swift Optical Instruments, founded in 1926 and headquartered in Corpus Christi, Texas, is one of the longest-running American microscope companies and has supplied US K–12 and university teaching labs for nearly a century. Swift operates a deliberate two-tier model: the professional M-series and SM-series (sold exclusively through authorized dealers, all-metal construction, Plan optics, Motic-sourced components on many configurations) and the consumer SW/S-series (introduced 2019, sold direct via Amazon and swift.direct). The consumer line has become one of the top-selling beginner microscopes in the USA but is manufactured to a lower specification than the professional dealer line — an important distinction for buyers comparing prices online. The M17 series is particularly respected in US veterinary practice. Swift has a strong domestic reputation for customer service and warranty support, which differentiates it from pure-import brands in its price range.",
 oem:{acquiredBy:null,acquired:[],makesFor:[],madeBy:[],notes:"Swift’s 2019 consumer line (SW/S series) is manufactured in China to a consumer price point, distinct from the professional M-series. Some M-series models are Motic-sourced. The SW-series is sold primarily via Amazon; the M-series via authorized microscope dealers."},
 models:[
  {id:"swift-sw380t",name:"SW380T / SW380B",series:"SW",type:"compound",subtype:"student / hobbyist upright (finite)",
   introduced:2019,discontinued:false,price_tier:"budget",price_new:"$150–$280",price_used:"$80–$150",
   illumination:["LED sub-stage","Dimmer wheel"],
   magnification:"40x–2500x (4x/10x/40x/100x objectives, 10x + 25x eyepieces)",
   objectives:"DIN Achromat 4x, 10x, 40x (spring), 100x oil (spring); 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm and WF 25x; Siedentopf 30°; 360° rotating",
   stage:"Two-layer mechanical stage; coaxial coarse + fine focus; NA 1.25 Abbe condenser",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"SwiftCam software (Windows/Mac)",
   applications:["Home hobbyist","High school","Introductory college","Clinical basics"],
   noteworthy:"Most popular Swift product on Amazon and among the top-selling consumer microscopes in the USA. Good value for a beginner: achromatic objectives, mechanical stage, LED, camera port. Uses 160mm finite RMS optics — standard aftermarket objectives work fine. The SW350T/SW350B are smaller, less expensive siblings with slightly lower optical quality. Not to be confused with the professional Swift M-series.",
   oem_source:null},
  {id:"swift-sw400",name:"SW400",series:"SW",type:"compound",subtype:"student / prosumer upright (infinity)",
   introduced:2023,discontinued:false,price_tier:"budget",price_new:"$200–$350",price_used:null,
   illumination:["LED sub-stage","Dimmer wheel"],
   magnification:"40x–2500x (4x/10x/40x/100x objectives, 10x + 25x eyepieces)",
   objectives:"Infinity achromat 4x, 10x, 40x (spring), 100x oil (spring); infinity-corrected, RMS thread",
   eyepieces:"WF 10x/18mm and WF 25x; Siedentopf 30° trinocular",
   stage:"Two-layer mechanical stage; NA 1.25 Abbe condenser",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"SwiftCam software",
   applications:["Home hobbyist","High school","Introductory college"],
   noteworthy:"Swift’s infinity-corrected upgrade to the SW380, launched ~2023. The infinity system reduces distortion and makes inserting accessories easier. Still budget-tier build quality. RMS thread on infinity objectives — compatible with standard aftermarket objectives.",
   oem_source:null},
  {id:"swift-m3600",name:"M3600 Series",series:"M",type:"compound",subtype:"professional education upright",
   introduced:2010,discontinued:false,price_tier:"budget",price_new:"$350–$700",price_used:"$100–$300",
   illumination:["LED","Halogen option"],
   magnification:"40x–1000x (4x/10x/40x/100x objectives, 10x eyepieces)",
   objectives:"DIN Achromat or Plan Achromat options; 160mm finite, RMS thread",
   eyepieces:"WF 10x/18mm; binocular or trinocular Siedentopf",
   stage:"Two-layer mechanical stage; coarse + fine focus coaxial",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus (optional)",
   applications:["K–12 education","Introductory college","Clinical basics","Veterinary student"],
   noteworthy:"Swift’s flagship professional education compound microscope, sold through authorized dealers rather than Amazon. Substantially better build quality than the SW consumer line — all-metal construction, better focus mechanics, Plan Achromat optics available. Widely used in US high school and community college biology labs. Some configurations Motic-sourced.",
   oem_source:null},
  {id:"swift-m17",name:"M17 Series",series:"M",type:"compound",subtype:"professional clinical / veterinary upright",
   introduced:2008,discontinued:false,price_tier:"mid",price_new:"$500–$1,200",price_used:"$150–$500",
   illumination:["LED","Halogen option"],
   magnification:"40x–1000x; phase contrast available",
   objectives:"Infinity-corrected Plan Achromat series; RMS thread",
   eyepieces:"WF 10x/20mm; Siedentopf binocular or trinocular 30°",
   stage:"Mechanical; coaxial coarse + fine; achromatic condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"Motic Images Plus",
   applications:["Veterinary","Clinical lab","Community college","Research basics"],
   noteworthy:"Swift’s quality professional tier with infinity-corrected Plan optics and all-metal build. Popular in US veterinary practices. Motic optical components on most configurations. Good-value alternative to the AmScope B490 or Nikon E200 for professional clinical and veterinary use.",
   oem_source:null},
  {id:"swift-sm105",name:"SM105 / SM105-C",series:"SM",type:"stereo",subtype:"zoom stereo (Greenough, education)",
   introduced:2005,discontinued:false,price_tier:"budget",price_new:"$250–$550",price_used:"$80–$250",
   illumination:["LED incident + LED transmitted","Variable intensity; 5 light settings"],
   magnification:"10x–30x (3:1 zoom; 10x eyepieces)",
   objectives:"Fixed Greenough zoom body 1.0x–3.0x",
   eyepieces:"WF 10x; binocular; 45° incline",
   stage:"Large flat base with black/white reversible plate; 110mm WD",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Basic dissection","Natural history","Hobbyist","Coins and stamps"],
   noteworthy:"Swift’s best-selling stereo. The SM105-C adds a C-mount camera port. LED incident + transmitted with 5 preset combinations. 3:1 zoom ratio (10x–30x). Very commonly found in US high school biology labs and home use. Reversible black/white stage plate included.",
   oem_source:null},

  {id:"swift-s7",name:"S7 / S7-TP / S7-TGL Professional Stereo",series:"S7",type:"stereo",subtype:"zoom stereo (Greenough, professional)",
   introduced:2018,discontinued:false,price_tier:"budget",
   price_new:"$180–$450",price_used:"$80–$250",
   illumination:["56-bulb LED ring light (standard)","S7-TGL: dual LED gooseneck + transmitted LED","S7-TP: post/pillar stand with transmitted platform"],
   magnification:"7x–45x (6.4:1 zoom; 10x/WF eyepieces); up to 270x with 20x eyepieces + 3x auxiliary",
   objectives:"Greenough 0.7x–4.5x zoom; 0.5x/2x auxiliary objectives available; 100mm WD standard",
   eyepieces:"WF 10x/20mm; 45° incline; 360° rotating trinocular head; 54–75mm IPD",
   stage:"Boom arm stand (S7, S7-TGL) or pillar/post stand (S7-TP); black/white reversible plate; 76mm neck",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"SwiftCam software",
   applications:["Electronics repair","PCB rework","Gemology","Research","Engraving","Dissection"],
   noteworthy:"Swift flagship Greenough stereo. Three primary configurations: S7 (trinocular with 56-LED ring light on boom arm), S7-TP (trinocular with post/pillar stand and transmitted LED platform for transparent specimens), S7-TGL (trinocular with dual LED gooseneck arms + transmitted LED for directional lighting flexibility). All share the same 6.4:1 Greenough zoom body. 5-year warranty. Compatible with Swift auxiliary objectives (0.5x and 2x). The S7-T520 designation refers to the trinocular version with a 0.5x C-mount camera adapter included.",
   oem_source:null},

  {id:"swift-sw-series",name:"SW50 / SW100 Consumer Stereo",series:"SW",type:"stereo",subtype:"zoom stereo (Greenough, consumer)",
   introduced:2019,discontinued:false,price_tier:"budget",
   price_new:"$100–$250",price_used:"$40–$120",
   illumination:["LED incident (top)","SW100: + LED transmitted (bottom)","Variable intensity"],
   magnification:"SW50: 7.5x–45x (6:1 zoom); SW100: 10x–40x (4:1 zoom); 10x/WF eyepieces",
   objectives:"Greenough fixed zoom body; no auxiliary objectives on budget versions",
   eyepieces:"WF 10x; binocular; 45° incline",
   stage:"Integrated flat base; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Home hobbyist","Elementary education","Coin collecting","Stamps","Nature study"],
   noteworthy:"Swift entry consumer stereo line sold primarily via Amazon. SW50: single LED top illumination, 6:1 zoom. SW100: dual LED (top + bottom simultaneous), 4:1 zoom with transmitted platform. Sealed optics for dust resistance. Budget tier below the professional SM-series and S7 series. Non-interchangeable eyepieces on some configurations. Good starter stereo for home use. Part of Swift 2019 Amazon consumer push alongside the SW380 compound series.",
   oem_source:null},

  {id:"swift-s3-series",name:"S303 / S306S / S308 Step Stereo Series",series:"S3",type:"stereo",subtype:"step-zoom stereo (Greenough, educational)",
   introduced:2015,discontinued:false,price_tier:"budget",
   price_new:"$250–$600",price_used:"$80–$250",
   illumination:["LED incident + transmitted","Variable intensity"],
   magnification:"S303: 10x/20x/30x (3-step); S306S: 10x/20x/40x; S308: 10x/20x/40x with different optics; lever-switch magnification",
   objectives:"Greenough fixed step objectives; sealed body",
   eyepieces:"WF 10x; binocular; 45° incline",
   stage:"Flat base with black/white reversible plate and stage clips",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["K–12 education","Basic dissection","Invertebrate observation","Botany"],
   noteworthy:"Fixed step-zoom stereo series for educational and budget professional use. Step-zoom design (lever or knob switches between discrete magnifications) is simpler and more durable than continuous zoom mechanisms, making these well-suited for classroom environments. S303 is the most basic (3 steps: 10x/20x/30x); S306S adds a slip clutch zoom protection; S308 features updated optics. Popular in US high school biology labs as a durable, low-maintenance alternative to continuous zoom stereos.",
   oem_source:null},

  {id:"swift-mz-series",name:"MZ800 / MZ801 / M28Z / M29TZ / M30TZ Zoom Stereo",series:"MZ/M",type:"stereo",subtype:"zoom stereo (Greenough, prosumer)",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$250–$600",price_used:"$80–$300",
   illumination:["LED incident + transmitted (model dependent)","Gooseneck or ring light options"],
   magnification:"7x–45x standard (6.4:1 zoom; 10x eyepieces); varies by model",
   objectives:"Greenough zoom body; 0.5x/2x auxiliary objectives compatible; 76mm neck",
   eyepieces:"WF 10x/20mm; binocular or trinocular (T suffix); 45° incline; 360° rotating",
   stage:"Post stand or boom stand; black/white reversible plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"SwiftCam software",
   applications:["Dissection","Electronics","QC inspection","Education","Natural history"],
   noteworthy:"Swift prosumer zoom stereo family. MZ800 (binocular), MZ801 (trinocular): compact post-stand configuration with integrated LED. M28Z: earlier binocular zoom on basic stand. M29TZ: trinocular version of M28Z. M30TZ: trinocular with improved optics and transmitted platform, also sold as Motic Swift M30TZ (OEM). The M30TZ is the most capable in this group and shares design elements with the Motic SMZ-140 series. All use 76mm neck for stand accessory compatibility.",
   oem_source:"motic"},

  {id:"swift-stereo80",name:"Stereo 80 / SW50 Entry Stereo",series:"Stereo 80",type:"stereo",subtype:"zoom stereo (Greenough, entry-level)",
   introduced:2020,discontinued:false,price_tier:"budget",
   price_new:"$80–$160",price_used:"$30–$80",
   illumination:["LED single top incident","Some models: + transmitted LED"],
   magnification:"10x–40x (4:1 zoom); 10x/WF eyepieces",
   objectives:"Fixed Greenough zoom body; sealed",
   eyepieces:"WF 10x; binocular; 45° incline",
   stage:"Integrated flat base; reversible black/white plate",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Elementary school","Home hobbyist","Stamps and coins","Basic nature study"],
   noteworthy:"Swift very entry-level stereo line sold primarily via Amazon. The Stereo 80 and similar SW-designation models are true beginner stereos with sealed optics and simple LED illumination. Not compatible with auxiliary objectives. Minimal magnification range (10x–40x). Good as a first stereo microscope for children and hobbyists; the step up to the SM101/SM105 series provides significantly better optical quality and accessory compatibility.",
   oem_source:null},

  {id:"swift-m3-specialty",name:"M3-B (Micro-Macro) / M3-F (Forensic) Specialty Stereo",series:"M3",type:"stereo",subtype:"zoom stereo (Greenough, specialty)",
   introduced:2015,discontinued:false,price_tier:"mid",
   price_new:"$800–2,000",price_used:"$300–$800",
   illumination:["High-intensity LED ring + gooseneck combination","Forensic UV LED illumination (M3-F variant)","Variable intensity and positioning"],
   magnification:"7.5x–45x standard; extended range with macro stand configuration",
   objectives:"Greenough zoom body with large working distance macro stand; object-to-lens distance adjustable",
   eyepieces:"WF 10x/20mm; binocular or trinocular; 45° incline",
   stage:"Specialized copy/macro stand allowing both close-up stereo and wide-field macro photography",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"SwiftCam software",
   applications:["Forensic investigation","Document examination","Macro photography","Questioned document","Evidence examination"],
   noteworthy:"Specialty Swift stereos for non-standard applications. M3-B (Micro-Macro): mounted on an articulating copy stand allowing both traditional stereo microscopy and macro photography of large flat specimens (documents, currency, artwork) at controlled distances. M3-F (Forensic): configured with forensic UV illumination for document examination, fiber comparison, and evidence analysis. Both use the same Greenough zoom optical body as the S7 series but on specialized stands not used in routine laboratory work.",
   oem_source:null},

  {id:"swift-s41",name:"S41-20 / SM101 / SM102 Entry Professional Stereo",series:"SM/S41",type:"stereo",subtype:"zoom stereo (Greenough, entry professional)",
   introduced:2010,discontinued:false,price_tier:"budget",
   price_new:"$150–$350",price_used:"$60–$180",
   illumination:["LED incident + transmitted","Variable intensity"],
   magnification:"10x–40x (4:1 zoom; 10x eyepieces)",
   objectives:"Greenough zoom body; basic 0.5x/2x auxiliary objectives compatible",
   eyepieces:"WF 10x/20mm; binocular; 45° incline; 55–75mm IPD",
   stage:"Flat base with black/white reversible plate; basic stage clips",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Basic dissection","Entomology student","Hobbyist"],
   noteworthy:"Entry professional tier below the SM105. Variants: SM101 (binocular, halogen illumination), SM102 (binocular, LED illumination), S41-20 (step zoom version with lever-switched 20x/40x). These share the same basic Greenough optical body but in simpler stand configurations than the SM105. SM102 is the current production LED version. The SM101 uses halogen and is found in older school inventories. All are dealer-channel instruments, not sold via Amazon consumer channels.",
   oem_source:null}]
});
