// ════════════════════════════════════════════════════
// WILD HEERBRUGG (HISTORICAL)
// ════════════════════════════════════════════════════
DB.companies.push({id:"wild",name:"Wild Heerbrugg AG",shortName:"Wild Heerbrugg",flag:"🇨🇭",country:"Switzerland",
 founded:1921,status:"historical",featured:false,hq:"Heerbrugg, St. Gallen, Switzerland",
 categories:["compound","stereo"],
 overview:"Wild Heerbrugg AG was founded in 1921 in Heerbrugg, St. Gallen, Switzerland, by Heinrich Wild — a precision geodetic engineer who had previously worked at Carl Zeiss Jena, where he designed some of the most precise pre-WWI survey instruments ever made. Wild founded his own company after disagreements with Zeiss management, taking his optical and mechanical expertise to Switzerland and eventually extending it to microscopes. Wild built its reputation on a single design principle: if a product bears the Wild name, it is made to the highest mechanical standard achievable regardless of cost. This philosophy produced instruments still in active use and fully functional after 50+ years. Wild stereo microscopes use the CMO (Common Main Objective) optical design — a single large objective shared by both eyes via a beamsplitter — rather than the Greenough (two separate angled objectives) design used by most competitors. CMO provides a larger, flatter field, longer working distance, and superior performance at high magnification, at the cost of greater complexity and expense. Key models: the M3 series (modular 3-to-5 step zoom, widely used in biology and industry), M5 series (CMO with optional apochromatic objectives, the highest-specification Wild stereo), M7/M7A (5-step zoom), M8 (the definitive Wild CMO stereo, widely considered the finest stereo microscope ever made for general laboratory use), M10 (large-format research), M11 (portable cylinder field microscope for military and field research), M20 (compound upright, their landmark research microscope known for its ‘Swiss watch’ mechanics), and M40 (inverted tissue culture). Wild merged with Ernst Leitz Wetzlar in 1986 to form the Wild Leitz Group — the foundation of modern Leica Microsystems. The Wild instrument DNA continues directly in the Leica M-series stereos (MZ6, MZ8, M125, M205 FA) and the Leica M compound stereo line.",
 oem:{acquiredBy:"Leica Microsystems (1986–1990 merger with Ernst Leitz Wetzlar)",acquired:[],makesFor:[],madeBy:[],
  notes:"The Wild brand was retired after the Leica merger. Wild's stereo microscope designs continue as the Leica M and S series. Wild M10 objectives are compatible with subsequent Leica M-series stands."},
 models:[

  // ─── COMPOUND MICROSCOPES ─────────────────────────────────

  {id:"wild-m9",name:"M9",series:"M",type:"compound",subtype:"compound laboratory",
   introduced:1947,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$600",
   illumination:["Incandescent (mirror/substage)"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Achromat 4x/10x/40x/100x (160mm tube length, RMS thread)",
   eyepieces:"10x (standard)",stage:"Fixed circular stage; optional mechanical stage",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Laboratory biology","Clinical routine","Medical education","Basic research"],
   noteworthy:"One of Wild's first two microscopes (with the M10), released in 1947. Marked Wild's entry into microscopy, a strategic move to offset potential declines in survey instrument sales. All-metal brass construction of the highest Swiss precision. Relatively simple but robust — the foundation that Wild built their reputation on.",
   oem_source:null},

  {id:"wild-m10c",name:"M10 (Compound)",series:"M",type:"compound",subtype:"compound laboratory",
   introduced:1947,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$650",
   illumination:["Incandescent (mirror/substage)","Built-in lamp (later versions)"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Achromat / Fluotar 4x/10x/40x/100x (160mm tube length)",
   eyepieces:"10x (standard)",stage:"Mechanical stage (optional)",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Laboratory biology","Clinical routine","Education","Basic research"],
   noteworthy:"Released alongside the M9 as Wild's inaugural compound microscope pair in 1947. Early Swiss precision construction. Predates Wild's transition to more modern optics in the M11 and M20 era. Rare on the used market — most have not survived in working condition.",
   oem_source:null},

  {id:"wild-m11",name:"M11",series:"M",type:"compound",subtype:"compound laboratory / field",
   introduced:1954,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$300–$900",
   illumination:["Incandescent (mirror or built-in 6V lamp)","HBO fluorescence (optional)"],
   magnification:"20x–1000x (2x–100x objectives, 10x eyepieces)",
   objectives:"Achromat / Fluotar / Plan-Fluotar 2x–100x (160mm tube, RMS thread); phase contrast available",
   eyepieces:"10x (standard); 45° monocular, vertical monocular, or binocular head",
   stage:"4 varieties: fixed circular, fixed rectangular, mechanical, rotating",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Field microscopy","Laboratory","Clinical","Phase contrast biology","Fluorescence","Photomicrography"],
   noteworthy:"Marketed as an 'Expansible microscope, ideal for field-work, courses and laboratory.' Surprisingly compact yet enormously accessory-rich — Wild made a vast range of accessories including photomicrography systems, fluorescence illuminators, phase contrast, darkfield, and polarization sets. Monocular, binocular, and photo tubes all available. Not yet at 'collectable' premium prices — excellent value for a functional Wild compound scope.",
   oem_source:null},

  {id:"wild-m20",name:"M20",series:"M",type:"compound",subtype:"research compound (flagship)",
   introduced:1954,discontinued:1976,price_tier:"premium",
   price_new:null,price_used:"$600–$2,500",
   illumination:["Halogen 6V/15W (built-in)","HBO 50W fluorescence"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Achromat / Fluotar / Plan-Fluotar 4x–100x (160mm tube); phase contrast, fluorescence objectives available",
   eyepieces:"10x (standard); binocular head standard; trinocular phototube available",
   stage:"Large format mechanical stage; circular rotating stage (optional)",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Clinical pathology","Fluorescence","Phase contrast","Photomicrography","Polarized light"],
   noteworthy:"The M20 is universally regarded as Wild's masterpiece compound microscope and one of the finest instruments of its era. Binocular as standard. Phase contrast, fluorescence, and a full photomicrography system (phototube, automatic exposure) were all available. Harvard's Collection of Historical Scientific Instruments holds a complete M20 KGS outfit ordered in 1960. Still widely sought and actively used — commands a significant premium for complete, well-equipped examples.",
   oem_source:null},

  {id:"wild-m20eb",name:"M20-EB",series:"M",type:"compound",subtype:"research compound (enhanced)",
   introduced:1973,discontinued:1976,price_tier:"premium",
   price_new:null,price_used:"$500–$2,000",
   illumination:["Halogen (built-in)","HBO fluorescence"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces; 994x with specific optics combination)",
   objectives:"Fluotar / Plan-Fluotar series (160mm); phase contrast and fluorescence objectives",
   eyepieces:"10x binocular standard",stage:"Large format mechanical stage",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence","Phase contrast","Photomicrography"],
   noteworthy:"Updated version of the M20 introduced shortly before the line was discontinued. The '-EB' designation refers to enhanced brightness and contrast features. The 994x figure references a specific documented optics combination. Rare — produced for only about 3 years. Desirable for collectors seeking a well-specified late-production Wild compound scope.",
   oem_source:null},

  {id:"wild-m21",name:"M21",series:"M",type:"compound",subtype:"polarizing compound",
   introduced:1962,discontinued:1970,price_tier:"premium",
   price_new:null,price_used:"$400–$1,400",
   illumination:["Halogen (built-in)"],
   magnification:"40x–1000x (polarizing objectives, 10x eyepieces)",
   objectives:"Strain-free achromat and fluotar objectives for polarized light",
   eyepieces:"10x binocular",stage:"Rotating graduated circular stage 360°",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Mineralogy","Petrology","Geology","Crystal analysis","Materials science"],
   noteworthy:"Wild's dedicated polarizing (petrographic) microscope. Features strain-free objectives, graduated rotating stage, Bertrand lens, and polarizer/analyzer. Used extensively in geological survey institutions, mining companies, and universities. Scarce on the used market — highly sought by geologists and earth scientists.",
   oem_source:null},

  {id:"wild-m50",name:"M50",series:"M",type:"compound",subtype:"compound laboratory",
   introduced:1963,discontinued:1971,price_tier:"mid",
   price_new:null,price_used:"$250–$800",
   illumination:["Halogen (built-in)"],
   magnification:"40x–550x (4x–55x objectives range, 10x eyepieces)",
   objectives:"Achromat series (160mm); limited to 550x maximum total magnification",
   eyepieces:"10x standard",stage:"Mechanical stage",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Sampling microscopy","Routine laboratory","Quality control","Clinical routine"],
   noteworthy:"Documented in the Wild virtual archive as 'Wild M50 1963-1971 (550x)'. The 550x designation suggests a deliberately limited magnification range for specific sampling and routine clinical applications — likely a cost-effective instrument for high-volume clinical and industrial lab use. Uncommon on the used market.",
   oem_source:null},

  // ─── STEREO MICROSCOPES ───────────────────────────────────

  {id:"wild-m40",name:"M40 / M40T",series:"M",type:"compound",subtype:"inverted tissue culture compound",
   introduced:1965,discontinued:1985,price_tier:"mid",price_new:null,price_used:"$200–$700",
   illumination:["Sub-stage built-in transmitted halogen","Phase contrast annuli in condenser turret"],
   magnification:"25x–400x (4x–40x objectives)",
   objectives:"Wild M-series inverted objectives (finite, long working distance). Wild thread standard.",
   eyepieces:"Wild 10x/18mm standard; binocular or monocular; 45° incline",
   stage:"Fixed large stage; focusing nosepiece; coarse + fine focus on body",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Tissue culture","Cell biology","IVF","Microbiology","Embryology"],
   noteworthy:"Wild Heerbrugg’s primary inverted tissue culture microscope. Build quality is exceptional. The M40T adds a trinocular photo port. Wild’s phase contrast on inverted scopes was considered among the best of the era. Wild inverted objectives are platform-specific — NOT cross-compatible with upright Wild compound objectives. After the Wild-Leitz merger, this line transitioned into the Leica DMIL.",
   oem_source:null},

{id:"wild-m5",name:"M5",series:"M",type:"stereo",subtype:"zoom stereo (discrete steps)",
   introduced:1958,discontinued:1989,price_tier:"premium",
   price_new:null,price_used:"$600–$1,500",
   illumination:["Incandescent lamp (incident)","Optional transmitted light base"],
   magnification:"6x, 12x, 25x, 50x (discrete steps with 10x eyepieces; extended range 1.5x–200x with accessories)",
   objectives:"CMO 1x achromat (fixed); 0.5x and 1.5x auxiliary objectives available",
   eyepieces:"10x/21mm (standard); 6.3x, 16x, 25x also available",
   stage:"Large flat base; mechanical stage (optional); boom arm stand (optional)",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Zoology","Entomology","Botany","Surgery preparation","Natural history","Geology"],
   noteworthy:"Wild's first stereo microscope (1958) and one of the longest-produced scientific instruments of the 20th century — made continuously for 31 years until 1989. Four discrete magnifications (6x, 12x, 25x, 50x) in a doubling progression via a rotating drum changer. CMO (common main objective) / parallel optic design — all Wild stereos use this principle, giving superior image quality vs. Greenough designs. Highly regarded for its wide optical path separation, giving an enhanced 3D stereo effect. Still actively used in research labs today. Used M5 microscopes sell for ~$800 in working condition.",
   oem_source:null},

  {id:"wild-m5a",name:"M5A / M5APO",series:"M",type:"stereo",subtype:"zoom stereo (discrete steps)",
   introduced:1971,discontinued:1989,price_tier:"premium",
   price_new:null,price_used:"$700–$1,800",
   illumination:["Halogen (incident)","Optional transmitted light base"],
   magnification:"6x, 12x, 25x, 50x (discrete steps with 10x eyepieces)",
   objectives:"CMO 1x achromat; optional 1x Apochromat (M5APO); 0.5x and 1.5x auxiliary available",
   eyepieces:"10x/21mm standard",stage:"Large flat base; optional stands",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Natural history","Surgery","Entomology","Botany","Geology","Quality inspection"],
   noteworthy:"Updated M5 with improved mechanics and optional apochromatic objective (M5APO version — advertised in Analytical Chemistry, 1982, as a joint E. Leitz/Wild product). The M5APO's apochromatic CMO significantly improves color correction and resolution. Same four discrete magnifications as the M5. M3 and M5 series objectives are interchangeable. The M5APO commands a notable premium over the standard M5A.",
   oem_source:null},

  {id:"wild-m4",name:"M4",series:"M",type:"stereo",subtype:"educational stereo (discrete steps)",
   introduced:1959,discontinued:1970,price_tier:"mid",
   price_new:null,price_used:"$200–$600",
   illumination:["Incandescent (incident)"],
   magnification:"6x, 16x, 40x (discrete; 10x and 25x also available with changer II; 10x eyepieces)",
   objectives:"CMO 1x achromat; sliding cartridge magnification changers (Changer I or II)",
   eyepieces:"10x/21mm standard",stage:"Trapezoidal base plate; swing-arm stand option",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Dissection","Basic biological observation","Introductory laboratories"],
   noteworthy:"Wild's student/education stereo, introduced just one year after the M5. Left/right sliding cartridge magnification changers (three magnifications with Changer I; Changer II offers 10x and 25x). Later variants M4A (1967) and M4C (1965) used circular changers. The M4 was succeeded by the M1 series in 1973 for the educational market. The plastic 'wings' beneath the magnification changer are commonly missing on surviving examples.",
   oem_source:null},

  {id:"wild-m3",name:"M3 / M3B / M3C / M3Z",series:"M",type:"stereo",subtype:"zoom stereo (discrete steps or zoom)",
   introduced:1966,discontinued:1989,price_tier:"mid",
   price_new:null,price_used:"$400–$1,400",
   illumination:["Halogen (incident)","Optional transmitted light base"],
   magnification:"M3/M3B: 6.4x, 16x, 40x (3 discrete; 10x ep) | M3C: 6.4x, 10x, 16x, 25x, 40x (5 discrete) | M3Z: 6.4x–40x continuous zoom",
   objectives:"CMO 1x achromat (standard); 1x PlanApo available on M3Z; 0.5x/1.5x/2x auxiliary",
   eyepieces:"10x/21mm standard",stage:"Flat base; various stand options; boom arm available",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["QC inspection","Dissection","Entomology","Electronics","Natural history","Education"],
   noteworthy:"The M3 series spanned three major variants. M3B (3 magnifications), M3C (5 magnifications — most versatile discrete-step version, sells ~$1,200 used), M3Z (continuous zoom 6.4x–40x with plan objective — the only zoom in the M3 line). The M3Z PlanApo version is particularly sought for flat-field imaging. Wild photo systems fit the M3 series. M3 objectives are interchangeable with M5. Extended range with accessories: 1.5x–160x.",
   oem_source:null},

  {id:"wild-m1",name:"M1 Series",series:"M",type:"stereo",subtype:"educational stereo",
   introduced:1973,discontinued:1985,price_tier:"budget",
   price_new:null,price_used:"$150–$450",
   illumination:["Halogen (incident)","Optional transmitted light base"],
   magnification:"Varies by CMO: typically 6x–40x (3–4 discrete steps, 10x eyepieces)",
   objectives:"Interchangeable CMOs (multiple magnification ranges available)",
   eyepieces:"10x/21mm standard",stage:"Flat base; incident-light or transmitted-light stands; swing-arm stand",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Education","Student dissection","Basic biological observation","Introductory labs"],
   noteworthy:"Successor to the M4 for the educational market. The M1 was Wild's most economical stereo, designed specifically for students. Interchangeable CMOs allow the magnification range to be adapted to specific teaching applications. Some M1A versions have a rectangular-section pole for fixed orientation — unusual for Wild. Sold through the mid-1980s.",
   oem_source:null},

  {id:"wild-m7",name:"M7",series:"M",type:"stereo",subtype:"zoom stereo",
   introduced:1972,discontinued:1984,price_tier:"premium",
   price_new:null,price_used:"$500–$1,400",
   illumination:["Halogen (incident)","Optional transmitted light base"],
   magnification:"Continuous zoom, approximately 7x–45x (10x eyepieces)",
   objectives:"CMO zoom body; auxiliary objectives available",
   eyepieces:"10x/21mm standard",stage:"Various stand options",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","QC inspection","Research","Electronics","Natural history"],
   noteworthy:"Wild's first zoom stereomicroscope — a significant departure from the company's traditional discrete-step approach. Introduced alongside the Leitz/Wild cooperation (1972). The M7 preceded the M8 and offered Wild's first smooth continuous zoom capability. Compatible with Wild photo systems shared with the M3, M8, and M10 series.",
   oem_source:null},

  {id:"wild-m8",name:"M8",series:"M",type:"stereo",subtype:"zoom stereo (CMO)",
   introduced:1974,discontinued:1990,price_tier:"premium",
   price_new:null,price_used:"$700–$2,200",
   illumination:["Halogen 6V/10W (incident)","Optional transmitted light base"],
   magnification:"6x–50x continuous zoom (8.3:1 zoom ratio; 10x/21mm eyepieces)",
   objectives:"CMO 1x Plan objective (fixed); no PlanApo available — a known limitation",
   eyepieces:"10x/21mm standard; compatible with wider-field eyepieces",
   stage:"Flat base; transmitted light stand; boom arm stand (optional)",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["QC inspection","Dissection","Electronics","Entomology","Research","Natural history","Watchmaking / jewelry"],
   noteworthy:"The M8 is widely regarded as the definitive Wild zoom stereo and one of the finest stereo microscopes ever made. CMO design with parallel optics. 8.3:1 zoom (6x–50x with 10x eyepieces). Constructed almost entirely without plastic — cross-roller guide focus drives, engraved (not printed) magnification markings. Modular design for easy repair. Trinocular phototube available. Compatible with Leica M50/M60/M80 objectives (with limitations). Key drawback: no PlanApo objective was ever made for the M8, making the non-plan objective its primary optical limitation for photodocumentation. Still used and prized daily by microscopists worldwide.",
   oem_source:null},

  {id:"wild-m10s",name:"M10",series:"M",type:"stereo",subtype:"zoom stereo (CMO, PlanApo)",
   introduced:1989,discontinued:1990,price_tier:"ultra",
   price_new:null,price_used:"$2,000–$5,500",
   illumination:["Halogen (incident)","Optional transmitted light base and fluorescence"],
   magnification:"8x–80x continuous zoom (10:1 zoom ratio; 10x eyepieces)",
   objectives:"CMO 1x PlanApo (standard); 0.63x / 1.6x auxiliary available",
   eyepieces:"10x/21mm standard",stage:"Large format; various stand options",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Developmental biology","Fluorescence screening","QC","Electronics","Neuroscience"],
   noteworthy:"The M10 was the M8's successor and Wild's finest stereo microscope — introduced in the final year of the Wild brand before the full Leica transition. Key advancement over M8: a true 1x PlanApo objective providing exceptional flat-field correction and apochromatic color fidelity. 10:1 zoom (8x–80x). Trinocular phototube standard. Fluorescence-capable. M10 objectives are incompatible with the M8 but are compatible with subsequent Leica M-series stands. 'If you are going to spend $3000 on a stereo microscope, buy a Wild M10' — photomacrography.net. The rarest production Wild stereo and highest collectible value.",
   oem_source:null},

  // ─── MAKROSKOP / MACROSCOPE ───────────────────────────────

  {id:"wild-m400",name:"M400 Photomakroskop",series:"Makroscop",type:"stereo",subtype:"macroscope / photomacroscope",
   introduced:1976,discontinued:1990,price_tier:"ultra",
   price_new:null,price_used:"$1,800–$6,000",
   illumination:["Halogen (coaxial incident)","Transmitted light base","Fluorescence (HBO optional)"],
   magnification:"5x–40x (Macrozoom 6.3x–32x objective; 10x eyepieces); up to 80x with 2x auxiliary",
   objectives:"Macrozoom objective (f=200mm, 6.3x–32x zoom, ~5:1 ratio); 0.5x/1.5x/2x supplementary",
   eyepieces:"10x (standard); single optical path to both eyepieces (not stereoscopic)",
   stage:"Large format macrostage with XY movement; aperture control",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Macro photography","Developmental biology","Whole-mount specimens","Neuroscience","Botany","Forensics","Photomacroscopy"],
   noteworthy:"The M400 was Wild's flagship macroscope — a single-optical-path instrument optimised for photomacroscopy at magnifications bridging the gap between stereo and compound. Unlike a stereo scope, both eyepieces receive the same image (no 3D), but resolution and flatness are dramatically superior for photographic work. Electronic controls, automatic exposure, and aperture control built-in. NA of 0.115 at 5x (comparable to a 10x compound objective). Directly inspired the Leica M420 and is the ancestor of the Leica Z6/Z16. For photomacroscopy of developmental specimens, widely considered the finest instrument of its era.",
   oem_source:null},

  {id:"wild-m410",name:"M410",series:"Makroscop",type:"stereo",subtype:"macroscope (observation only)",
   introduced:1976,discontinued:1990,price_tier:"premium",
   price_new:null,price_used:"$1,200–$3,500",
   illumination:["Halogen (coaxial incident)","Transmitted light base"],
   magnification:"5x–40x (Macrozoom objective, 10x eyepieces)",
   objectives:"Macrozoom objective (6.3x–32x zoom); supplementary objectives available",
   eyepieces:"10x standard; single optical path",
   stage:"Large format macrostage",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Macro observation","Dissection","Whole-mount viewing","Natural history","Botany"],
   noteworthy:"The observation-only sister model to the M400 — same optical system but without the photomicroscopy systems (no phototube, no automatic exposure). Designed for visual examination only. Less expensive than the M400. Excellent for labs needing macroscopic observation capability without photodocumentation requirements.",
   oem_source:null},

  {id:"wild-m420",name:"Makroscop M420",series:"Makroscop",type:"stereo",subtype:"macroscope / photomacroscope",
   introduced:1980,discontinued:2003,price_tier:"ultra",
   price_new:null,price_used:"$2,500–$7,500",
   illumination:["Halogen (coaxial incident)","Transmitted light base","HBO fluorescence (optional)"],
   magnification:"5x–40x (Macrozoom 6.3x–32x objective, 10x eyepieces); up to 80x with 2x auxiliary",
   objectives:"Macrozoom objective (6.3x–32x); 0.5x/1.5x/2x supplementary lenses",
   eyepieces:"10x standard; single non-stereoscopic optical path",
   stage:"Large format macrostage with XY control and aperture",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Whole-mount fluorescence","Macro photography","Neuroscience","Botany","Forensics"],
   noteworthy:"The M420 was a lower-cost alternative to the M400 — retaining the same Macrozoom optical system but without the M400's built-in electronic controls, instead accepting user-mounted cameras on top. Continued in production under the Leica brand until 2003, long after the Wild brand was retired — testament to its enduring value. Fluorescence-capable with HBO illuminator. Directly inspired the Leica M205 FA and Zeiss SteREO Discovery. The benchmark for whole-mount developmental biology imaging across two decades. Still used and serviced in specialist labs.",
   oem_source:null},

  {id:"wild-m450",name:"EpiMakroskop M450",series:"Makroscop",type:"stereo",subtype:"macroscope (epi-illumination variant)",
   introduced:1982,discontinued:1990,price_tier:"ultra",
   price_new:null,price_used:"$2,000–$5,500",
   illumination:["Halogen coaxial epi-illumination (Epizoom objective with permanent 2x front element)"],
   magnification:"10x–80x (Epizoom objective — 2x Macrozoom equivalent; 10x eyepieces)",
   objectives:"Epizoom objective (Macrozoom with permanent 2x front element; double magnification, half field of view vs M400/M420)",
   eyepieces:"10x standard",stage:"Large format macrostage",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Surface inspection","Electronics","Semiconductor","Industrial macro-inspection","Reflected-light macroscopy"],
   noteworthy:"The M450 EpiMakroskop features the 'Epizoom' objective — essentially the standard Macrozoom with a permanently attached 2x front element providing twice the magnification but half the field of view compared to the M400/M420. Optimised for epi-illumination (reflected light from above) for surface inspection of opaque specimens. Rare — produced for only about 8 years and used in specialised industrial and semiconductor contexts.",
   oem_source:null}

]});
