// ════════════════════════════════════════════════════
// BIG FOUR — ZEISS
// ════════════════════════════════════════════════════
DB.companies.push({id:"zeiss",name:"Carl Zeiss AG",shortName:"Zeiss",flag:"🇩🇪",country:"Germany",
 founded:1846,status:"active",featured:true,hq:"Oberkochen, Germany",
 categories:["compound","stereo"],
 overview:"Founded by Carl Zeiss in Jena in 1846, the company’s scientific foundations were laid by physicist Ernst Abbe (joined 1866) and glassmaker Otto Schott. Abbe’s 1873 wave-optics diffraction theory of image formation — establishing the mathematical relationship between wavelength, numerical aperture, and resolution — is arguably the most important single contribution to microscope optics in history. Abbe and Schott also introduced apochromatic objectives (1886) and plan objectives, setting standards that define professional microscopy to this day. In 1889, following Zeiss’s death, Abbe established the Carl-Zeiss-Stiftung (foundation) — a legally unique entity with no shareholders, mandated to reinvest profits for employees and science. This foundation ownership structure remains today and is why Zeiss has never been sold to private equity. Zeiss was divided by WWII: in 1945 US forces evacuated 126 senior staff to Oberkochen (West Germany), while the Jena factories were nationalized as VEB Carl Zeiss Jena (East Germany). The two companies operated as rivals for 46 years; reunification occurred 1991–1995 when Oberkochen absorbed the Jena optical and microscopy divisions. Today Carl Zeiss AG (Oberkochen) is the unified successor, with Jena now home to Carl Zeiss Microscopy GmbH. Key microscopy milestones: first commercial Greenough stereo microscope (1897), ICS infinity optical system (1990s), Axiovert research inverted series, Axio Observer, and the Elyra super-resolution family (SIM/PALM).",
 oem:{acquiredBy:null,acquired:["Carl Zeiss Jena (East German split, reunified 1991)"],makesFor:[],madeBy:[],notes:"Carl Zeiss Jena was the East German entity; both halves were legally reunified in 1991."},
 models:[
  // ── CURRENT ──
  {id:"zeiss-primo-star",name:"Primo Star",series:"Primo",type:"compound",subtype:"brightfield upright",
   introduced:2006,discontinued:false,price_tier:"budget",
   price_new:"$1,800–$3,200",price_used:"$400–$900",
   illumination:["LED","Halogen"],magnification:"40x–1000x",objectives:"4x/10x/40x/100x achromat",
   eyepieces:"10x/20mm",stage:"Mechanical 140×130mm",fluorescence:false,phase_contrast:true,
   darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,
   software:"ZEN Lite / Labscope",
   applications:["Education","Clinical routine","Hematology","Urinalysis"],
   noteworthy:"Arguably the most widely deployed teaching and clinical routine microscope globally. LED illumination standard since ~2012. Renowned for ergonomic Köhler setup and exceptional build quality for its price tier.",
   oem_source:null},
  {id:"zeiss-axioscope5",name:"Axioscope 5",series:"Axioscope",type:"compound",subtype:"research upright",
   introduced:2018,discontinued:false,price_tier:"mid",
   price_new:"$8,000–$22,000",price_used:"$3,500–$10,000",
   illumination:["LED (Colibri 3/7)","Halogen"],magnification:"50x–1000x",
   objectives:"Plan-Apo / EC Plan-Neofluar series",eyepieces:"10x/23mm",
   stage:"Motorized encoded (optional)",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,software:"ZEN Blue / ZEN Core",
   applications:["Materials science","Life science","Clinical pathology","Multi-contrast imaging"],
   noteworthy:"Modular upright platform fully compatible with the Colibri LED system for widefield fluorescence. Motorized version supports automated tiling and Z-stacking for large-format sample documentation.",
   oem_source:null},
  {id:"zeiss-axio-observer7",name:"Axio Observer 7",series:"Axio Observer",type:"compound",subtype:"inverted research",
   introduced:2016,discontinued:false,price_tier:"premium",
   price_new:"$35,000–$85,000",price_used:"$8,000–$28,000",
   illumination:["LED (Colibri 7)","Halogen","Laser (add-on)"],magnification:"25x–1000x",
   objectives:"Plan-Apochromat / LD Plan-Neofluar",eyepieces:"10x/23mm",
   stage:"Motorized encoded 130×100mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"ZEN Blue / ZEN Black",
   applications:["Live cell imaging","TIRF","FRAP","Single molecule imaging","Drug screening"],
   noteworthy:"Premier Zeiss inverted research platform. Supports TIRF, PALM/STORM, and lattice light sheet add-ons. Definite Focus 2 hardware autofocus prevents Z-drift during long-term live experiments.",
   oem_source:null},
  {id:"zeiss-stereo-discovery",name:"SteREO Discovery.V20",series:"SteREO Discovery",type:"stereo",subtype:"research fluorescence stereo",
   introduced:2005,discontinued:false,price_tier:"ultra",
   price_new:"$45,000–$130,000",price_used:"$12,000–$40,000",
   illumination:["LED ring light","Fluorescence (HBO/LED)","Coaxial LED"],
   magnification:"7.5x–150x (10x ep, 1x obj; up to 225x with 1.5x obj)",
   objectives:"0.3x/0.63x/1.5x/2.3x plan-apochromat auxiliary",eyepieces:"10x/23mm",
   stage:"Large transmitted + reflected",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:true,inverted:false,camera_port:true,software:"ZEN Blue",
   applications:["Developmental biology","Neuroscience","GFP/RFP screening","Model organisms"],
   noteworthy:"20:1 zoom ratio (zoom body 0.75x–15x). Apochromatic optics with eZoom for motorized magnification recall >99% reproducible. The benchmark fluorescence stereo for zebrafish, Drosophila, and mouse model work.",
   oem_source:null},
  {id:"zeiss-stemi508",name:"Stemi 508",series:"Stemi",type:"stereo",subtype:"zoom stereo",
   introduced:2016,discontinued:false,price_tier:"mid",
   price_new:"$1,400–$3,200",price_used:"$500–$1,400",
   illumination:["LED transmitted","LED reflected","LED ring"],
   magnification:"6.3x–50x (standard 10x/23 eyepieces; 2x–250x with auxiliary objectives)",
   objectives:"Fixed Greenough; optional PlanApo S 0.5x/1.5x/2.0x auxiliary",
   eyepieces:"10x/23mm",stage:"Foam stage / large format",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,motorized:false,inverted:false,
   camera_port:true,software:"ZEN Lite (with optional camera)",
   applications:["QC/inspection","Dissection","Electronics","Natural history","Education"],
   noteworthy:"8:1 zoom ratio; zoom body 0.63x–5.0x. With standard 10x/23 eyepieces: 6.3x–50x. Apochromatic optics with 35° viewing angle for ergonomic extended use. Excellent for students and routine lab work.",
   oem_source:null},
  // ── HISTORICAL / COLLECTIBLE ──
  {id:"zeiss-axiophot",name:"Axiophot",series:"Axio",type:"compound",subtype:"research upright (fluorescence)",
   introduced:1984,discontinued:1998,price_tier:"premium",
   price_new:null,price_used:"$500–$1,800",
   illumination:["Halogen (transmitted)","HBO 50/100W (fluorescence)"],magnification:"12.5x–1000x",
   objectives:"Plan-Neofluar / Plan-Apochromat (Axio series)",eyepieces:"10x/25mm",
   stage:"Mechanical / motorized option",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence imaging","Neuroanatomy","Cell biology","Photomicrography"],
   noteworthy:"The Axiophot was Zeiss's flagship fluorescence research upright of the late 1980s–90s and introduced the 'Axio' naming convention still used today. Extraordinary optical quality with the Plan-Neofluar and Plan-Apo series. Highly sought on the used market for its robust build and still-excellent optics. Many units remain in active use.",
   oem_source:null},
  {id:"zeiss-axioplan",name:"Axioplan",series:"Axio",type:"compound",subtype:"research upright",
   introduced:1986,discontinued:2001,price_tier:"premium",
   price_new:null,price_used:"$800–$2,500",
   illumination:["Halogen","HBO fluorescence"],magnification:"12.5x–1000x",
   objectives:"Plan-Neofluar / Plan-Apochromat",eyepieces:"10x/25mm",
   stage:"Mechanical large format",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Fluorescence","Neuroanatomy","Histology","DIC"],
   noteworthy:"The Axioplan defined research microscopy in the late 1980s and 1990s. Built to last generations — these are commonly found in used equipment markets still performing excellently. The Plan-Neofluar objectives set the standard for fluorescence imaging. Excellent value for a well-equipped research lab on a budget.",
   oem_source:null},
  {id:"zeiss-axioplan2",name:"Axioplan 2",series:"Axio",type:"compound",subtype:"research upright",
   introduced:1996,discontinued:2008,price_tier:"premium",
   price_new:null,price_used:"$1,500–$4,500",
   illumination:["Halogen","HBO 100W fluorescence","Metal halide option"],magnification:"50x–1000x",
   objectives:"Plan-Apochromat / Plan-Neofluar (improved coating)",eyepieces:"10x/25mm",
   stage:"Mechanical / optional motorized",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"AxioVision (early versions)",
   applications:["Research","Fluorescence","Materials","DIC","Photomicrography"],
   noteworthy:"Updated Axioplan with improved anti-reflection coatings and better fluorescence throughput. Accepts the full range of Zeiss Axio fluorescence filter sets and condensers. Still widely used in university research departments. Compatible with early digital cameras.",
   oem_source:null},
  {id:"zeiss-axioskop",name:"Axioskop",series:"Axio",type:"compound",subtype:"research/clinical upright",
   introduced:1988,discontinued:2001,price_tier:"mid",
   price_new:null,price_used:"$400–$1,500",
   illumination:["Halogen","HBO fluorescence (optional)"],magnification:"50x–1000x",
   objectives:"Plan-Neofluar / Achroplan",eyepieces:"10x/23mm",
   stage:"Mechanical",fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Research","Clinical pathology","Neuroscience","Histology","Education"],
   noteworthy:"The Axioskop was the mid-tier research/clinical upright of the late 1980s–90s. Simpler than the Axiophot but using the same outstanding Zeiss optics. Hundreds of thousands sold worldwide. One of the most common used scopes available. Very affordable entry into Zeiss optics.",
   oem_source:null},
  {id:"zeiss-axioskop2",name:"Axioskop 2 Plus",series:"Axio",type:"compound",subtype:"research upright",
   introduced:1999,discontinued:2012,price_tier:"mid",
   price_new:null,price_used:"$800–$2,800",
   illumination:["Halogen","HBO fluorescence"],magnification:"50x–1000x",
   objectives:"Plan-Neofluar / Plan-Apochromat",eyepieces:"10x/23mm",
   stage:"Mechanical / motorized option",fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,software:"AxioVision",
   applications:["Research","Neuroscience","Electrophysiology","Histology","Multi-contrast"],
   noteworthy:"Updated Axioskop with expanded contrast methods and better fluorescence capability. Very popular for electrophysiology labs due to the low-stage ergonomic design. Accepts full Zeiss fluorescence module set. Excellent used value with broad parts availability.",
   oem_source:null},
  {id:"zeiss-axiovert135",name:"Axiovert 135 / 135M",series:"Axiovert",type:"compound",subtype:"inverted research (finite, full DIC/fluorescence)",
   introduced:1988,discontinued:1998,price_tier:"mid",price_new:null,price_used:"$400–$2,000",
   illumination:["HAL 12V/100W transmitted","HBO 100W epi-fluorescence","Optovar 1x/1.6x/2.5x magnification changer built in"],
   magnification:"25x–1000x base; up to 2500x with 2.5x Optovar + 100x objective",
   objectives:"Finite 8mm tube system — Zeiss Plan-Neofluar and Achroplan inverted series marked ‘8/’. NOT interchangeable with Axiovert 100/200 ICS objectives.",
   eyepieces:"Pl 10x/20mm (23.2mm tube); tiltable upper arm",
   stage:"Full mechanical XY stage; universal plate adapters",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Cell biology","Fluorescence","DIC","Live cell imaging","Confocal coupling","Patch clamp"],
   noteworthy:"Premier Zeiss research inverted of the early-to-mid 1990s. CRITICAL OBJECTIVE NOTE: uses objectives labeled ‘8/’ — a Zeiss-specific finite optical system. NOT compatible with Axiovert 100/200 ICS objectives or standard upright objectives. The 135M adds motorized focus. Built-in Optovar (1x/1.6x/2.5x) is a major practical advantage.",
   oem_source:null},

{id:"zeiss-axiovert100",name:"Axiovert 100",series:"Axio",type:"compound",subtype:"inverted research",
   introduced:1987,discontinued:1999,price_tier:"premium",
   price_new:null,price_used:"$400–$2,000",
   illumination:["Halogen","HBO fluorescence"],magnification:"50x–1000x",
   objectives:"Plan-Neofluar LD (long working distance)",eyepieces:"10x/23mm",
   stage:"Mechanical 180×160mm",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Live cell culture","Cell biology","Phase contrast of cultures","Timelapse (film era)"],
   noteworthy:"Zeiss's first major inverted research platform in the modern era. Used in virtually every cell biology laboratory of the late 1980s–1990s. LWD objectives allow phase contrast imaging of cells in standard culture vessels. Still widely available and functional on the used market.",
   oem_source:null},
  {id:"zeiss-axiovert200",name:"Axiovert 200",series:"Axiovert",type:"compound",subtype:"inverted research (ICS, manual)",
   introduced:2000,discontinued:2008,price_tier:"mid",price_new:null,price_used:"$800–$4,000",
   illumination:["HAL 12V/100W transmitted","HBO 100W epi-fluorescence","Optional XBO 75W xenon"],
   magnification:"25x–1000x; 10x/22mm eyepieces",
   objectives:"ICS infinity-corrected, 164.5mm tube lens, M27 thread. Full range Plan-Achromat, Plan-Neofluar, Plan-Apochromat inverted LD series.",
   eyepieces:"Pl 10x/22mm (23.2mm tube); 30° binocular or trinocular",
   stage:"Full mechanical stage; large specimen opening",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,motorized:false,inverted:true,camera_port:true,software:"AxioVision (optional)",
   applications:["Cell biology","Fluorescence","DIC","Live cell imaging","Confocal coupling"],
   noteworthy:"Manual (non-motorized) counterpart to the Axiovert 200M. Same ICS optical system — M27 objectives fully interchangeable. Extremely common in research institute surplus; one of the best value research inverteds available used.",
   oem_source:null},

{id:"zeiss-axio-observer5",name:"Axio Observer 5",series:"Axio Observer",type:"compound",subtype:"inverted research (ICS, LED, current mid-range)",
   introduced:2016,discontinued:false,price_tier:"mid",price_new:"$15,000–$40,000",price_used:"$5,000–$15,000",
   illumination:["LED transmitted (Colibri 3 or HAL 100 option)","HBO/LED fluorescence epi"],
   magnification:"20x–1000x; FN22 field number",
   objectives:"ICS2 infinity-corrected, 165mm tube lens, M27 thread. Full Plan-Apochromat, Plan-Neofluar, LD series.",
   eyepieces:"10x/22mm; 30° binocular or trinocular",
   stage:"Manual or motorized (Observer 5 M variant)",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:true,motorized:false,inverted:true,camera_port:true,software:"ZEN Blue",
   applications:["Live cell imaging","Fluorescence","Cell biology"],
   noteworthy:"Current mid-range entry in Zeiss’s Axio Observer line, sitting below the flagship Observer 7. Fully LED-capable with the Colibri LED fluorescence system.",
   oem_source:null},

{id:"zeiss-axiovert200m",name:"Axiovert 200M",series:"Axio",type:"compound",subtype:"motorized inverted research",
   introduced:2001,discontinued:2012,price_tier:"premium",
   price_new:null,price_used:"$2,500–$7,500",
   illumination:["Halogen","HBO 100W / Metal halide fluorescence","Laser (add-on)"],
   magnification:"25x–1000x",objectives:"Plan-Apochromat / Plan-Neofluar LD",eyepieces:"10x/23mm",
   stage:"Motorized 130×100mm, encoded",fluorescence:true,phase_contrast:true,darkfield:false,dic:true,
   motorized:true,inverted:true,camera_port:true,software:"AxioVision",
   applications:["Live cell","Timelapse","TIRF (add-on)","Cell biology","Drug discovery"],
   noteworthy:"The motorized Axiovert 200M was the benchmark inverted platform of the early 2000s — predecessor to the Axio Observer. Fully automated for multi-position timelapse. Still in use in many labs. Software is outdated but hardware remains excellent. Strong used market value.",
   oem_source:null},
  {id:"zeiss-stemi-sv6",name:"Stemi SV6",series:"Stemi SV",type:"stereo",subtype:"research zoom stereo (CMO)",
   introduced:1999,discontinued:2014,price_tier:"mid",price_new:null,price_used:"$400–$1,200",
   illumination:["Built-in incident fiber illuminator","Optional transmitted base","Optional LED ringlight"],
   magnification:"8x–50x (6:1 zoom; 10x/23mm eyepieces); up to 80x with 1.6x aux",
   objectives:"CMO system; 0.63x/0.8x/1x/1.6x PlanApo objectives; 30mm Interface 60 photo port",
   eyepieces:"10x/23mm Plan standard",stage:"Multiple base options; 76mm neck diameter",
   fluorescence:false,phase_contrast:false,darkfield:true,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Embryology","Electronics","Gemology","Natural history","Industrial QC"],
   noteworthy:"Entry-level CMO stereo in Zeiss’s Stemi SV line. Common Main Objective design gives superior image quality vs. Greenough. WARNING: Some SV6 and SV8 units from the 1970s–80s suffer lens cement delamination. Inspect through eyepieces before buying — purple fringing and haze are the telltale signs.",
   oem_source:null},

{id:"zeiss-stemi-sv8",name:"Stemi SV8",series:"Stemi SV",type:"stereo",subtype:"research zoom stereo (CMO)",
   introduced:1975,discontinued:1999,price_tier:"mid",price_new:null,price_used:"$300–$900",
   illumination:["Built-in body spotlight (incident)","Optional transmitted mirror base"],
   magnification:"8x–50x (standard 10x eyepieces)",
   objectives:"CMO system; square-section 1x standard objective; optional planachromat upgrade",
   eyepieces:"10x/21mm standard binocular; 30mm photo port",stage:"Multiple base options; all-metal boxy body; depth-of-field diaphragm wheel",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Dissection","Electronics","Geology","Industrial inspection"],
   noteworthy:"Classic Zeiss CMO workhorse of the 1970s–90s. DELAMINATION WARNING: A significant fraction of SV8 units suffer lens cement delamination — an irreparable failure. Always inspect through eyepieces before purchasing. Later 1980s units are less affected.",
   oem_source:null},

{id:"zeiss-stemi-sv11",name:"Stemi SV11",series:"Stemi SV",type:"stereo",subtype:"research zoom stereo",
   introduced:1985,discontinued:2005,price_tier:"premium",
   price_new:null,price_used:"$1,200–$3,800",
   illumination:["Halogen (external)","Fluorescence option"],
   magnification:"6.6x–120x (with auxiliary objectives)",
   objectives:"0.5x–2.0x auxiliary",eyepieces:"10x/23mm",
   stage:"Large format transmitted + reflected",fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Developmental biology","Fluorescence screening","Dissection","Model organisms"],
   noteworthy:"The SV11 was the predecessor to the SteREO Discovery series. 11.5:1 zoom ratio with true apochromatic optics — the first Zeiss stereo capable of widefield fluorescence. Used extensively for early zebrafish and Drosophila fluorescence screening. Highly sought for fluorescence stereomicroscopy on a budget.",
   oem_source:null},
  {id:"zeiss-stemi2000c",name:"Stemi 2000-C",series:"Stemi",type:"stereo",subtype:"zoom stereo",
   introduced:1998,discontinued:2010,price_tier:"mid",
   price_new:null,price_used:"$700–$2,500",
   illumination:["Halogen ring + transmitted","LED upgrade possible"],
   magnification:"7x–45x (10x eyepieces)",objectives:"Fixed Greenough; 0.63x/1.0x/1.5x/2.0x auxiliary",
   eyepieces:"10x/23mm",stage:"Flat base / stand options",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,motorized:false,inverted:false,
   camera_port:true,software:"—",
   applications:["QC inspection","Dissection","Electronics","Natural history","Education"],
   noteworthy:"Practical successor to the Stemi SV6. Very rugged and popular in industrial and university settings through the 2000s. Excellent optical quality for a fixed-objective zoom stereo. LED upgrades are available, making these highly usable second-hand instruments.",
   oem_source:null},

{id:"zeiss-standard-gf",name:"Standard GF",series:"Standard",type:"compound",subtype:"early West German upright binocular",
   introduced:1949,discontinued:1955,price_tier:"mid",
   price_new:null,price_used:"$300–$700",
   illumination:["Removable plug-in illuminator (fits concave base depression)","Manual twist on/off switch on lamp housing","Direct wall plug","Optional external mirror for daylight use"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"Zeiss 160mm RMS objectives — Achromat, Planachromat, Neofluar, Apochromat series",
   eyepieces:"C 10x (23.2mm tube diameter); upgradeable to KPL compensating eyepieces",
   stage:"Mechanical 130×90mm; coarse + fine focus; sub-stage condenser",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:false,software:"—",
   applications:["Clinical pathology","Education","Research","Histology","Hematology","Natural history"],
   noteworthy:"IDENTIFIED INSTRUMENT — Owner SN 2075589: West German Carl Zeiss (Oberkochen) Standard GF, manufactured approximately 1950–1954. Confirmed by: (1) ‘Carl Zeiss, Germany’ (no ‘Jena’) = West German Oberkochen. (2) Jet-black enamel — grey/cream transition occurred ~1955–56. (3) Concave base depression with removable plug-in illuminator and twist on/off switch = GF (Grundform). (4) Head part number 402-9316 = West German component numbering. C 10x eyepieces. Contact Zeiss Archive for exact date.",
   objective_guide:{
     warning:"Verify thread before purchasing. Most Standard GF scopes use RMS thread (20.32mm). All use 160mm finite tube length — do NOT use infinity-corrected (∞) objectives.",
     tube_length:"160mm finite.",
     thread:"RMS — 20.32mm diameter, 0.706mm pitch.",
     parfocal:"45mm standard (Zeiss).",
     compatible_series:[
       {name:"Achromat",code:"Achr",note:"Standard achromats. Common and affordable ($10–40). Originally supplied."},
       {name:"Planachromat",code:"Plan/PL",note:"Flat-field. Superior for photography."},
       {name:"Neofluar",code:"Neofluar",note:"Best practical upgrade. Inspect for delamination before buying."},
       {name:"Apochromat",code:"Apo",note:"Highest correction. Pair with KPL eyepieces."}
     ],
     incompatible:[
       "Infinity-corrected (∞) Zeiss ICS objectives",
       "M27 thread objectives (some modern Zeiss)",
       "Nikon CFI objectives (M25 thread)",
       "Olympus UIS/UIS2 objectives (infinity corrected)"
     ],
     buying_tips:"Search eBay for ‘Zeiss 160mm objective’ or ‘Zeiss Achromat 160 RMS’. Confirm ‘160’ on barrel (not ‘∞’). Most sell $20–80.",
     identification_resources:"Zeiss Archive: zeiss.com → Corporate → History → Archives. Provide SN 2075589 + photos. Also: Zeiss Historica Society (zeisshistorica.org)."
   },
   accessories:{
     illumination:[{name:"Original plug-in illuminator",note:"Fits concave base depression. Twist on/off. Direct wall plug. CHECK CORD CONDITION — may be 70+ years old. Re-wire if cracked."},{name:"LED retrofit",note:"Search ‘Zeiss Standard LED retrofit’. Modern and safe."}],
     condensers:[{name:"Abbe condenser NA 1.25",note:"Standard. Available eBay $20–60."}],
     eyepieces:[{name:"C 10x (original)",note:"23.2mm tube. Your current eyepieces."},{name:"KPL 10x compensating",note:"Zeiss top-tier 160mm eyepiece for Neofluar/Apo objectives."}],
     cameras:[{name:"USB eyepiece camera",note:"AmScope or similar USB cameras fit 23.2mm tube directly."}]
   },
   oem_source:null},

{id:"zeiss-standard-wl",name:"Standard WL",series:"Standard",type:"compound",subtype:"research / routine upright",
   introduced:1970,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$150–$600",
   illumination:["Halogen 6V/15W (built-in)","HBO fluorescence"],
   magnification:"25x–1000x (2.5x–100x objectives, 10x eyepieces)",
   objectives:"Plan-Neofluar / Achroplan (160mm tube, RMS thread); phase contrast available",
   eyepieces:"10x/20mm; binocular or trinocular",stage:"Mechanical 130x90mm; optional rotating stage",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Research","Clinical pathology","Fluorescence","DIC","Photomicrography","Polarization"],
   noteworthy:"The Standard WL was the late-era flagship of the Standard series and the bridge to the Axioplan generation. Combines the removable nosepiece of the Standard 18 with elements of the large Universal/Photomicroscope. Accepts the full Zeiss 160mm accessory range including Optovar magnification changer. Note: some WL optical components (Neofluar objectives and DIC prisms) are prone to delamination — inspect before purchasing.",
   oem_source:null},

  {id:"zeiss-standard-1416",name:"Standard 14 / Standard 16",series:"Standard",type:"compound",subtype:"routine / clinical upright (West German)",
   introduced:1966,discontinued:1985,price_tier:"mid",price_new:null,price_used:"$100–$400",
   illumination:["Built-in low-voltage halogen (6V 20W typical)","Variable intensity transformer"],
   magnification:"40x–1000x standard",
   objectives:"160mm finite, RMS thread. Standard 16: 5-position nosepiece; Standard 14: 4-position.",
   eyepieces:"KPL W 10x / KPL 10x compensating (23.2mm tube).",
   stage:"Mechanical coaxial stage; coarse + fine focus coaxial; sub-stage Abbe condenser NA 1.25",
   fluorescence:false,phase_contrast:true,darkfield:true,dic:false,motorized:false,inverted:false,camera_port:true,software:"—",
   applications:["Clinical pathology","Hematology","Education","Histology"],
   noteworthy:"IDENTIFICATION NOTE: Zeiss omitted model numbers from the instrument body on many Standard-series scopes. Identify from part codes stamped on components: look for ‘47 09 14’, ‘47 09 16’, or ‘47 09 18’. The Standard 16 adds a 5-hole nosepiece. Both use 160mm RMS objectives. One of the best-value research-quality scopes at $100–$400.",
   oem_source:null},

{id:"zeiss-telaval31",name:"Telaval 31",series:"Telaval",type:"compound",subtype:"inverted routine (pre-Axiovert)",
   introduced:1961,discontinued:1982,price_tier:"budget",price_new:null,price_used:"$80–$350",
   illumination:["Built-in transmitted sub-stage illumination","Simple halogen or incandescent"],
   magnification:"20x–400x (typical phase contrast configuration)",
   objectives:"160mm finite, RMS thread. Zeiss inverted objectives.",
   eyepieces:"Kpl 10x (23.2mm tube); monocular or binocular",
   stage:"Fixed stage with large opening; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:false,software:"—",
   applications:["Tissue culture","Protistology","Sediment analysis","Education"],
   noteworthy:"Zeiss’s primary inverted tissue culture microscope before the Axiovert era — the direct predecessor to the Axiovert 35. Uses 160mm finite optics throughout.",
   oem_source:null},

{id:"zeiss-im35",name:"IM / IM35",series:"IM",type:"compound",subtype:"inverted routine / tissue culture (finite)",
   introduced:1970,discontinued:1990,price_tier:"mid",price_new:null,price_used:"$150–$600",
   illumination:["Built-in sub-stage halogen","Optional epi-illumination attachment"],
   magnification:"25x–400x standard; phase contrast to 400x",
   objectives:"160mm finite, RMS thread. Zeiss inverted LWD objectives.",
   eyepieces:"KPL 10x / KPL W 10x (23.2mm); binocular or trinocular",
   stage:"Fixed stage, focusing nosepiece; large opening for culture flasks",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Tissue culture","Cell biology","Embryology","Microbiology"],
   noteworthy:"West German Zeiss’s standard finite-era inverted microscope, equivalent to the Olympus CK2 and Nikon Diaphot. Extremely common in university surplus. Compatible with Zeiss 160mm objectives.",
   oem_source:null},

{id:"zeiss-axiovert25",name:"Axiovert 25 / 25C / 25CFL",series:"Axiovert",type:"compound",subtype:"inverted routine / tissue culture (compact)",
   introduced:1996,discontinued:2010,price_tier:"budget",price_new:null,price_used:"$150–$600",
   illumination:["HAL 6V/30W transmitted","Axiovert 25CFL adds HBO 50W epi-fluorescence"],
   magnification:"20x–400x standard tissue culture config",
   objectives:"ICS infinity-corrected, 164.5mm tube lens, M27 thread. CP Achromat and LD Achrostigmat series.",
   eyepieces:"PL 10x/18mm (23.2mm tube); binocular 30°; front photo port on C and CFL variants",
   stage:"Fixed stage; large opening for T-flasks and petri dishes; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Tissue culture","Cell biology","IVF","Education"],
   noteworthy:"One of the most commonly encountered inverted microscopes on eBay and in university surplus. Three variants: Axiovert 25 (basic); Axiovert 25 C (documentation port); Axiovert 25 CFL (adds HBO 50W fluorescence). Uses ICS infinity-corrected optics with M27 thread — NOT RMS. Common failure: condenser slider detent wear.",
   oem_source:null},

{id:"zeiss-axiovert40",name:"Axiovert 40 / 40C / 40CFL",series:"Axiovert",type:"compound",subtype:"inverted routine (PlasDIC)",
   introduced:2002,discontinued:2014,price_tier:"budget",price_new:null,price_used:"$200–$800",
   illumination:["HAL 6V/30W transmitted","Optional HBO 50W fluorescence (CFL variant)"],
   magnification:"20x–400x standard",
   objectives:"ICS infinity-corrected, 164.5mm tube lens, M27 thread. CP Achromat, LD Achrostigmat, LD A-Plan series.",
   eyepieces:"PL 10x/18mm (23.2mm tube); 30° binocular",
   stage:"Fixed stage; large central opening; focusing nosepiece",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,motorized:false,inverted:true,camera_port:true,software:"—",
   applications:["Tissue culture","Cell biology","IVF","QC"],
   noteworthy:"Direct successor to the Axiovert 25, adding PlasDIC contrast — DIC-like relief contrast that works through plastic culture vessels (genuine DIC cannot). Three variants: 40 (basic), 40C (documentation), 40CFL (fluorescence). Same ICS M27 objective thread as the Axiovert 25.",
   oem_source:null},

{id:"zeiss-axiovert35",name:"Axiovert 35",series:"Axiovert",type:"compound",subtype:"inverted routine",
   introduced:1980,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$200–$700",
   illumination:["Halogen 6V/20W","HBO fluorescence (optional)"],
   magnification:"50x–400x (5x–40x LD objectives, 10x eyepieces)",
   objectives:"LD Plan-Neofluar 5x/10x/20x/40x (160mm, long working distance)",
   eyepieces:"10x/20mm; binocular standard",stage:"Mechanical 190x130mm",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"—",
   applications:["Cell culture","Tissue culture","Phase contrast of living cells","IVF","Clinical cytology"],
   noteworthy:"The Axiovert 35 was Zeiss's standard inverted microscope of the 1980s, used in virtually every cell biology and IVF lab equipped with Zeiss instruments. LD (long distance) Plan-Neofluar objectives for imaging cells in standard culture vessels. Fluorescence option widely added. Predecessor to the Axiovert 100. Very common on the used market.",
   oem_source:null},

  {id:"zeiss-axiolab",name:"Axiolab",series:"Axio",type:"compound",subtype:"routine clinical / education upright",
   introduced:1994,discontinued:true,price_tier:"budget",
   price_new:null,price_used:"$250–$800",
   illumination:["Halogen 6V/20W","LED (later versions)"],
   magnification:"40x–1000x (4x–100x objectives, 10x eyepieces)",
   objectives:"EC Plan-Neofluar (ICS infinity corrected)",
   eyepieces:"10x/20mm; binocular 30°",stage:"Mechanical",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["Medical education","Clinical routine","Hematology","Basic research"],
   noteworthy:"The Axiolab introduced the ICS (Infinity Color-Corrected System) optics to Zeiss's routine instruments. Compact, ergonomic, and durable. Widely adopted in European medical schools and NHS hospitals as a replacement for the aging Standard series. The Axiolab E continued into the 2010s.",
   oem_source:null},

  {id:"zeiss-axiostar",name:"Axiostar Plus",series:"Axio",type:"compound",subtype:"routine upright",
   introduced:1997,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$350–$1,100",
   illumination:["Halogen 6V/30W"],
   magnification:"40x–1000x (4x–100x ICS objectives, 10x eyepieces)",
   objectives:"EC Plan-Neofluar / Plan-Achrostat (ICS infinity corrected)",
   eyepieces:"10x/20mm; binocular 30°",stage:"Mechanical",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"AxioVision",
   applications:["Routine pathology","Education","Clinical labs","Multi-contrast research"],
   noteworthy:"Zeiss's mid-tier routine upright of the late 1990s–2000s, between the Axiolab and Axioskop 2. Phase contrast, fluorescence, and darkfield available. ICS optics. Widely found in European university teaching labs and hospital pathology departments.",
   oem_source:null},

  {id:"zeiss-axio-imager",name:"AxioImager A1/Z1",series:"Axio Imager",type:"compound",subtype:"research upright (ICS)",
   introduced:2006,discontinued:false,price_tier:"premium",
   price_new:"$12,000–$35,000",price_used:"$2,500–$12,000",
   illumination:["Halogen 12V/100W","Metal Halide","Colibri LED fluorescence"],
   magnification:"25x–1000x (2.5x–100x objectives, 10x/23mm eyepieces)",
   objectives:"Plan-Apochromat / EC Plan-Neofluar (ICS, M27 thread)",
   eyepieces:"10x/23mm; binocular or trinocular",stage:"Motorized encoded (Z1); manual (A1)",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:true,
   motorized:true,inverted:false,camera_port:true,
   software:"ZEN Blue / ZEN Core",
   applications:["Research","Materials science","Neuroscience","Digital pathology","Multi-contrast imaging"],
   noteworthy:"The AxioImager replaced the Axioplan 2 as Zeiss's flagship research upright. A1 is manual; Z1 is fully motorized with encoded stage for multi-position and Z-stack experiments. Full ICS optics with M27 thread objectives. ApoTome structured illumination available. Still widely in use in research institutions globally.",
   oem_source:null},

  {id:"zeiss-axio-scope",name:"Axio Scope.A1",series:"Axio Scope",type:"compound",subtype:"modular routine / education upright",
   introduced:2011,discontinued:false,price_tier:"mid",
   price_new:"$3,500–$9,000",price_used:"$700–$3,000",
   illumination:["Halogen 6V/30W","LED"],
   magnification:"40x–1000x (4x–100x objectives, 10x/20mm eyepieces)",
   objectives:"EC Plan-Neofluar / Plan-Achrostat (ICS)",
   eyepieces:"10x/20mm; binocular 30°; rotating head",stage:"Mechanical; optional motorized",
   fluorescence:true,phase_contrast:true,darkfield:true,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"ZEN Lite / ZEN Core",
   applications:["University teaching","Clinical labs","Multi-contrast biology","Industrial QC"],
   noteworthy:"Zeiss's current mid-tier modular upright, designed to accept the same filter and contrast accessories as the AxioImager at a lower price point. Widely adopted in university teaching labs as a step up from the Primo Star.",
   oem_source:null},

  {id:"zeiss-axio-lab",name:"Axio Lab.A1",series:"Axio Lab",type:"compound",subtype:"routine / education upright",
   introduced:2012,discontinued:false,price_tier:"budget",
   price_new:"$1,800–$4,000",price_used:"$400–$1,400",
   illumination:["LED (standard)"],
   magnification:"40x–1000x (4x–100x objectives, 10x/20mm eyepieces)",
   objectives:"A-Plan / EC Plan-Neofluar (ICS)",
   eyepieces:"10x/20mm; binocular 30°; 360° rotatable",stage:"Mechanical",
   fluorescence:false,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"ZEN Lite",
   applications:["Medical education","Clinical routine","Hematology","Basic biology"],
   noteworthy:"Replaced the Axiolab E as Zeiss's entry clinical/education upright. Full LED illumination standard. Simple, ergonomic, durable — designed for high-volume student and clinical use.",
   oem_source:null},

  {id:"zeiss-axio-vert",name:"Axio Vert.A1",series:"Axio Vert",type:"compound",subtype:"inverted routine",
   introduced:2011,discontinued:false,price_tier:"mid",
   price_new:"$4,000–$10,000",price_used:"$800–$3,200",
   illumination:["Halogen 6V/30W","LED"],
   magnification:"40x–400x (4x–40x LWD objectives, 10x/20mm eyepieces)",
   objectives:"LD Plan-Neofluar / EC Plan-Neofluar LD (ICS, long working distance)",
   eyepieces:"10x/20mm; binocular",stage:"Mechanical 145x105mm",
   fluorescence:true,phase_contrast:true,darkfield:false,dic:false,
   motorized:false,inverted:true,camera_port:true,
   software:"ZEN Lite",
   applications:["Cell culture QC","Tissue culture","IVF","Basic live cell","Phase contrast of cultures"],
   noteworthy:"Replaced the aging Axiovert 25/40 as Zeiss's routine inverted. ICS optics with fluorescence and phase contrast available. Compact footprint. Used in IVF clinics, biotech cell culture labs, and academic cell biology courses.",
   oem_source:null},

  {id:"zeiss-stemi1000",name:"Stemi 1000",series:"Stemi",type:"stereo",subtype:"zoom stereo",
   introduced:1993,discontinued:true,price_tier:"mid",
   price_new:null,price_used:"$300–$900",
   illumination:["Halogen (ring + transmitted base)"],
   magnification:"7x–45x (standard 10x/20mm eyepieces)",
   objectives:"Fixed Greenough zoom body 0.7x–4.5x (6.4:1 ratio)",
   eyepieces:"10x/20mm",stage:"Flat base; various stands",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["QC inspection","Dissection","Electronics","Education","Natural history"],
   noteworthy:"Zeiss's entry stereo in the 1990s–early 2000s. Greenough optical design. Simple, durable, and widely sold to European schools and industrial QC labs. Succeeded by the Stemi 2000 series.",
   oem_source:null},

  {id:"zeiss-stemi305",name:"Stemi 305",series:"Stemi",type:"stereo",subtype:"zoom stereo (Greenough)",
   introduced:2017,discontinued:false,price_tier:"budget",
   price_new:"$800–$1,800",price_used:"$250–$700",
   illumination:["LED ring + transmitted LED"],
   magnification:"8x–40x (5:1 zoom; standard 10x/21mm eyepieces)",
   objectives:"Fixed Greenough zoom body 0.8x–4.0x",
   eyepieces:"10x/21mm",stage:"Flat base; track stand option",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"ZEN Lite",
   applications:["Education","QC inspection","Electronics","Natural history","Hobbyist"],
   noteworthy:"Zeiss's current entry-level Greenough zoom stereo. Very compact and affordable, positioned below the Stemi 508. Fully LED. Widely adopted in university introductory biology courses. Compatible with the EyeEss document camera attachment.",
   oem_source:null},

  {id:"zeiss-stereo-v8",name:"SteREO Discovery.V8",series:"SteREO Discovery",type:"stereo",subtype:"research stereo",
   introduced:2004,discontinued:false,price_tier:"premium",
   price_new:"$12,000–$40,000",price_used:"$2,500–$10,000",
   illumination:["LED ring","HBO/LED fluorescence","Coaxial LED"],
   magnification:"8x–100x (10x eyepieces, 1x obj; up to 160x with 1.6x obj; 8:1 zoom)",
   objectives:"0.5x/1.0x/1.6x plan-apochromat auxiliary",
   eyepieces:"10x/23mm",stage:"Large format transmitted + reflected",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"ZEN Blue",
   applications:["Developmental biology","Fluorescence screening","Model organisms","Natural history"],
   noteworthy:"The lower-cost sibling in the SteREO Discovery line. 8:1 manual zoom. Accepts the same auxiliary objectives and accessories as the V12/V20. Full fluorescence capability. Widely used in developmental biology labs on tighter budgets.",
   oem_source:null},

  {id:"zeiss-stereo-v12",name:"SteREO Discovery.V12",series:"SteREO Discovery",type:"stereo",subtype:"research stereo",
   introduced:2005,discontinued:false,price_tier:"premium",
   price_new:"$20,000–$65,000",price_used:"$4,500–$18,000",
   illumination:["LED ring","HBO/LED fluorescence","Coaxial LED"],
   magnification:"7.5x–100x (10x eyepieces, 1x obj; up to 160x with 1.6x obj; 12:1 zoom)",
   objectives:"0.5x/1.0x/1.6x plan-apochromat auxiliary",
   eyepieces:"10x/23mm",stage:"Large format",
   fluorescence:true,phase_contrast:false,darkfield:false,dic:false,
   motorized:true,inverted:false,camera_port:true,
   software:"ZEN Blue",
   applications:["Developmental biology","Fluorescence screening","Model organisms","Neuroscience"],
   noteworthy:"12:1 motorized zoom. Mid-tier in the SteREO Discovery line between the V8 and V20. Motorized zoom with eZoom for reproducible magnification recall. Full fluorescence capability. PlasDIC for plastic culture vessels. Very widely used in developmental biology and model organism research.",
   oem_source:null}
,

{id:"zeiss-sv6",name:"Stemi SV6",series:"Stemi",type:"stereo",subtype:"zoom stereo (CMO, mid-tier)",
   introduced:1993,discontinued:false,price_tier:"mid",
   price_new:"$1,200–$3,500",price_used:"$300–$1,100",
   illumination:["Halogen (ring + transmitted base)"],
   magnification:"6x–50x (continuous zoom; 10x/20mm eyepieces; 8.3:1 zoom ratio; click-stops optional)",
   objectives:"CMO zoom body 0.6x–5.0x; 0.5x/1.5x/2x auxiliary objectives",
   eyepieces:"10x/20mm; binocular or trinocular 45 degree",stage:"Flat base; various stand options",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:true,
   software:"—",
   applications:["QC inspection","Dissection","Electronics","Embryology","Education","Natural history"],
   noteworthy:"The Stemi SV6 is Zeiss mid-tier CMO (Common Main Objective / parallel optics) stereo, positioned between the entry Stemi 2000 (Greenough) and the flagship SV11. 8.3:1 zoom with optional click-stops for reproducible magnification recall. CMO design gives superior image brightness and flatness vs. Greenough at equivalent magnification. Binocular and trinocular heads available. Compatible with SV11 objective and accessory system. Widely used in European industrial QC, IVF labs, and biology departments.",
   oem_source:null},

  {id:"zeiss-dv4",name:"Stemi DV4",series:"Stemi",type:"stereo",subtype:"zoom stereo (Greenough, education)",
   introduced:2000,discontinued:false,price_tier:"budget",
   price_new:"$400–$900",price_used:"$100–$350",
   illumination:["LED ring + transmitted LED (modern); Halogen (early versions)"],
   magnification:"8x–32x (4:1 zoom ratio; fixed 10x eyepieces)",
   objectives:"Fixed Greenough Double-lens-Vario zoom body; 0.5x/2x auxiliary",
   eyepieces:"Fixed 10x (built-in, not removable on standard version)",stage:"Flat base (C-stand)",
   fluorescence:false,phase_contrast:false,darkfield:false,dic:false,
   motorized:false,inverted:false,camera_port:false,
   software:"—",
   applications:["Education","Basic dissection","QC","Natural history","Hobbyist"],
   noteworthy:"The DV4 is Zeiss most affordable stereo — a compact sealed-optic Greenough scope with fixed integrated 10x eyepieces. The Double-lens-Vario design provides a sealed optical body resistant to dust and humidity. 4:1 zoom ratio (8x–32x). Simple and extremely durable for student use. A DV4 SPOT variant with fiber-optic cold-light illumination was offered for brighter incident illumination in demanding inspection work.",
   oem_source:null}

]});
